# Data Cleaning

In [484]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [485]:
from selenium import webdriver
import chromedriver_binary  # Adds chromedriver binary to path

In [486]:
df = pd.read_csv('metric_tonnes.csv', sep = ';')

In [487]:
#cut unneccesary columns from emissions data (source: world bank)
df = df.iloc[:, :-3]

In [488]:
#import bokeh libraries
from bokeh.io import output_file, show, save
from bokeh.models import ColumnDataSource, Legend, Label, BoxAnnotation, HoverTool, CategoricalColorMapper
from bokeh.models import LinearColorMapper,ColorBar, BasicTicker, PrintfTickFormatter, BasicTickFormatter, Title
from bokeh.models import NumeralTickFormatter, WheelZoomTool, BoxZoomTool, PrintfTickFormatter
from bokeh.plotting import figure
from bokeh.palettes import viridis, inferno, d3, Turbo256
from math import pi
from bokeh.transform import cumsum, transform
from bokeh.layouts import row,column
from bokeh.io import export_png

#colour palette
colour = d3['Category10'][10]
#d3['Category20'][15]

# Setting up function for country selection

In [489]:
#df of australia
df1 = df[df['Country Name'] == 'Australia']

df1 = df1.T

df1.rename(columns={ df1.columns[0]: "year" }, inplace = True)

df1 = df1[4:]

#df of world
dfw = df[df['Country Name'] == 'World']

dfw = dfw.T

dfw.rename(columns={ dfw.columns[0]: "year" }, inplace = True)

dfw = dfw[4:]

In [490]:
#function for getting country data
def country (name):
    frame = df[df['Country Name'] == name]
    frame = frame.T
    frame.rename(columns={ frame.columns[0]: "emissions" }, inplace = True)
    frame = frame[4:]
    frame = frame.reset_index()
    frame['country'] = name
    return frame

In [491]:
#data for different countries per capita
us = country('United States')
china = country('China')
world = country('World')
india = country ('India')

# Pik-potsdam data

In [492]:
#kyoto total ghg data
us_kyoto= pd.read_csv('us_kyoto.csv')
india_kyoto= pd.read_csv('india_kyoto.csv')
china_kyoto= pd.read_csv('china_kyoto.csv')
world_kyoto= pd.read_csv('world_kyoto.csv')
eu_kyoto = pd.read_csv('eu_kyoto.csv')
nl_kyoto = pd.read_csv('nl_kyoto.csv')
indo_kyoto = pd.read_csv('indonesia_kyoto.csv')
india_kyoto = pd.read_csv('india_kyoto.csv')
brazil_kyoto = pd.read_csv('brazil_kyoto.csv')
nigeria_kyoto = pd.read_csv('nigeria_kyoto.csv')
russia_kyoto = pd.read_csv('russia_kyoto.csv')
mor_kyoto = pd.read_csv('mor_kyoto.csv')

In [493]:
#add total column - function
def Total (df):
    
    df['total'] = df['IPC1'] + df['IPC2']+ df['IPC4'] + df['IPC5'] + df['IPCMAG']
    #make into kiloton
    df['total'] = df['total'] *1000000
    df = df[df['year'] >= 1960]
    return df

In [494]:
#add total to all df + > 1900
us_kyoto = Total(us_kyoto)
india_kyoto = Total(india_kyoto)
china_kyoto = Total(china_kyoto)
world_kyoto = Total(world_kyoto)
eu_kyoto = Total(eu_kyoto)
nl_kyoto = Total(nl_kyoto)
indo_kyoto = Total(indo_kyoto)
indo_kyoto = Total(indo_kyoto)
india_kyoto = Total(india_kyoto)
brazil_kyoto = Total(brazil_kyoto)
nigeria_kyoto = Total(nigeria_kyoto)
russia_kyoto = Total(russia_kyoto)
mor_kyoto = Total(mor_kyoto)

In [495]:
#add per capita emissions
pop = pd.read_csv('population_data.csv', sep = ';')
#Filter out 2020
pop = pop.iloc[:,:-1]

In [496]:
pop['Country Name'].unique()

array(['Aruba', 'Africa Eastern and Southern', 'Afghanistan',
       'Africa Western and Central', 'Angola', 'Albania', 'Andorra',
       'Arab World', 'United Arab Emirates', 'Argentina', 'Armenia',
       'American Samoa', 'Antigua and Barbuda', 'Australia', 'Austria',
       'Azerbaijan', 'Burundi', 'Belgium', 'Benin', 'Burkina Faso',
       'Bangladesh', 'Bulgaria', 'Bahrain', 'Bahamas, The',
       'Bosnia and Herzegovina', 'Belarus', 'Belize', 'Bermuda',
       'Bolivia', 'Brazil', 'Barbados', 'Brunei Darussalam', 'Bhutan',
       'Botswana', 'Central African Republic', 'Canada',
       'Central Europe and the Baltics', 'Switzerland', 'Channel Islands',
       'Chile', 'China', "Cote d'Ivoire", 'Cameroon', 'Congo, Dem. Rep.',
       'Congo, Rep.', 'Colombia', 'Comoros', 'Cabo Verde', 'Costa Rica',
       'Caribbean small states', 'Cuba', 'Curacao', 'Cayman Islands',
       'Cyprus', 'Czech Republic', 'Germany', 'Djibouti', 'Dominica',
       'Denmark', 'Dominican Republic', 'Algeria',
       'East Asia & Pacific (excluding high income)',
       'Early-demographic dividend', 'East Asia & Pacific',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia', 'Ecuador', 'Egypt, Arab Rep.',
       'Euro area', 'Eritrea', 'Spain', 'Estonia', 'Ethiopia',
       'European Union', 'Fragile and conflict affected situations',
       'Finland', 'Fiji', 'France', 'Faroe Islands',
       'Micronesia, Fed. Sts.', 'Gabon', 'United Kingdom', 'Georgia',
       'Ghana', 'Gibraltar', 'Guinea', 'Gambia, The', 'Guinea-Bissau',
       'Equatorial Guinea', 'Greece', 'Grenada', 'Greenland', 'Guatemala',
       'Guam', 'Guyana', 'High income', 'Hong Kong SAR, China',
       'Honduras', 'Heavily indebted poor countries (HIPC)', 'Croatia',
       'Haiti', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA total',
       'IDA blend', 'Indonesia', 'IDA only', 'Isle of Man', 'India',
       'Not classified', 'Ireland', 'Iran, Islamic Rep.', 'Iraq',
       'Iceland', 'Israel', 'Italy', 'Jamaica', 'Jordan', 'Japan',
       'Kazakhstan', 'Kenya', 'Kyrgyz Republic', 'Cambodia', 'Kiribati',
       'St. Kitts and Nevis', 'Korea, Rep.', 'Kuwait',
       'Latin America & Caribbean (excluding high income)', 'Lao PDR',
       'Lebanon', 'Liberia', 'Libya', 'St. Lucia',
       'Latin America & Caribbean',
       'Least developed countries: UN classification', 'Low income',
       'Liechtenstein', 'Sri Lanka', 'Lower middle income',
       'Low & middle income', 'Lesotho', 'Late-demographic dividend',
       'Lithuania', 'Luxembourg', 'Latvia', 'Macao SAR, China',
       'St. Martin (French part)', 'Morocco', 'Monaco', 'Moldova',
       'Madagascar', 'Maldives', 'Middle East & North Africa', 'Mexico',
       'Marshall Islands', 'Middle income', 'North Macedonia', 'Mali',
       'Malta', 'Myanmar',
       'Middle East & North Africa (excluding high income)', 'Montenegro',
       'Mongolia', 'Northern Mariana Islands', 'Mozambique', 'Mauritania',
       'Mauritius', 'Malawi', 'Malaysia', 'North America', 'Namibia',
       'New Caledonia', 'Niger', 'Nigeria', 'Nicaragua', 'Netherlands',
       'Norway', 'Nepal', 'Nauru', 'New Zealand', 'OECD members', 'Oman',
       'Other small states', 'Pakistan', 'Panama', 'Peru', 'Philippines',
       'Palau', 'Papua New Guinea', 'Poland', 'Pre-demographic dividend',
       'Puerto Rico', "Korea, Dem. People's Rep.", 'Portugal', 'Paraguay',
       'West Bank and Gaza', 'Pacific island small states',
       'Post-demographic dividend', 'French Polynesia', 'Qatar',
       'Romania', 'Russian Federation', 'Rwanda', 'South Asia',
       'Saudi Arabia', 'Sudan', 'Senegal', 'Singapore', 'Solomon Islands',
       'Sierra Leone', 'El Salvador', 'San Marino', 'Somalia', 'Serbia',
       'Sub-Saharan Africa (excluding high income)', 'South Sudan',
       'Sub-Saharan Africa', 'Small states', 'Sao Tome and Principe',
       'Suriname', 'Slovak Republic', 'Slovenia', 'Sweden', 'Eswatini',
       'Sint Maarten (Dutch part)', 'Seychelles', 'Syrian Arab Republic',
       'Turks and Caicos Islands', 'Chad',
       'East Asia & Pacific (IDA & IBRD countries)',
       'Europe & Central Asia (IDA & IBRD countries)', 'Togo', 'Thailand',
       'Tajikistan', 'Turkmenistan',
       'Latin America & the Caribbean (IDA & IBRD countries)',
       'Timor-Leste', 'Middle East & North Africa (IDA & IBRD countries)',
       'Tonga', 'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Tuvalu', 'Tanzania', 'Uganda', 'Ukraine',
       'Upper middle income', 'Uruguay', 'United States', 'Uzbekistan',
       'St. Vincent and the Grenadines', 'Venezuela, RB',
       'British Virgin Islands', 'Virgin Islands (U.S.)', 'Vietnam',
       'Vanuatu', 'World', 'Samoa', 'Kosovo', 'Yemen, Rep.',
       'South Africa', 'Zambia', 'Zimbabwe'], dtype=object)

In [497]:
def per_capita(df, name):
    
    temp = pop[pop['Country Name'] == name]
    population = list(temp.iloc[0, 1:])
    df['pop'] = population
    df['pc'] = df['total'] / df['pop']
    
    return df

In [498]:
china_kyoto = per_capita(china_kyoto, 'China')
india_kyoto = per_capita(india_kyoto, 'India')
us_kyoto = per_capita(us_kyoto, 'United States')
world_kyoto = per_capita(world_kyoto, 'World')
eu_kyoto = per_capita(eu_kyoto, 'European Union')
nl_kyoto = per_capita(nl_kyoto, 'Netherlands')
indo_kyoto = per_capita(indo_kyoto, 'Indonesia')
india_kyoto =per_capita(india_kyoto, 'India')
brazil_kyoto =per_capita(brazil_kyoto, 'Brazil')
nigeria_kyoto =per_capita(nigeria_kyoto, 'Nigeria')
russia_kyoto =per_capita(russia_kyoto, 'Russian Federation')
mor_kyoto =per_capita(mor_kyoto, 'Morocco')

#make total to gt
us_kyoto['total_'] = us_kyoto.total/1000000000
india_kyoto['total_'] = india_kyoto.total/1000000000
china_kyoto['total_'] = china_kyoto.total/1000000000
eu_kyoto['total_'] = eu_kyoto.total/1000000000
world_kyoto['total_'] = world_kyoto.total/1000000000
nl_kyoto['total_'] = nl_kyoto.total/1000000000
indo_kyoto['total_'] = indo_kyoto.total/1000000000
india_kyoto['total_'] =india_kyoto.total/1000000000
brazil_kyoto['total_'] =brazil_kyoto.total/1000000000
nigeria_kyoto['total_'] =nigeria_kyoto.total/1000000000
russia_kyoto['total_'] =russia_kyoto.total/1000000000
mor_kyoto['total_'] =mor_kyoto.total/1000000000


#extra column for for megaton
nl_kyoto['mega'] = nl_kyoto.total/1000000
indo_kyoto['mega'] = indo_kyoto.total/1000000
mor_kyoto['mega'] =mor_kyoto.total/1000000
nigeria_kyoto['mega'] =nigeria_kyoto.total/1000000
brazil_kyoto['mega'] =brazil_kyoto.total/1000000


russia_kyoto

,year,IPC1,IPC2,IPC4,IPC5,IPCMAG,total,pop,pc,total_
210,1960,1070.0,142.0,32.8,5.88,152.0,1.402680e+09,119897000.0,11.699042,1.40268
211,1961,1100.0,149.0,34.0,5.90,153.0,1.441900e+09,121236000.0,11.893332,1.44190
212,1962,1150.0,159.0,35.2,5.93,162.0,1.512130e+09,122591000.0,12.334755,1.51213
213,1963,1230.0,172.0,36.5,5.96,168.0,1.612460e+09,123960000.0,13.007906,1.61246
214,1964,1290.0,184.0,37.7,5.99,165.0,1.682690e+09,125345000.0,13.424468,1.68269
215,1965,1360.0,200.0,39.0,6.02,168.0,1.773020e+09,126745000.0,13.988875,1.77302
216,1966,1420.0,215.0,40.2,6.04,180.0,1.861240e+09,127468000.0,14.601626,1.86124
217,1967,1470.0,226.0,41.4,6.07,185.0,1.928470e+09,128196000.0,15.043137,1.92847
218,1968,1490.0,233.0,42.5,6.10,188.0,1.959600e+09,128928000.0,15.199181,1.95960
219,1969,1540.0,243.0,43.7,6.13,187.0,2.019830e+09,129664000.0,15.577415,2.01983
220,1970,1670.0,239.0,43.5,5.84,196.0,2.154340e+09,130404000.0,16.520506,2.15434
221,1971,1740.0,237.0,45.5,5.84,205.0,2.233340e+09,131155000.0,17.028249,2.23334
222,1972,1830.0,251.0,46.2,6.23,210.0,2.343430e+09,131909000.0,17.765505,2.34343
223,1973,1910.0,269.0,47.1,6.68,217.0,2.449780e+09,132669000.0,18.465354,2.44978
224,1974,1980.0,265.0,48.5,7.12,221.0,2.521620e+09,133432000.0,18.898165,2.52162
225,1975,2080.0,263.0,49.2,7.81,226.0,2.626010e+09,134200000.0,19.567884,2.62601
226,1976,2160.0,275.0,50.0,7.84,228.0,2.720840e+09,135147000.0,20.132448,2.72084
227,1977,2230.0,276.0,50.8,8.02,228.0,2.792820e+09,136100000.0,20.520353,2.79282
228,1978,2370.0,275.0,51.4,8.25,234.0,2.938650e+09,137060000.0,21.440610,2.93865
229,1979,2400.0,270.0,51.1,8.43,234.0,2.963530e+09,138027000.0,21.470654,2.96353
230,1980,2480.0,270.0,51.8,8.64,239.0,3.049440e+09,139010000.0,21.936839,3.04944
231,1981,2450.0,268.0,52.4,9.00,238.0,3.017400e+09,139941000.0,21.561944,3.01740
232,1982,2500.0,252.0,53.8,9.06,243.0,3.057860e+09,140823000.0,21.714209,3.05786
233,1983,2530.0,255.0,54.8,9.09,251.0,3.099890e+09,141668000.0,21.881371,3.09989
234,1984,2540.0,271.0,56.0,9.12,253.0,3.129120e+09,142745000.0,21.921048,3.12912
235,1985,2720.0,269.0,55.8,9.18,257.0,3.310980e+09,143858000.0,23.015613,3.31098
236,1986,2730.0,279.0,56.9,9.30,260.0,3.335200e+09,144894000.0,23.018206,3.33520
237,1987,2730.0,283.0,57.5,9.42,262.0,3.341920e+09,145908000.0,22.904296,3.34192
238,1988,2810.0,290.0,58.0,9.39,257.0,3.424390e+09,146857000.0,23.317853,3.42439
239,1989,2760.0,291.0,59.3,9.21,252.0,3.371510e+09,147721000.0,22.823498,3.37151
240,1990,2600.0,283.0,59.3,10.40,247.0,3.199700e+09,147969407.0,21.624064,3.19970
241,1991,2480.0,260.0,59.2,10.10,235.0,3.044300e+09,148394216.0,20.514951,3.04430
242,1992,2050.0,232.0,58.4,9.51,223.0,2.572910e+09,148538197.0,17.321538,2.57291
243,1993,1950.0,199.0,58.5,9.63,206.0,2.423130e+09,148458777.0,16.321905,2.42313
244,1994,1730.0,174.0,58.0,8.14,184.0,2.154140e+09,148407912.0,14.514994,2.15414
245,1995,1690.0,183.0,58.3,7.30,163.0,2.101600e+09,148375787.0,14.164036,2.10160
246,1996,1670.0,166.0,58.4,7.12,151.0,2.052520e+09,148160129.0,13.853390,2.05252
247,1997,1560.0,167.0,59.3,6.38,139.0,1.931680e+09,147915361.0,13.059360,1.93168
248,1998,1550.0,159.0,59.9,6.65,125.0,1.900550e+09,147670784.0,12.870183,1.90055
249,1999,1570.0,180.0,61.0,6.59,119.0,1.936590e+09,147214776.0,13.154862,1.93659
250,2000,1540.0,196.0,62.0,6.59,119.0,1.923590e+09,146596869.0,13.121631,1.92359
251,2001,1580.0,194.0,63.4,6.62,116.0,1.960020e+09,145976482.0,13.426957,1.96002
252,2002,1550.0,191.0,64.7,6.50,115.0,1.927200e+09,145306497.0,13.263000,1.92720
253,2003,1590.0,193.0,66.2,6.44,113.0,1.968640e+09,144648618.0,13.609809,1.96864
254,2004,1600.0,207.0,67.6,6.29,110.0,1.990890e+09,144067316.0,13.819165,1.99089
255,2005,1610.0,207.0,69.5,6.17,105.0,1.997670e+09,143518814.0,13.919220,1.99767
256,2006,1650.0,214.0,71.3,6.29,103.0,2.044590e+09,143049637.0,14.292871,2.04459
257,2007,1650.0,215.0,73.6,6.08,105.0,2.049680e+09,142805114.0,14.352987,2.04968
258,2008,1670.0,207.0,75.4,5.99,109.0,2.067390e+09,142742366.0,14.483366,2.06739
259,2009,1580.0,180.0,76.9,5.60,107.0,1.949500e+09,142785349.0,13.653362,1.94950
260,2010,1660.0,196.0,78.4,5.69,104.0,2.044090e+09,142849468.0,14.309399,2.04409
261,2011,1710.0,200.0,81.5,6.05,106.0,2.103550e+09,142960908.0,14.714162,2.10355
262,2012,1720.0,216.0,83.9,6.20,105.0,2.131100e+09,143201721.0,14.881804,2.13110
263,2013,1640.0,220.0,86.5,5.99,108.0,2.060490e+09,143506995.0,14.358115,2.06049
264,2014,1640.0,220.0,89.9,5.90,108.0,2.063800e+09,143819667.0,14.349915,2.06380
265,2015,1660.0,219.0,92.1,5.81,109.0,2.085910e+09,144096870.0,14.475748,2.08591
266,2016,1650.0,218.0,94.1,5.54,112.0,2.079640e+09,144342397.0,14.407686,2.07964
267,2017,1670.0,233.0,96.2,5.57,113.0,2.117770e+09,144496739.0,14.656179,2.11777
268,2018,1720.0,243.0,98.2,5.60,113.0,2.179800e+09,144477859.0,15.087433,2.17980
269,2019,1710.0,237.0,100.0,5.57,114.0,2.166570e+09,144406261.0,15.003297,2.16657

# projection data

In [499]:
#read and deal with projection data
us_proj = pd.read_csv('us_proj.csv', sep = ';')

In [500]:
#helper function for cleaning df
def projections(df, name = None):
    df.rename(columns={ df.columns[0]: "projection" }, inplace = True)
    df = df.T
    df = df.rename(columns=df.iloc[0]).drop(df.index[0])
    
    #convert to int
    for col in df.columns:
        df[col] = df[col].str.replace(',','.')
        df[col] = pd.to_numeric(df[col])
    
        
    df['avg'] = (df['minimum']+df['maximum'])/2
    
    if name in ['morocco', 'nigeria', 'brazil']:
        df = df.reset_index()
        return df
    else:
        df = df[['paris', 'minimum', 'maximum', 'avg']]/1000
        df = df.reset_index()

        return df

In [501]:
us_proj = projections(us_proj)
us_proj.head()

  index   paris  minimum  maximum     avg
0  2020  6.5255    5.956    5.960  5.9580
1  2021  6.1625    6.275    6.278  6.2765
2  2022  5.7995    6.366    6.397  6.3815
3  2023  5.4365    6.310    6.333  6.3215
4  2024  5.0735    6.208    6.266  6.2370

In [502]:
china_proj = pd.read_csv('china_proj.csv', sep = ';')
china_proj.head()

,Unnamed: 0,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030
0,paris,"14017,1","13345,9","12674,7","12003,5","11332,3","10661,2","10071,2","9481,1","8891,1","8301,1","7711,1"
1,minimum,13341,13633,13826,13819,13854,13851,13812,13790,13662,13548,13433
2,maximum,13341,13633,13826,14060,14146,14233,14319,14405,14414,14424,14433

In [503]:
china_proj = projections(china_proj)
china_proj.head()

  index    paris  minimum  maximum      avg
0  2020  14.0171   13.341   13.341  13.3410
1  2021  13.3459   13.633   13.633  13.6330
2  2022  12.6747   13.826   13.826  13.8260
3  2023  12.0035   13.819   14.060  13.9395
4  2024  11.3323   13.854   14.146  14.0000

In [504]:
eu_proj = pd.read_csv('eu_proj.csv', sep = ';')
eu_proj = projections(eu_proj)
eu_proj.head()

  index   paris  minimum  maximum     avg
0  2020  3.6875    3.186    3.186  3.1860
1  2021  3.4709    3.125    3.271  3.1980
2  2022  3.2544    3.064    3.347  3.2055
3  2023  3.0378    3.004    3.320  3.1620
4  2024  2.8212    2.943    3.294  3.1185

In [505]:
indo_proj = pd.read_csv('indo_proj.csv', sep = ';')

indo_proj = projections(indo_proj, 'indonesia')
indo_proj

   index   paris  minimum  maximum     avg
0   2020  0.8817    0.892    0.942  0.9170
1   2021  0.8437    0.882    0.970  0.9260
2   2022  0.8057    0.906    1.001  0.9535
3   2023  0.7676    0.931    1.032  0.9815
4   2024  0.7296    0.955    1.063  1.0090
5   2025  0.6916    0.979    1.094  1.0365
6   2026  0.6651    1.021    1.140  1.0805
7   2027  0.6386    1.064    1.187  1.1255
8   2028  0.6121    1.106    1.233  1.1695
9   2029  0.5857    1.149    1.279  1.2140
10  2030  0.5592    1.191    1.326  1.2585

In [506]:
#load data on india
india_proj = pd.read_csv('india_proj.csv', sep = ';')

india_proj = projections(india_proj, 'india')
india_proj

   index   paris  minimum  maximum     avg
0   2020  3.0105    2.923    2.923  2.9230
1   2021  2.8796    3.054    3.054  3.0540
2   2022  2.7487    3.135    3.170  3.1525
3   2023  2.6179    3.216    3.287  3.2515
4   2024  2.4870    3.297    3.403  3.3500
5   2025  2.3561    3.378    3.528  3.4530
6   2026  2.2575    3.470    3.641  3.5555
7   2027  2.1589    3.563    3.738  3.6505
8   2028  2.0603    3.655    3.835  3.7450
9   2029  1.9617    3.747    3.932  3.8395
10  2030  1.8631    3.841    4.024  3.9325

In [507]:
#load data on brazil
brazil_proj = pd.read_csv('brazil_proj.csv', sep = ';')

brazil_proj = projections(brazil_proj, 'brazil')
brazil_proj

   index  minimum  maximum   paris     avg
0   2020      973      982  1070.5   977.5
1   2021      980      988  1036.1   984.0
2   2022      987      995  1001.8   991.0
3   2023      993     1001   967.4   997.0
4   2024      997     1006   933.0  1001.5
5   2025     1001     1010   898.7  1005.5
6   2026     1006     1015   861.8  1010.5
7   2027     1011     1021   824.9  1016.0
8   2028     1017     1027   788.0  1022.0
9   2029     1024     1033   751.1  1028.5
10  2030     1029     1039   714.2  1034.0

In [508]:
brazil_lul = pd.read_csv('brazil_proj_lul.csv', sep = ';')

brazil_lul = brazil_lul.fillna(0)

def projections_b(df, name = None):
    df.rename(columns={ df.columns[0]: "projection" }, inplace = True)
    df = df.T
    df = df.rename(columns=df.iloc[0]).drop(df.index[0])
    
    df['paris'] = df['paris'].str.replace(',','.')
    df['paris'] = pd.to_numeric(df['paris']).fillna(0)
    df['minimum'] = pd.to_numeric(df['minimum'])
    df['maximum'] = pd.to_numeric(df['maximum'])
    df['history'] = pd.to_numeric(df['history'])
    df['lulucf'] = pd.to_numeric(df['lulucf'])
    
    df['avg'] = (df['minimum']+df['maximum'])/2


    df = df[['paris', 'minimum', 'maximum', 'avg','history', 'lulucf']]/1000
    df = df.reset_index()

    
    return df

brazil_lul = projections_b(brazil_lul)
brazil_lul

   index   paris  minimum  maximum     avg  history  lulucf
0   2000  0.0000    0.000    0.000  0.0000    0.740   1.301
1   2001  0.0000    0.000    0.000  0.0000    0.758   1.299
2   2002  0.0000    0.000    0.000  0.0000    0.775   1.518
3   2003  0.0000    0.000    0.000  0.0000    0.792   2.480
4   2004  0.0000    0.000    0.000  0.0000    0.828   2.679
5   2005  0.0000    0.000    0.000  0.0000    0.847   1.947
6   2006  0.0000    0.000    0.000  0.0000    0.855   1.527
7   2007  0.0000    0.000    0.000  0.0000    0.861   1.312
8   2008  0.0000    0.000    0.000  0.0000    0.890   1.417
9   2009  0.0000    0.000    0.000  0.0000    0.880   0.459
10  2010  0.0000    0.000    0.000  0.0000    0.943   0.388
11  2011  0.0000    0.000    0.000  0.0000    0.980   0.323
12  2012  0.0000    0.000    0.000  0.0000    1.011   0.290
13  2013  0.0000    0.000    0.000  0.0000    1.050   0.431
14  2014  0.0000    0.000    0.000  0.0000    1.080   0.274
15  2015  0.0000    0.000    0.000  0.0000    1.056   0.373
16  2016  0.0000    0.000    0.000  0.0000    1.028   0.395
17  2017  0.0000    0.000    0.000  0.0000    1.036   0.327
18  2018  0.0000    1.013    1.013  1.0130    1.013   0.353
19  2019  0.0000    1.019    1.020  1.0195    0.000   0.000
20  2020  1.0705    0.973    0.982  0.9775    0.000   0.000
21  2021  1.0361    0.980    0.988  0.9840    0.000   0.000
22  2022  1.0018    0.987    0.995  0.9910    0.000   0.000
23  2023  0.9674    0.993    1.001  0.9970    0.000   0.000
24  2024  0.9330    0.997    1.006  1.0015    0.000   0.000
25  2025  0.8987    1.001    1.010  1.0055    0.000   0.000
26  2026  0.8618    1.006    1.015  1.0105    0.000   0.000
27  2027  0.8249    1.011    1.021  1.0160    0.000   0.000
28  2028  0.7880    1.017    1.027  1.0220    0.000   0.000
29  2029  0.7511    1.024    1.033  1.0285    0.000   0.000
30  2030  0.7142    1.029    1.039  1.0340    0.000   0.000

In [509]:
#load data on nigeria
nigeria_proj = pd.read_csv('nigeria_proj.csv', sep = ';')

nigeria_proj = projections(nigeria_proj, 'nigeria')
nigeria_proj

   index  minimum  maximum  paris    avg
0   2020      320      320  374.9  320.0
1   2021      323      330  364.5  326.5
2   2022      327      339  354.0  333.0
3   2023      330      349  343.6  339.5
4   2024      334      358  333.2  346.0
5   2025      338      368  322.8  353.0
6   2026      342      377  312.0  359.5
7   2027      346      387  301.2  366.5
8   2028      350      396  290.4  373.0
9   2029      354      406  279.6  380.0
10  2030      358      416  268.8  387.0

In [510]:
#load data on russia
russia_proj = pd.read_csv('russia_proj.csv', sep = ';')

russia_proj = projections(russia_proj, 'russia')
russia_proj

   index   paris  minimum  maximum     avg
0   2020  2.0940    1.986    2.035  2.0105
1   2021  1.9932    2.013    2.071  2.0420
2   2022  1.8925    2.012    2.081  2.0465
3   2023  1.7918    2.012    2.092  2.0520
4   2024  1.6911    2.012    2.102  2.0570
5   2025  1.5904    2.012    2.112  2.0620
6   2026  1.4947    2.011    2.122  2.0665
7   2027  1.3990    2.011    2.132  2.0715
8   2028  1.3034    2.011    2.143  2.0770
9   2029  1.2077    2.011    2.153  2.0820
10  2030  1.1120    2.010    2.163  2.0865

In [511]:
#load data on morocco
morocco_proj = pd.read_csv('morocco_proj.csv', sep = ';')

morocco_proj = projections(morocco_proj, 'morocco')
morocco_proj

   index  minimum  maximum  paris   avg
0   2020       76       84  102.3  80.0
1   2021       76       89   99.7  82.5
2   2022       76       92   97.1  84.0
3   2023       76       96   94.5  86.0
4   2024       76       99   91.9  87.5
5   2025       76      102   89.3  89.0
6   2026       77      106   85.9  91.5
7   2027       77      110   82.4  93.5
8   2028       78      114   78.9  96.0
9   2029       78      118   75.4  98.0
10  2030       78      121   71.9  99.5

# Visualisations per capita co2

In [512]:
us_kyoto.head()

,year,IPC1,IPC2,IPC4,IPC5,IPCMAG,total,pop,pc,total_
210,1960,3260.0,315.0,114.0,26.6,441.0,4.156600e+09,180671000.0,23.006459,4.1566
211,1961,3250.0,328.0,122.0,26.8,453.0,4.179800e+09,183691000.0,22.754517,4.1798
212,1962,3380.0,353.0,130.0,26.9,466.0,4.355900e+09,186538000.0,23.351274,4.3559
213,1963,3540.0,384.0,139.0,27.0,481.0,4.571000e+09,189242000.0,24.154258,4.5710
214,1964,3700.0,416.0,147.0,27.2,489.0,4.779200e+09,191889000.0,24.906065,4.7792

In [513]:
"""
# visualisation of US tonnes co2 emission vs world average
#data source: https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=ind&entity=kyotoghgar4
output_file('us_per_capita.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Greenhouse gas emissions per capita (tonnes CO2e)', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019),y_range = (0,45))

#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


first = p.line(x='year',y= 'pc',source=us_kyoto, color = colour[0],line_width = 7, legend_label="US")
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))

second = p.line(x='year',y= 'pc',source=world_kyoto, color = colour[7],line_width = 4, line_dash = 'dashed', legend_label="World", alpha = 0.5)
p.add_tools(HoverTool(renderers=[second], tooltips=[('Region', 'World'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

third = p.line(x='year',y= 'pc',source=eu_kyoto, color = colour[3],line_width = 4, legend_label="EU", alpha = 0.5)
p.add_tools(HoverTool(renderers=[third], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

fourth = p.line(x='year',y= 'pc',source=china_kyoto, color = colour[2],line_width = 4, legend_label="China", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))

fifth = p.line(x='year',y= 'pc',source=india_kyoto, color = colour[1],line_width = 4, legend_label="India", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fifth], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'The PRIMAP-hist national historical emissions time series'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')


p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

#export_png(p, filename="us_per_capita.png")

show(p)
save(p)
"""

'\n# visualisation of US tonnes co2 emission vs world average\n#data source: https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=ind&entity=kyotoghgar4\noutput_file(\'us_per_capita.html\')\n\n#create figure\np = figure(x_axis_label=\'Year\', y_axis_label=\'Greenhouse gas emissions per capita (tonnes CO2e)\', \n            sizing_mode=\'stretch_both\', toolbar_location=None,x_range = (1960, 2019),y_range = (0,45))\n\n#Disable scientific notation on axes\np.left[0].formatter.use_scientific = False\np.below[0].formatter.use_scientific = False\n\n\nfirst = p.line(x=\'year\',y= \'pc\',source=us_kyoto, color = colour[0],line_width = 7, legend_label="US")\np.add_tools(HoverTool(renderers=[first], tooltips=[(\'Country\', \'US\'),(\'Year\',"@year"),(\'Emissions\',"@pc{0.0} t")],mode=\'mouse\', toggleable=False))\n\nsecond = p.line(x=\'year\',y= \'pc\',source=world_kyoto, color = colour[7],line_width = 4, line_dash = \'dashed\', legend_label="World", alpha = 0.5)\np.add_tools(HoverTool(renderers=[second], tooltips=[(\'Region\', \'World\'),(\'Year\',"@year"),(\'Emissions\',"@pc{0.0} t")],mode=\'mouse\',toggleable=False))\n\nthird = p.line(x=\'year\',y= \'pc\',source=eu_kyoto, color = colour[3],line_width = 4, legend_label="EU", alpha = 0.5)\np.add_tools(HoverTool(renderers=[third], tooltips=[(\'Region\', \'EU\'),(\'Year\',"@year"),(\'Emissions\',"@pc{0.0} t")],mode=\'mouse\',toggleable=False))\n\nfourth = p.line(x=\'year\',y= \'pc\',source=china_kyoto, color = colour[2],line_width = 4, legend_label="China", alpha = 0.5)\np.add_tools(HoverTool(renderers=[fourth], tooltips=[(\'Country\', \'China\'),(\'Year\',"@year"),(\'Emissions\',"@pc{0.0} t")],mode=\'mouse\', toggleable=False))\n\nfifth = p.line(x=\'year\',y= \'pc\',source=india_kyoto, color = colour[1],line_width = 4, legend_label="India", alpha = 0.5)\np.add_tools(HoverTool(renderers=[fifth], tooltips=[(\'Country\', \'India\'),(\'Year\',"@year"),(\'Emissions\',"@pc{0.0} t")],mode=\'mouse\', toggleable=False))\n\n#add data sources below charts\nlabel_opts = dict(x = 0, y = 0, x_units = \'screen\', y_units =\'screen\')\nmsg = \'Data source:\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np.add_layout(caption1, \'below\')\nmsg = \'The PRIMAP-hist national historical emissions time series\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'7pt\', text_font_style = \'italic\')\np.add_layout(caption1, \'below\')\n\n\np.xaxis.major_label_orientation = 120\np.toolbar.active_drag = None\n\n#export_png(p, filename="us_per_capita.png")\n\nshow(p)\nsave(p)\n'

In [514]:
# visualisation of China tonnes co2 emission vs world average
#data source: https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=ind&entity=kyotoghgar4
output_file('china_per_capita.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Annual greenhouse gas emissions per capita (tonnes CO2e)',title = 'China\'s per capita emissions are above the world average', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019), y_range=(0,45))


p.add_layout(Title(text="Per capita emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')

#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


fourth = p.line(x='year',y= 'pc',source=china_kyoto, color = colour[2],line_width = 7, legend_label="China")
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))

second = p.line(x='year',y= 'pc',source=world_kyoto, color = colour[7],line_width = 4, line_dash = 'dashed', legend_label="World", alpha = 0.5)
p.add_tools(HoverTool(renderers=[second], tooltips=[('Region', 'World'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

eu = p.line(x='year',y= 'pc',source=eu_kyoto, color = colour[3],line_width = 4, legend_label="EU", alpha = 0.5)
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))


first = p.line(x='year',y= 'pc',source=us_kyoto, color = colour[0],line_width = 4, legend_label="US", alpha = 0.5)
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))

third = p.line(x='year',y= 'pc',source=india_kyoto, color = colour[1],line_width = 4, legend_label="India", alpha = 0.5)
p.add_tools(HoverTool(renderers=[third], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:The PRIMAP-hist national historical'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'emissions time series and the World Bank'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None
show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/china_per_capita.html'

In [515]:
# visualisation of NL  tonnes co2 emission vs world average
#data source: https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=ind&entity=kyotoghgar4
output_file('nl_per_capita.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Annual greenhouse gas emissions per capita (tonnes CO2e)', 
           title = 'Per capita emissions in the Netherlands are around double the global average', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019), y_range=(0,45))

#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False

p.add_layout(Title(text="Per capita emissions in different countries/regions", text_font_style="italic", text_font_size = '10px',), 'above')

nl = p.line(x='year',y= 'pc',source=nl_kyoto, color = colour[4],line_width = 7, legend_label="Netherlands")
p.add_tools(HoverTool(renderers=[nl], tooltips=[('Country', 'Netherlands'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


second = p.line(x='year',y= 'pc',source=world_kyoto, color = colour[7],line_width = 4, line_dash = 'dashed', legend_label="World", alpha = 0.5)
p.add_tools(HoverTool(renderers=[second], tooltips=[('Region', 'World'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

first = p.line(x='year',y= 'pc',source=us_kyoto, color = colour[0],line_width = 4, legend_label="US", alpha = 0.5)
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


third = p.line(x='year',y= 'pc',source=eu_kyoto, color = colour[3],line_width = 4, legend_label="EU", alpha = 0.5)
p.add_tools(HoverTool(renderers=[third], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

fourth = p.line(x='year',y= 'pc',source=china_kyoto, color = colour[2],line_width = 4, legend_label="China", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


fifth = p.line(x='year',y= 'pc',source=india_kyoto, color = colour[1],line_width = 4, legend_label="India", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fifth], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:The PRIMAP-hist national historical'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'emissions time series and the World Bank'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/nl_per_capita.html'

In [516]:
# visualisation of Brazil  tonnes co2 emission vs world average
#data source: https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=ind&entity=kyotoghgar4
output_file('brazil_per_capita.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Annual greenhouse gas emissions per capita (tonnes CO2e)', title = 'Brazil\'s per capita emissions are below the world average', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019), y_range=(0,45))

p.add_layout(Title(text="Per capita emissions in different countries/regions (excluding land use)", text_font_style="italic", text_font_size = '10px',), 'above')

#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


br = p.line(x='year',y= 'pc',source=brazil_kyoto, color = colour[4],line_width = 7, legend_label="Brazil")
p.add_tools(HoverTool(renderers=[br], tooltips=[('Country', 'Brazil'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


second = p.line(x='year',y= 'pc',source=world_kyoto, color = colour[7],line_width = 4, line_dash = 'dashed', legend_label="World", alpha = 0.5)
p.add_tools(HoverTool(renderers=[second], tooltips=[('Region', 'World'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

first = p.line(x='year',y= 'pc',source=us_kyoto, color = colour[0],line_width = 4, legend_label="US", alpha = 0.5)
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


third = p.line(x='year',y= 'pc',source=eu_kyoto, color = colour[3],line_width = 4, legend_label="EU", alpha = 0.5)
p.add_tools(HoverTool(renderers=[third], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

fourth = p.line(x='year',y= 'pc',source=china_kyoto, color = colour[2],line_width = 4, legend_label="China", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


fifth = p.line(x='year',y= 'pc',source=india_kyoto, color = colour[1],line_width = 4, legend_label="India", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fifth], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:The PRIMAP-hist national historical'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'emissions time series and the World Bank'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/brazil_per_capita.html'

In [663]:
# visualisation of Nigeria  tonnes co2 emission vs world average
#data source: https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=ind&entity=kyotoghgar4
output_file('nigeria_per_capita.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Annual greenhouse gas emissions per capita (tonnes CO2e)', title ='Nigeria\'s per capita emissions are less than a third of the global average', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019), y_range=(0,45))

p.add_layout(Title(text="Per capita emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')

#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


ni = p.line(x='year',y= 'pc',source=nigeria_kyoto, color = colour[4],line_width = 7, legend_label="Nigeria")
p.add_tools(HoverTool(renderers=[ni], tooltips=[('Country', 'Nigeria'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


second = p.line(x='year',y= 'pc',source=world_kyoto, color = colour[7],line_width = 4, line_dash = 'dashed', legend_label="World", alpha = 0.5)
p.add_tools(HoverTool(renderers=[second], tooltips=[('Region', 'World'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

first = p.line(x='year',y= 'pc',source=us_kyoto, color = colour[0],line_width = 4, legend_label="US", alpha = 0.5)
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


third = p.line(x='year',y= 'pc',source=eu_kyoto, color = colour[3],line_width = 4, legend_label="EU", alpha = 0.5)
p.add_tools(HoverTool(renderers=[third], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

fourth = p.line(x='year',y= 'pc',source=china_kyoto, color = colour[2],line_width = 4, legend_label="China", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


fifth = p.line(x='year',y= 'pc',source=india_kyoto, color = colour[1],line_width = 4, legend_label="India", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fifth], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:The PRIMAP-hist national historical'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'emissions time series and the World Bank'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/nigeria_per_capita.html'

In [740]:
# visualisation of Russia  tonnes co2 emission vs world average
#data source: https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=ind&entity=kyotoghgar4
output_file('russia_per_capita.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Annual greenhouse gas emissions per capita (tonnes CO2e)', title = 'Russia\'s per capita emissions are over double the world average', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019), y_range=(0,45))

p.add_layout(Title(text="Per capita emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')


#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


ru = p.line(x='year',y= 'pc',source=russia_kyoto, color = colour[4],line_width = 7, legend_label="Russia")
p.add_tools(HoverTool(renderers=[ru], tooltips=[('Country', 'Russia'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


second = p.line(x='year',y= 'pc',source=world_kyoto, color = colour[7],line_width = 4, line_dash = 'dashed', legend_label="World", alpha = 0.5)
p.add_tools(HoverTool(renderers=[second], tooltips=[('Region', 'World'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

first = p.line(x='year',y= 'pc',source=us_kyoto, color = colour[0],line_width = 4, legend_label="US", alpha = 0.5)
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


third = p.line(x='year',y= 'pc',source=eu_kyoto, color = colour[3],line_width = 4, legend_label="EU", alpha = 0.5)
p.add_tools(HoverTool(renderers=[third], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

fourth = p.line(x='year',y= 'pc',source=china_kyoto, color = colour[2],line_width = 4, legend_label="China", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


fifth = p.line(x='year',y= 'pc',source=india_kyoto, color = colour[1],line_width = 4, legend_label="India", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fifth], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:The PRIMAP-hist national historical'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'emissions time series and the World Bank'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/russia_per_capita.html'

In [759]:
# visualisation of morocco  tonnes co2 emission vs world average
#data source: https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=ind&entity=kyotoghgar4
output_file('mo_per_capita.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Annual greenhouse gas emissions per capita (tonnes)', title = 'Morocco\'s per capita emissions are less than half of the world average', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019), y_range=(0,45))

p.add_layout(Title(text="Per capita emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')


#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


mo = p.line(x='year',y= 'pc',source=mor_kyoto, color = colour[4],line_width = 7, legend_label="Morocco")
p.add_tools(HoverTool(renderers=[mo], tooltips=[('Country', 'Morocco'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


second = p.line(x='year',y= 'pc',source=world_kyoto, color = colour[7],line_width = 4, line_dash = 'dashed', legend_label="World", alpha = 0.5)
p.add_tools(HoverTool(renderers=[second], tooltips=[('Region', 'World'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

first = p.line(x='year',y= 'pc',source=us_kyoto, color = colour[0],line_width = 4, legend_label="US", alpha = 0.5)
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


third = p.line(x='year',y= 'pc',source=eu_kyoto, color = colour[3],line_width = 4, legend_label="EU", alpha = 0.5)
p.add_tools(HoverTool(renderers=[third], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

fourth = p.line(x='year',y= 'pc',source=china_kyoto, color = colour[2],line_width = 4, legend_label="China", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


fifth = p.line(x='year',y= 'pc',source=india_kyoto, color = colour[1],line_width = 4, legend_label="India", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fifth], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:The PRIMAP-hist national historical'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'emissions time series and the World Bank'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/mo_per_capita.html'

# Visualisation total ghg

In [520]:
"""
#make total to gt
us_kyoto['total'] = us_kyoto.total/1000000000
india_kyoto['total'] = india_kyoto.total/1000000000
china_kyoto['total'] = china_kyoto.total/1000000000
eu_kyoto['total'] = eu_kyoto.total/1000000000
world_kyoto['total'] = world_kyoto.total/1000000000

india_kyoto.head()
"""

"\n#make total to gt\nus_kyoto['total'] = us_kyoto.total/1000000000\nindia_kyoto['total'] = india_kyoto.total/1000000000\nchina_kyoto['total'] = china_kyoto.total/1000000000\neu_kyoto['total'] = eu_kyoto.total/1000000000\nworld_kyoto['total'] = world_kyoto.total/1000000000\n\nindia_kyoto.head()\n"

In [521]:
"""
# visualisation of US total ghg emission vs world
#data source: pik potsdam
output_file('us_total.html')


#create figure
p = figure(x_axis_label='Year', y_axis_label='Total greenhouse gas emissions (billions of tonnes CO2e)', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019),y_range = (0,50))

#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


first = p.line(x='year',y= 'total_',source=us_kyoto, color = colour[0],line_width = 7, legend_label="US")
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

third = p.line(x='year',y= 'total_',source=india_kyoto, color = colour[1],line_width = 4, alpha = 0.7, legend_label="India")
p.add_tools(HoverTool(renderers=[third], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

fourth = p.line(x='year',y= 'total_',source=china_kyoto, color = colour[2],line_width = 4,alpha = 0.7, legend_label="China")
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

eu = p.line(x='year', y= 'total_',source=eu_kyoto, color = colour[3], line_width = 4, alpha = 0.7,legend_label="EU")
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))

second = p.varea(x='year',y1 = 0, y2= 'total_',source=world_kyoto, color = colour[7], legend_label="World", alpha = 0.2, level ='underlay')
line =p.line(x = 'year', y='total_', source = world_kyoto, color = colour[7], alpha = 0.1, level = 'underlay')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))


p.yaxis[0].formatter = NumeralTickFormatter(format="0")

p.legend.location = 'top_left'
#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'The PRIMAP-hist national historical emissions time series'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)
"""

'\n# visualisation of US total ghg emission vs world\n#data source: pik potsdam\noutput_file(\'us_total.html\')\n\n\n#create figure\np = figure(x_axis_label=\'Year\', y_axis_label=\'Total greenhouse gas emissions (billions of tonnes CO2e)\', \n            sizing_mode=\'stretch_both\', toolbar_location=None,x_range = (1960, 2019),y_range = (0,50))\n\n#Disable scientific notation on axes\np.left[0].formatter.use_scientific = False\np.below[0].formatter.use_scientific = False\n\n\nfirst = p.line(x=\'year\',y= \'total_\',source=us_kyoto, color = colour[0],line_width = 7, legend_label="US")\np.add_tools(HoverTool(renderers=[first], tooltips=[(\'Country\', \'US\'),(\'Year\',"@year"),(\'Emissions\',"@total_{0.0} Gt")],mode=\'mouse\', toggleable=False))\n\nthird = p.line(x=\'year\',y= \'total_\',source=india_kyoto, color = colour[1],line_width = 4, alpha = 0.7, legend_label="India")\np.add_tools(HoverTool(renderers=[third], tooltips=[(\'Country\', \'India\'),(\'Year\',"@year"),(\'Emissions\',"@total_{0.0} Gt")],mode=\'mouse\', toggleable=False))\n\nfourth = p.line(x=\'year\',y= \'total_\',source=china_kyoto, color = colour[2],line_width = 4,alpha = 0.7, legend_label="China")\np.add_tools(HoverTool(renderers=[fourth], tooltips=[(\'Country\', \'China\'),(\'Year\',"@year"),(\'Emissions\',"@total_{0.0} Gt")],mode=\'mouse\', toggleable=False))\n\neu = p.line(x=\'year\', y= \'total_\',source=eu_kyoto, color = colour[3], line_width = 4, alpha = 0.7,legend_label="EU")\np.add_tools(HoverTool(renderers=[eu], tooltips=[(\'Region\', \'EU\'),(\'Year\',"@year"),(\'Emissions\',"@total_{0.0} Gt")],mode=\'mouse\',toggleable=False))\n\nsecond = p.varea(x=\'year\',y1 = 0, y2= \'total_\',source=world_kyoto, color = colour[7], legend_label="World", alpha = 0.2, level =\'underlay\')\nline =p.line(x = \'year\', y=\'total_\', source = world_kyoto, color = colour[7], alpha = 0.1, level = \'underlay\')\np.add_tools(HoverTool(renderers=[line], tooltips=[(\'Year\',"@year"),(\'Emissions\',"@total_{0.0} Gt")],mode=\'mouse\',toggleable=False))\n\n\np.yaxis[0].formatter = NumeralTickFormatter(format="0")\n\np.legend.location = \'top_left\'\n#add data sources below charts\nlabel_opts = dict(x = 0, y = 0, x_units = \'screen\', y_units =\'screen\')\nmsg = \'Data source:\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np.add_layout(caption1, \'below\')\nmsg = \'The PRIMAP-hist national historical emissions time series\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'7pt\', text_font_style = \'italic\')\np.add_layout(caption1, \'below\')\np.toolbar.active_drag = None\np.xaxis.major_label_orientation = 120\n\nshow(p)\nsave(p)\n'

In [522]:
# visualisation of china total ghg emission vs world
#data source pik potsdam
output_file('china_total.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Total greenhouse gas emissions (billions of tonnes CO2e)', title = 'China overtook the US in 2005 to become the world\'s biggest emitter',
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019),y_range = (0,50))

p.add_layout(Title(text="Total greenhouse gas emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')

#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


fourth = p.line(x='year',y= 'total_',source=china_kyoto, color = colour[2],line_width = 7, legend_label="China")
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country',"China"),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

first = p.line(x='year',y= 'total_',source=us_kyoto, color = colour[0],line_width = 4, alpha = 0.7, legend_label="US")
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country',"US"),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

third = p.line(x='year',y= 'total_',source=india_kyoto, color = colour[1],line_width = 4, alpha = 0.7, legend_label="India")
p.add_tools(HoverTool(renderers=[third], tooltips=[('Country',"India"),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

eu = p.line(x='year', y= 'total_',source=eu_kyoto, color = colour[3], line_width = 4, alpha = 0.7, legend_label="EU")
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region',"EU"),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))

second = p.varea(x='year',y1 = 0, y2= 'total_',source=world_kyoto, color = colour[7], legend_label="World", alpha = 0.2, level ='underlay')
line =p.line(x = 'year', y='total_', source = world_kyoto, color = colour[7], alpha = 0.1)
p.add_tools(HoverTool(renderers=[line], tooltips=[('Region',"World"),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))


p.yaxis[0].formatter = NumeralTickFormatter(format="0")

p.legend.location = 'top_left'

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'The PRIMAP-hist national historical emissions time series'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None
show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/china_total.html'

In [523]:
# visualisation of netherlands total ghg emission vs world
output_file('nl_total.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Total greenhouse gas emissions (billions of tonnes CO2e)', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019),y_range = (0,50))

#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


nl = p.line(x='year',y= 'total_',source=nl_kyoto, color = colour[4],line_width = 7, legend_label="Netherlands")
p.add_tools(HoverTool(renderers=[nl], tooltips=[('Country', 'Netherlands'),('Year',"@year"),('Emissions',"@mega{0.0} Mt")],mode='mouse', toggleable=False))

fourth = p.line(x='year',y= 'total_',source=china_kyoto, color = colour[2],line_width = 4, alpha = 0.7, legend_label="China")
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

first = p.line(x='year',y= 'total_',source=us_kyoto, color = colour[0],line_width = 4, alpha = 0.7, legend_label="US")
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

third = p.line(x='year',y= 'total_',source=india_kyoto, color = colour[1],line_width = 4, alpha = 0.7, legend_label="India")
p.add_tools(HoverTool(renderers=[third], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

eu = p.line(x='year', y= 'total_',source=eu_kyoto, color = colour[3], line_width = 4, alpha = 0.7, legend_label="EU")
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))

second = p.varea(x='year',y1 = 0, y2= 'total_',source=world_kyoto, color = colour[7], legend_label="World", alpha = 0.2, level ='underlay')
line =p.line(x = 'year', y='total_', source = world_kyoto, color = colour[7], alpha = 0.1)
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))


p.yaxis[0].formatter = NumeralTickFormatter(format="0")

p.legend.location = 'top_left'

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'The PRIMAP-hist national historical emissions time series'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None
show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/nl_total.html'

In [741]:
# visualisation of Russia total ghg emission vs world
#data source: pik potsdam
output_file('russia_total.html')


#create figure
p = figure(x_axis_label='Year', y_axis_label='Total greenhouse gas emissions (billions of tonnes CO2e)', title = 'Russia is the world\'s fourth biggest emitter after China, the US and India',
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019),y_range = (0,50))

p.add_layout(Title(text="Total greenhouse gas emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')


#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False

ru = p.line(x='year',y= 'total_',source=russia_kyoto, color = colour[4],line_width = 7, legend_label="Russia")
p.add_tools(HoverTool(renderers=[ru], tooltips=[('Country', 'Russia'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

first = p.line(x='year',y= 'total_',source=us_kyoto, color = colour[0],line_width = 4, alpha = 0.7, legend_label="US")
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

third = p.line(x='year',y= 'total_',source=india_kyoto, color = colour[1],line_width = 4, alpha = 0.7, legend_label="India")
p.add_tools(HoverTool(renderers=[third], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

fourth = p.line(x='year',y= 'total_',source=china_kyoto, color = colour[2],line_width = 4,alpha = 0.7, legend_label="China")
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

eu = p.line(x='year', y= 'total_',source=eu_kyoto, color = colour[3], line_width = 4, alpha = 0.7,legend_label="EU")
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))

second = p.varea(x='year',y1 = 0, y2= 'total_',source=world_kyoto, color = colour[7], legend_label="World", alpha = 0.2, level ='underlay')
line =p.line(x = 'year', y='total_', source = world_kyoto, color = colour[7], alpha = 0.1, level = 'underlay')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))


p.yaxis[0].formatter = NumeralTickFormatter(format="0")

p.legend.location = 'top_left'
#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'The PRIMAP-hist national historical emissions time series'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/russia_total.html'

In [525]:
# visualisation of Russia total ghg emission vs world
#data source: pik potsdam
output_file('brazil_total.html')


#create figure
p = figure(x_axis_label='Year', y_axis_label='Total greenhouse gas emissions (billions of tonnes CO2e)', title = 'Brazil\'s CO2 emissions have almost doubled in the past 30 years',
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019),y_range = (0,50))

p.add_layout(Title(text="Total greenhouse gas emissions in different countries/regions (excluding land use)", text_font_style="italic", text_font_size = '10px',), 'above')


#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False

br = p.line(x='year',y= 'total_',source=brazil_kyoto, color = colour[4],line_width = 7, legend_label="Brazil")
p.add_tools(HoverTool(renderers=[br], tooltips=[('Country', 'Brazil'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

first = p.line(x='year',y= 'total_',source=us_kyoto, color = colour[0],line_width = 4, alpha = 0.7, legend_label="US")
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

third = p.line(x='year',y= 'total_',source=india_kyoto, color = colour[1],line_width = 4, alpha = 0.7, legend_label="India")
p.add_tools(HoverTool(renderers=[third], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

fourth = p.line(x='year',y= 'total_',source=china_kyoto, color = colour[2],line_width = 4,alpha = 0.7, legend_label="China")
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

eu = p.line(x='year', y= 'total_',source=eu_kyoto, color = colour[3], line_width = 4, alpha = 0.7,legend_label="EU")
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))

second = p.varea(x='year',y1 = 0, y2= 'total_',source=world_kyoto, color = colour[7], legend_label="World", alpha = 0.2, level ='underlay')
line =p.line(x = 'year', y='total_', source = world_kyoto, color = colour[7], alpha = 0.1, level = 'underlay')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))


p.yaxis[0].formatter = NumeralTickFormatter(format="0")

p.legend.location = 'top_left'
#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'The PRIMAP-hist national historical emissions time series'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/brazil_total.html'

In [664]:
# visualisation of Nigeria total ghg emission vs world
#data source: pik potsdam
output_file('nigeria_total.html')


#create figure
p = figure(x_axis_label='Year', y_axis_label='Total greenhouse gas emissions (billions of tonnes CO2e)', title = 'Nigeria\'s emissions are currently a fraction of the biggest emitters but are growing fast',
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019),y_range = (0,50))

p.add_layout(Title(text="Total greenhouse gas emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')


#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False

ni = p.line(x='year',y= 'total_',source=nigeria_kyoto, color = colour[4],line_width = 7, legend_label="Nigeria")
p.add_tools(HoverTool(renderers=[ni], tooltips=[('Country', 'Nigeria'),('Year',"@year"),('Emissions',"@mega{0.0} Mt")],mode='mouse', toggleable=False))

first = p.line(x='year',y= 'total_',source=us_kyoto, color = colour[0],line_width = 4, alpha = 0.7, legend_label="US")
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

third = p.line(x='year',y= 'total_',source=india_kyoto, color = colour[1],line_width = 4, alpha = 0.7, legend_label="India")
p.add_tools(HoverTool(renderers=[third], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

fourth = p.line(x='year',y= 'total_',source=china_kyoto, color = colour[2],line_width = 4,alpha = 0.7, legend_label="China")
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

eu = p.line(x='year', y= 'total_',source=eu_kyoto, color = colour[3], line_width = 4, alpha = 0.7,legend_label="EU")
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))

second = p.varea(x='year',y1 = 0, y2= 'total_',source=world_kyoto, color = colour[7], legend_label="World", alpha = 0.2, level ='underlay')
line =p.line(x = 'year', y='total_', source = world_kyoto, color = colour[7], alpha = 0.1, level = 'underlay')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))


p.yaxis[0].formatter = NumeralTickFormatter(format="0")

p.legend.location = 'top_left'
#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'The PRIMAP-hist national historical emissions time series'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/nigeria_total.html'

In [758]:
# visualisation of Morocco total ghg emission vs world
#data source: pik potsdam
output_file('morocco_total.html')


#create figure
p = figure(x_axis_label='Year', y_axis_label='Total greenhouse gas emissions (billions of tonnes CO2e)', title = '...',
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019),y_range = (0,50))

p.add_layout(Title(text="Total greenhouse gas emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')


#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False

mo = p.line(x='year',y= 'total_',source=mor_kyoto, color = colour[4],line_width = 7, legend_label="Morocco")
p.add_tools(HoverTool(renderers=[mo], tooltips=[('Country', 'Morocco'),('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse', toggleable=False))

first = p.line(x='year',y= 'total_',source=us_kyoto, color = colour[0],line_width = 4, alpha = 0.7, legend_label="US")
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

third = p.line(x='year',y= 'total_',source=india_kyoto, color = colour[1],line_width = 4, alpha = 0.7, legend_label="India")
p.add_tools(HoverTool(renderers=[third], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

fourth = p.line(x='year',y= 'total_',source=china_kyoto, color = colour[2],line_width = 4,alpha = 0.7, legend_label="China")
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse', toggleable=False))

eu = p.line(x='year', y= 'total_',source=eu_kyoto, color = colour[3], line_width = 4, alpha = 0.7,legend_label="EU")
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))

second = p.varea(x='year',y1 = 0, y2= 'total_',source=world_kyoto, color = colour[7], legend_label="World", alpha = 0.2, level ='underlay')
line =p.line(x = 'year', y='total_', source = world_kyoto, color = colour[7], alpha = 0.1, level = 'underlay')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year',"@year"),('Emissions',"@total_{0.0} Gt")],mode='mouse',toggleable=False))


p.yaxis[0].formatter = NumeralTickFormatter(format="0")

p.legend.location = 'top_left'
#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'The PRIMAP-hist national historical emissions time series'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/morocco_total.html'

# Projections

In [528]:
us_proj.head()

  index   paris  minimum  maximum     avg
0  2020  6.5255    5.956    5.960  5.9580
1  2021  6.1625    6.275    6.278  6.2765
2  2022  5.7995    6.366    6.397  6.3815
3  2023  5.4365    6.310    6.333  6.3215
4  2024  5.0735    6.208    6.266  6.2370

In [529]:
china_proj.head()

  index    paris  minimum  maximum      avg
0  2020  14.0171   13.341   13.341  13.3410
1  2021  13.3459   13.633   13.633  13.6330
2  2022  12.6747   13.826   13.826  13.8260
3  2023  12.0035   13.819   14.060  13.9395
4  2024  11.3323   13.854   14.146  14.0000

In [530]:
"""
# visualisation of projected metric tonnes co2 emission US
#https://climateactiontracker.org/countries/usa/
output_file('us_projection.html')
source = ColumnDataSource(us_proj)

p = figure(x_axis_label='Year', y_axis_label='US projected emissions (billions of tonnes CO2)', x_range = (2019.9,2030.1), y_range = (0,7),
            sizing_mode='stretch_both', toolbar_location=None)

proj = p.varea(x='index',
        y1='minimum',
        y2='maximum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Projected CO2 emissions')


p.legend.location = 'bottom_left'

#add average line
line = p.line(x ='index', y = 'avg', source = source, color= 'black', line_width = 1)
p.scatter(x='index', y ='avg', source = source, size = 3, fill_color = 'black', line_color = 'black')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Average projection',"@avg{0.0} Gt")],mode='mouse'))

#add paris scatter
paris = p.scatter(x = 'index', y = 'paris', source = source, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = '1.5C compatible pathway*')
p.add_tools(HoverTool(renderers=[paris], tooltips=[('1.5C compatible*',"@paris{0.0} Gt")],mode='mouse'))

un = p.scatter(x = 2030, y=[3.715, 4.219], size = 10, legend_label ='UN climate pledge')

# add a patch renderer with an alpha and line width
p.patch([2030, 2030], [3.715, 4.219], alpha=0.5, line_width=5)
p.add_tools(HoverTool(renderers = [un], tooltips =[('Upper', '4.2 Gt'), ('Lower', '3,7 Gt')]))


p.segment('index', 'paris', 'index', 'avg', source = source, line_width=2, line_color='black', alpha = 0.3, line_dash = [1,5] )

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Climate Action Tracker, September 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '* Using a global least-cost-solution model'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

show(p)
save(p)
"""

'\n# visualisation of projected metric tonnes co2 emission US\n#https://climateactiontracker.org/countries/usa/\noutput_file(\'us_projection.html\')\nsource = ColumnDataSource(us_proj)\n\np = figure(x_axis_label=\'Year\', y_axis_label=\'US projected emissions (billions of tonnes CO2)\', x_range = (2019.9,2030.1), y_range = (0,7),\n            sizing_mode=\'stretch_both\', toolbar_location=None)\n\nproj = p.varea(x=\'index\',\n        y1=\'minimum\',\n        y2=\'maximum\', source = source, color = colour[3], alpha = 0.7, legend_label = \'Projected CO2 emissions\')\n\n\np.legend.location = \'bottom_left\'\n\n#add average line\nline = p.line(x =\'index\', y = \'avg\', source = source, color= \'black\', line_width = 1)\np.scatter(x=\'index\', y =\'avg\', source = source, size = 3, fill_color = \'black\', line_color = \'black\')\np.add_tools(HoverTool(renderers=[line], tooltips=[(\'Year\', \'@index\'),(\'Average projection\',"@avg{0.0} Gt")],mode=\'mouse\'))\n\n#add paris scatter\nparis = p.scatter(x = \'index\', y = \'paris\', source = source, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = \'1.5C compatible pathway*\')\np.add_tools(HoverTool(renderers=[paris], tooltips=[(\'1.5C compatible*\',"@paris{0.0} Gt")],mode=\'mouse\'))\n\nun = p.scatter(x = 2030, y=[3.715, 4.219], size = 10, legend_label =\'UN climate pledge\')\n\n# add a patch renderer with an alpha and line width\np.patch([2030, 2030], [3.715, 4.219], alpha=0.5, line_width=5)\np.add_tools(HoverTool(renderers = [un], tooltips =[(\'Upper\', \'4.2 Gt\'), (\'Lower\', \'3,7 Gt\')]))\n\n\np.segment(\'index\', \'paris\', \'index\', \'avg\', source = source, line_width=2, line_color=\'black\', alpha = 0.3, line_dash = [1,5] )\n\n#add data sources below charts\nlabel_opts = dict(x = 0, y = 0, x_units = \'screen\', y_units =\'screen\')\nmsg = \'Data source: Climate Action Tracker, September 2021\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np.add_layout(caption1, \'below\')\nmsg = \'* Using a global least-cost-solution model\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np.add_layout(caption1, \'below\')\np.yaxis[0].formatter = NumeralTickFormatter(format="0,0")\n\np.xaxis.major_label_orientation = 120\np.toolbar.active_drag = None\n\nshow(p)\nsave(p)\n'

In [531]:
# visualisation of projected metric tonnes co2 emission china
#data https://climateactiontracker.org/countries/china/
output_file('china_projection.html')
source = ColumnDataSource(china_proj)

p = figure(x_axis_label='Year', y_axis_label='China projected emissions (billions of tonnes CO2)', title = 'China has pledged to peak its own CO2 emissions before 2030', x_range = (2019.9,2030.1), y_range = (0,15),
            sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Projected CO2 emissions in China based on current policies", text_font_style="italic", text_font_size = '10px',), 'above')



proj = p.varea(x='index',
        y1='minimum',
        y2='maximum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Projected CO2 emissions')

p.legend.location = 'bottom_left'


#add average line
line = p.line(x ='index', y = 'avg', source = source, color= 'black', line_width = 1)
p.scatter(x='index', y ='avg', source = source, size = 3, fill_color = 'black', line_color = 'black')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Average projection',"@avg{0.0} Gt")],mode='mouse'))

#add paris scatter
paris = p.scatter(x = 'index', y = 'paris', source = source, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = '1.5C compatible pathway*')
p.add_tools(HoverTool(renderers=[paris], tooltips=[('1.5C Compatible*',"@paris{0.0} Gt")],mode='mouse'))

p.segment('index', 'paris', 'index', 'avg', source = source, line_width=2, line_color='black', alpha = 0.3, line_dash = [1,5] )

un = p.scatter(x = 2030, y=[13.205, 14.045], size = 10, legend_label ='UN climate pledge')

# add a patch renderer with an alpha and line width
p.patch([2030, 2030], [13.205, 14.045], line_width=5, alpha = 0.5)
p.add_tools(HoverTool(renderers = [un], tooltips =[('Upper', '13.2 Gt'), ('Lower', '14.0 Gt')]))

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Climate Action Tracker, September 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '* Using a global least-cost-solution model'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None
show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/china_projection.html'

In [532]:
# visualisation of projected metric tonnes co2 emission EU
#data https://climateactiontracker.org/countries/eu/
output_file('EU_projection.html')
source = ColumnDataSource(eu_proj)

p = figure(x_axis_label='Year', y_axis_label='EU projected emissions (billions of tonnes CO2)', x_range = (2019.9,2030.1), y_range = (0,4),
            sizing_mode='stretch_both', toolbar_location=None)

proj = p.varea(x='index',
        y1='minimum',
        y2='maximum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Projected CO2 emissions')

p.legend.location = 'bottom_left'


#add average line
line = p.line(x ='index', y = 'avg', source = source, color= 'black', line_width = 1)
p.scatter(x='index', y ='avg', source = source, size = 3, fill_color = 'black', line_color = 'black')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Average projection',"@avg{0.0} Gt")],mode='mouse'))

#add paris scatter
paris = p.scatter(x = 'index', y = 'paris', source = source, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = '1.5C compatible pathway*')
p.add_tools(HoverTool(renderers=[paris], tooltips=[('1.5C Compatible',"@paris{0.0} Gt")],mode='mouse'))

p.segment('index', 'paris', 'index', 'avg', source = source, line_width=2, line_color='black', alpha = 0.3, line_dash = [1,5] )

un = p.scatter(x = 2030, y=[2.246], size = 10, legend_label ='UN climate pledge')

p.add_tools(HoverTool(renderers = [un], tooltips =[('Climate pledge', '2.2 Gt')]))



#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Climate Action Tracker, September 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '* Using a global least-cost-solution model'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/EU_projection.html'

In [743]:
# visualisation of projected metric tonnes co2 emission Russia
#data https://climateactiontracker.org/countries/eu/
output_file('russia_projection.html')
source = ColumnDataSource(russia_proj)

p = figure(x_axis_label='Year', y_axis_label='Russia projected emissions (billions of tonnes CO2)', x_range = (2019.9,2030.1), y_range = (0,3),
            title = '...', sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Projected CO2 emissions in Russia based on current policies", text_font_style="italic", text_font_size = '10px',), 'above')


proj = p.varea(x='index',
        y1='minimum',
        y2='maximum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Projected CO2 emissions')

p.legend.location = 'bottom_left'


#add average line
line = p.line(x ='index', y = 'avg', source = source, color= 'black', line_width = 1)
p.scatter(x='index', y ='avg', source = source, size = 3, fill_color = 'black', line_color = 'black')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Average projection',"@avg{0.0} Gt")],mode='mouse'))

#add paris scatter
paris = p.scatter(x = 'index', y = 'paris', source = source, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = '1.5C compatible pathway*')
p.add_tools(HoverTool(renderers=[paris], tooltips=[('1.5C Compatible',"@paris{0.0} Gt")],mode='mouse'))

p.segment('index', 'paris', 'index', 'avg', source = source, line_width=2, line_color='black', alpha = 0.3, line_dash = [1,5] )

un = p.scatter(x = 2030, y=[2.423], size = 10, legend_label ='UN climate pledge')

p.add_tools(HoverTool(renderers = [un], tooltips =[('Climate pledge', '2.4 Gt')]))



#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Climate Action Tracker, September 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '* Using a global least-cost-solution model'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
#p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/russia_projection.html'

In [534]:
brazil_proj

   index  minimum  maximum   paris     avg
0   2020      973      982  1070.5   977.5
1   2021      980      988  1036.1   984.0
2   2022      987      995  1001.8   991.0
3   2023      993     1001   967.4   997.0
4   2024      997     1006   933.0  1001.5
5   2025     1001     1010   898.7  1005.5
6   2026     1006     1015   861.8  1010.5
7   2027     1011     1021   824.9  1016.0
8   2028     1017     1027   788.0  1022.0
9   2029     1024     1033   751.1  1028.5
10  2030     1029     1039   714.2  1034.0

In [535]:
# visualisation of projected metric tonnes co2 emission Brazil
#data https://climateactiontracker.org/countries/eu/
output_file('brazil_projection.html')
source = ColumnDataSource(brazil_proj)

p = figure(x_axis_label='Year', y_axis_label='Brazil projected emissions (millions of tonnes CO2)', x_range = (2019.9,2030.1), y_range = (0,1400),
            title = '...', sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Projected CO2 emissions in Brazil based on current policies (excluding land use)", text_font_style="italic", text_font_size = '10px',), 'above')



proj = p.varea(x='index',
        y1='minimum',
        y2='maximum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Projected CO2 emissions')

p.legend.location = 'bottom_left'


#add average line
line = p.line(x ='index', y = 'avg', source = source, color= 'black', line_width = 1)
p.scatter(x='index', y ='avg', source = source, size = 3, fill_color = 'black', line_color = 'black')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Average projection',"@avg{0.0} Mt")],mode='mouse'))

#add paris scatter
paris = p.scatter(x = 'index', y = 'paris', source = source, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = '1.5C compatible pathway*')
p.add_tools(HoverTool(renderers=[paris], tooltips=[('1.5C Compatible',"@paris{0.0} Mt")],mode='mouse'))

p.segment('index', 'paris', 'index', 'avg', source = source, line_width=2, line_color='black', alpha = 0.3, line_dash = [1,5] )

un = p.scatter(x = 2030, y=[1307], size = 10, legend_label ='UN climate pledge')

p.add_tools(HoverTool(renderers = [un], tooltips =[('Climate pledge', '1307 Mt')]))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Climate Action Tracker, September 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '* Using a global least-cost-solution model'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/brazil_projection.html'

In [536]:
brazil_lul

   index   paris  minimum  maximum     avg  history  lulucf
0   2000  0.0000    0.000    0.000  0.0000    0.740   1.301
1   2001  0.0000    0.000    0.000  0.0000    0.758   1.299
2   2002  0.0000    0.000    0.000  0.0000    0.775   1.518
3   2003  0.0000    0.000    0.000  0.0000    0.792   2.480
4   2004  0.0000    0.000    0.000  0.0000    0.828   2.679
5   2005  0.0000    0.000    0.000  0.0000    0.847   1.947
6   2006  0.0000    0.000    0.000  0.0000    0.855   1.527
7   2007  0.0000    0.000    0.000  0.0000    0.861   1.312
8   2008  0.0000    0.000    0.000  0.0000    0.890   1.417
9   2009  0.0000    0.000    0.000  0.0000    0.880   0.459
10  2010  0.0000    0.000    0.000  0.0000    0.943   0.388
11  2011  0.0000    0.000    0.000  0.0000    0.980   0.323
12  2012  0.0000    0.000    0.000  0.0000    1.011   0.290
13  2013  0.0000    0.000    0.000  0.0000    1.050   0.431
14  2014  0.0000    0.000    0.000  0.0000    1.080   0.274
15  2015  0.0000    0.000    0.000  0.0000    1.056   0.373
16  2016  0.0000    0.000    0.000  0.0000    1.028   0.395
17  2017  0.0000    0.000    0.000  0.0000    1.036   0.327
18  2018  0.0000    1.013    1.013  1.0130    1.013   0.353
19  2019  0.0000    1.019    1.020  1.0195    0.000   0.000
20  2020  1.0705    0.973    0.982  0.9775    0.000   0.000
21  2021  1.0361    0.980    0.988  0.9840    0.000   0.000
22  2022  1.0018    0.987    0.995  0.9910    0.000   0.000
23  2023  0.9674    0.993    1.001  0.9970    0.000   0.000
24  2024  0.9330    0.997    1.006  1.0015    0.000   0.000
25  2025  0.8987    1.001    1.010  1.0055    0.000   0.000
26  2026  0.8618    1.006    1.015  1.0105    0.000   0.000
27  2027  0.8249    1.011    1.021  1.0160    0.000   0.000
28  2028  0.7880    1.017    1.027  1.0220    0.000   0.000
29  2029  0.7511    1.024    1.033  1.0285    0.000   0.000
30  2030  0.7142    1.029    1.039  1.0340    0.000   0.000

In [537]:
# visualisation of projected metric tonnes co2 emission Brazil
#data https://climateactiontracker.org/countries/eu/
output_file('brazil_projection_lulucf.html')

p = figure(x_axis_label='Year', y_axis_label='Brazil historical emissions (billions of tonnes CO2)', x_range = (1999.9,2018.1), y_range = (0,3),
            title = 'Brazil\'s emissions differ a lot depending on if land use is included or not', sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="CO2 emissions 2000-2018 in Brazil with and without land use", text_font_style="italic", text_font_size = '10px',), 'above')


new = ColumnDataSource(brazil_lul[:-12])

#add history, without luls
line = p.line(x ='index', y = 'history', source = new, color= colour[9], line_width = 4, legend_label = 'Historical emissions (excluding land use)')
p.scatter(x='index', y ='history', source = new, size = 5, fill_color = colour[9], line_color = colour[9])
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Historical emissions (excluding land use)',"@history{0.00} Gt")],mode='mouse'))

#add history, with luls
line = p.line(x ='index', y = 'lulucf', source = new, color= colour[4], line_width = 4, legend_label = 'Historical emissions (including land use)')
p.scatter(x='index', y ='lulucf', source = new, size = 5, fill_color = colour[4], line_color = colour[4])
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Historical emissions (including land use)',"@history{0.00} Gt")],mode='mouse'))

"""
source = ColumnDataSource(brazil_lul)


proj = p.varea(x='index',
        y1='minimum',
        y2='maximum', source = source, color = colour[3], alpha = 0.7)

p.legend.location = 'bottom_left'


scatter_s = ColumnDataSource(brazil_lul[18:])
#add average line
line = p.line(x ='index', y = 'avg', source = scatter_s, color= 'black', line_width = 1, legend_label = 'Projected CO2 emissions (excluding land use)')


p.scatter(x='index', y ='avg', source = scatter_s, size = 3, fill_color = 'black', line_color = 'black')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Average projection',"@avg{0.00} Gt")],mode='mouse'))




#add paris scatter

scatter = ColumnDataSource(brazil_lul[20:])

paris = p.scatter(x = 'index', y = 'paris', source = scatter, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = '1.5C compatible pathway*')
p.add_tools(HoverTool(renderers=[paris], tooltips=[('1.5C Compatible',"@paris{0.00} Mt")],mode='mouse'))

p.segment('index', 'paris', 'index', 'avg', source = scatter, line_width=2, line_color='black', alpha = 0.3, line_dash = [1,5] )

un = p.scatter(x = 2030, y=[1.307], size = 10, legend_label ='UN climate pledge')

p.add_tools(HoverTool(renderers = [un], tooltips =[('Climate pledge', '1.3 Gt')]))
"""

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Climate Action Tracker, September 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '* Using a global least-cost-solution model'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
#p.add_layout(caption1, 'below')
#p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/brazil_projection_lulucf.html'

In [538]:
nigeria_proj

   index  minimum  maximum  paris    avg
0   2020      320      320  374.9  320.0
1   2021      323      330  364.5  326.5
2   2022      327      339  354.0  333.0
3   2023      330      349  343.6  339.5
4   2024      334      358  333.2  346.0
5   2025      338      368  322.8  353.0
6   2026      342      377  312.0  359.5
7   2027      346      387  301.2  366.5
8   2028      350      396  290.4  373.0
9   2029      354      406  279.6  380.0
10  2030      358      416  268.8  387.0

In [539]:
# visualisation of projected metric tonnes co2 emission Nigeria
#data https://climateactiontracker.org/countries/eu/
output_file('nigeria_projection.html')
source = ColumnDataSource(nigeria_proj)

p = figure(x_axis_label='Year', y_axis_label='Nigeria projected emissions (millions of tonnes CO2)', x_range = (2019.9,2030.1), y_range = (0,500),
            title = '...', sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Projected CO2 emissions in Nigeria based on current policies", text_font_style="italic", text_font_size = '10px',), 'above')



proj = p.varea(x='index',
        y1='minimum',
        y2='maximum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Projected CO2 emissions')

p.legend.location = 'bottom_left'


#add average line
line = p.line(x ='index', y = 'avg', source = source, color= 'black', line_width = 1)
p.scatter(x='index', y ='avg', source = source, size = 3, fill_color = 'black', line_color = 'black')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Average projection',"@avg{0.0} Mt")],mode='mouse'))

#add paris scatter
paris = p.scatter(x = 'index', y = 'paris', source = source, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = '1.5C compatible pathway*')
p.add_tools(HoverTool(renderers=[paris], tooltips=[('1.5C Compatible',"@paris{0.0} Mt")],mode='mouse'))

p.segment('index', 'paris', 'index', 'avg', source = source, line_width=2, line_color='black', alpha = 0.3, line_dash = [1,5] )

un = p.scatter(x = 2030, y=[213,276], size = 10, legend_label ='Unconditional climate pledge')
# add a patch renderer with an alpha and line width
p.patch([2030, 2030], [213,276], line_width=5, alpha = 0.5)

p.add_tools(HoverTool(renderers = [un], tooltips =[('Upper', '276 Mt'), ('Lower', '213')]))

un1 = p.scatter(x = 2030, y=[321,348], size = 10, color = colour[9],legend_label ='Conditional climate pledge')
# add a patch renderer with an alpha and line width
p.patch([2030, 2030], [321,348], color = colour[9], line_width=5, alpha = 0.5)

p.add_tools(HoverTool(renderers = [un1], tooltips =[('Upper', '348 Mt'), ('Lower', '321')]))



#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Climate Action Tracker, September 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '* Using a global least-cost-solution model'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/nigeria_projection.html'

In [760]:
# visualisation of projected metric tonnes co2 emission morocco
#data https://climateactiontracker.org/countries/eu/
output_file('morocco_projection.html')
source = ColumnDataSource(morocco_proj)

p = figure(x_axis_label='Year', y_axis_label='Morocco projected emissions (millions of tonnes CO2)', x_range = (2019.9,2030.1), y_range = (0,200),
            title = 'Morocco\'s conditional climate pledge is roughly in line with a 1.5C trajectory', sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Projected CO2 emissions in Morocco based on current policies", text_font_style="italic", text_font_size = '10px',), 'above')



proj = p.varea(x='index',
        y1='minimum',
        y2='maximum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Projected CO2 emissions')

p.legend.location = 'bottom_left'


#add average line
line = p.line(x ='index', y = 'avg', source = source, color= 'black', line_width = 1)
p.scatter(x='index', y ='avg', source = source, size = 3, fill_color = 'black', line_color = 'black')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Average projection',"@avg{0.0} Mt")],mode='mouse'))

#add paris scatter
paris = p.scatter(x = 'index', y = 'paris', source = source, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = '1.5C compatible pathway*')
p.add_tools(HoverTool(renderers=[paris], tooltips=[('1.5C Compatible',"@paris{0.0} Mt")],mode='mouse'))

p.segment('index', 'paris', 'index', 'avg', source = source, line_width=2, line_color='black', alpha = 0.3, line_dash = [1,5] )

un = p.scatter(x = 2030, y=[115], size = 10, legend_label ='Unconditional climate pledge')
p.add_tools(HoverTool(renderers = [un], tooltips =[('Unconditional', '115 Mt' )]))

un1 = p.scatter(x = 2030, y=[75], size = 10, color = colour[9],legend_label ='Conditional climate pledge')

p.add_tools(HoverTool(renderers = [un1], tooltips =[('Conditional', '75 Mt' )]))



#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Climate Action Tracker, September 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '* Using a global least-cost-solution model'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

p.toolbar.active_drag = None
p.xaxis.major_label_orientation = 120

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/morocco_projection.html'

# transport

In [541]:
#prepare first dataset - data from EPA, by sector

sector = pd.DataFrame()

sector['type'] = ['Transport', 'Electricity production', 'Industry', 'Agriculture', 'Commercial', 'Residential']
sector['emissions'] = [29, 25, 23,10, 7, 6]

#prepare second data set - data from EPA, by vehicle
vehicle = pd.DataFrame()
vehicle['type'] = ['Light-duty vehicles', 'Trucks', 'Aircraft', 'Other', 'Rail', 'Ships and boats']
vehicle['emissions'] = [58, 24, 10, 5, 2, 2]

#prepare third data set - data from iea

sales = pd.DataFrame()
sales['type'] = ['2010','  ','Conv. cars','   ', 'Conv. SUVs', '    ','Electric cars', '     ','Electric SUVs','      ','2020']
sales['number'] = [0,0,40500000,0,29600000,0,1900000,0,1100000,0,0]

#prepare fourth data set - data from iea
sales_suv = pd.DataFrame()
sales_suv['index'] = ['2010','  ','Conv. cars','   ', 'Conv. SUVs', '    ','Electric cars', '     ','Electric SUVs','      ','2020']
sales_suv['percentage'] = [15.5, 17.5, 19.6, 21.7, 24.1, 27.3, 31.2, 34.6, 37, 39, 40.5]
sales_suv['year'] = [i for i in range(2010,2021)]

In [542]:
"""
from bokeh.io import show
from bokeh.models import Panel, Tabs, LinearAxis, Range1d
from bokeh.plotting import figure

output_file('by_sector.html')

temp_colour= colour +('#000000','#000001')

#first bars
#data https://www.epa.gov/greenvehicles/fast-facts-transportation-greenhouse-gas-emissions

source = ColumnDataSource(data = dict(sector = list(sector.type), emissions = list(sector.emissions), color = colour[0:6]))

p1 = figure(x_range = sector.type, y_range = (0,40), sizing_mode='stretch_both', toolbar_location=None,
           tools="hover", tooltips=[('Sector', '@sector'),('Share',"@emissions%")], y_axis_label = 'Industry share of US total greenhouse gas emissions')

c = len(sector.type)

bars = p1.vbar(x='sector', bottom = 0, top='emissions', width=0.5, fill_color='color', line_color = 'color',source = source)

p1.yaxis[0].formatter = PrintfTickFormatter(format='%0.0f%%')

p1.xaxis.major_label_orientation = 120

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Environmental Protection Agency'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p1.add_layout(caption1, 'below')

show(p1)
save(p1)
"""

'\nfrom bokeh.io import show\nfrom bokeh.models import Panel, Tabs, LinearAxis, Range1d\nfrom bokeh.plotting import figure\n\noutput_file(\'by_sector.html\')\n\ntemp_colour= colour +(\'#000000\',\'#000001\')\n\n#first bars\n#data https://www.epa.gov/greenvehicles/fast-facts-transportation-greenhouse-gas-emissions\n\nsource = ColumnDataSource(data = dict(sector = list(sector.type), emissions = list(sector.emissions), color = colour[0:6]))\n\np1 = figure(x_range = sector.type, y_range = (0,40), sizing_mode=\'stretch_both\', toolbar_location=None,\n           tools="hover", tooltips=[(\'Sector\', \'@sector\'),(\'Share\',"@emissions%")], y_axis_label = \'Industry share of US total greenhouse gas emissions\')\n\nc = len(sector.type)\n\nbars = p1.vbar(x=\'sector\', bottom = 0, top=\'emissions\', width=0.5, fill_color=\'color\', line_color = \'color\',source = source)\n\np1.yaxis[0].formatter = PrintfTickFormatter(format=\'%0.0f%%\')\n\np1.xaxis.major_label_orientation = 120\n\n#add data sources below charts\nlabel_opts = dict(x = 0, y = 0, x_units = \'screen\', y_units =\'screen\')\nmsg = \'Data source: Environmental Protection Agency\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np1.add_layout(caption1, \'below\')\n\nshow(p1)\nsave(p1)\n'

In [543]:
"""
#second bars
# data https://www.epa.gov/greenvehicles/fast-facts-transportation-greenhouse-gas-emissions
output_file('by_vehicle.html')
source = ColumnDataSource(data = dict(vehicle = list(vehicle.type), emissions = list(vehicle.emissions), color = colour[0:6]))

p2 = figure(x_range = vehicle.type, y_range = (0,60), sizing_mode='stretch_both', toolbar_location=None,
           tools="hover", tooltips=[('Source', '@vehicle'),('Share',"@emissions%")], y_axis_label =' U.S. transport sector greenhouse gas emissions by source')

c = len(sector.type)

bars = p2.vbar(x='vehicle', bottom = 0, top='emissions', width=0.5, fill_color='color', line_color = 'color',source = source)

p2.yaxis[0].formatter = PrintfTickFormatter(format='%0.0f%%')
p2.xaxis.major_label_orientation = 120

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Environmental Protection Agency'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p2.add_layout(caption1, 'below')
p2.toolbar.active_drag = None

show(p2)
save(p2)
"""

'\n#second bars\n# data https://www.epa.gov/greenvehicles/fast-facts-transportation-greenhouse-gas-emissions\noutput_file(\'by_vehicle.html\')\nsource = ColumnDataSource(data = dict(vehicle = list(vehicle.type), emissions = list(vehicle.emissions), color = colour[0:6]))\n\np2 = figure(x_range = vehicle.type, y_range = (0,60), sizing_mode=\'stretch_both\', toolbar_location=None,\n           tools="hover", tooltips=[(\'Source\', \'@vehicle\'),(\'Share\',"@emissions%")], y_axis_label =\' U.S. transport sector greenhouse gas emissions by source\')\n\nc = len(sector.type)\n\nbars = p2.vbar(x=\'vehicle\', bottom = 0, top=\'emissions\', width=0.5, fill_color=\'color\', line_color = \'color\',source = source)\n\np2.yaxis[0].formatter = PrintfTickFormatter(format=\'%0.0f%%\')\np2.xaxis.major_label_orientation = 120\n\n#add data sources below charts\nlabel_opts = dict(x = 0, y = 0, x_units = \'screen\', y_units =\'screen\')\nmsg = \'Data source: Environmental Protection Agency\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np2.add_layout(caption1, \'below\')\np2.toolbar.active_drag = None\n\nshow(p2)\nsave(p2)\n'

In [544]:
#prepare third data set - data from iea

sales = pd.DataFrame()
sales['type'] = ['2010','2011','2012','2013', '2014', '2015','2016', '2017','2018','2019','Pickup trucks and SUVs', 'Passenger cars']
sales['number'] = [0,0,0,0,0,0,0,0,0,0,11.058337,3.519034]

#1.1,1.9] 'Electric SUVs','Other electric cars'

#prepare fourth data set - data from iea
sales_suv = pd.DataFrame()
sales_suv['index'] = ['2010','2011','2012','2013', '2014', '2015','2016', '2017','2018','2019','Pickup trucks and SUVs', 'Passenger cars']
sales_suv['percentage'] = [27,30,29,31,34,38,42,45,48,50, 'Nan','Nan']
#sales_suv['year'] = [i for i in range(2010,2021)]

In [545]:
"""
#third graphs
#data https://www.iea.org/commentaries/carbon-emissions-fell-across-all-sectors-in-2020-except-for-one-suvs
#percentages are calculated by hand

c = ['#000000','#000000','#000000','#000000','#000000',
     '#000000','#000000',
     '#000000','#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']
output_file('suv_sales.html')

source = ColumnDataSource(data = dict(cars = list(sales.type), number = list(sales.number), color = c[0:15]))

p3 = figure(x_range = sales.type, y_range = (0, 60), sizing_mode = 'stretch_both', y_axis_label='Percentage of US car sales', toolbar_location=None)

p3.extra_y_ranges = {"2020 sales": Range1d(start=0, end=15)}
p3.add_layout(LinearAxis(y_range_name="2020 sales", axis_label = 'Millions of cars sold in 2020'), 'right')
p3.yaxis[0].formatter = PrintfTickFormatter(format='%0.0f%%')
#Disable scientific notation on axes
p3.right[0].formatter.use_scientific = False


#set bars
bars = p3.vbar(x='cars', bottom = 0, top='number', width=0.9, fill_color = 'color', line_color = 'color', source = source, y_range_name='2020 sales')
p3.add_tools(HoverTool(renderers=[bars], tooltips=[('Cars sold in 2020',"@number{0.0}m")],mode='mouse',toggleable=False))

#p3.left[0].formatter.use_scientific = False
p3.yaxis[1].formatter = NumeralTickFormatter(format="0,0")

p3.xaxis.major_label_orientation = 120

source1 = ColumnDataSource(sales_suv)

line=p3.line(x ='index', y = 'percentage',source = source1, color= 'black', line_width = 3 )

p3.add_tools(HoverTool(renderers=[line], tooltips=[('SUV % of sales',"@percentage{0}%")],mode='mouse',toggleable=False))
p3.scatter(x = 'index', y ='percentage', source = source1, color = 'black', size = 5)


tempx = ['2019', 'Pickup trucks and SUVs']
tempy = [50, 40]

p3.line(x = tempx, y = tempy, color = 'grey', line_width = 2, line_dash = 'dashed', level = 'underlay')
p3.line(x = tempx, y = [50, 0], color = 'grey', line_width = 2, line_dash = 'dashed', level = 'underlay')

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: International Energy Agency, Marklines (2020)'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p3.add_layout(caption1, 'below')

p3.toolbar.active_drag = None


show(p3)
save(p3)
"""

'\n#third graphs\n#data https://www.iea.org/commentaries/carbon-emissions-fell-across-all-sectors-in-2020-except-for-one-suvs\n#percentages are calculated by hand\n\nc = [\'#000000\',\'#000000\',\'#000000\',\'#000000\',\'#000000\',\n     \'#000000\',\'#000000\',\n     \'#000000\',\'#1f77b4\', \'#ff7f0e\', \'#2ca02c\', \'#d62728\']\noutput_file(\'suv_sales.html\')\n\nsource = ColumnDataSource(data = dict(cars = list(sales.type), number = list(sales.number), color = c[0:15]))\n\np3 = figure(x_range = sales.type, y_range = (0, 60), sizing_mode = \'stretch_both\', y_axis_label=\'Percentage of US car sales\', toolbar_location=None)\n\np3.extra_y_ranges = {"2020 sales": Range1d(start=0, end=15)}\np3.add_layout(LinearAxis(y_range_name="2020 sales", axis_label = \'Millions of cars sold in 2020\'), \'right\')\np3.yaxis[0].formatter = PrintfTickFormatter(format=\'%0.0f%%\')\n#Disable scientific notation on axes\np3.right[0].formatter.use_scientific = False\n\n\n#set bars\nbars = p3.vbar(x=\'cars\', bottom = 0, top=\'number\', width=0.9, fill_color = \'color\', line_color = \'color\', source = source, y_range_name=\'2020 sales\')\np3.add_tools(HoverTool(renderers=[bars], tooltips=[(\'Cars sold in 2020\',"@number{0.0}m")],mode=\'mouse\',toggleable=False))\n\n#p3.left[0].formatter.use_scientific = False\np3.yaxis[1].formatter = NumeralTickFormatter(format="0,0")\n\np3.xaxis.major_label_orientation = 120\n\nsource1 = ColumnDataSource(sales_suv)\n\nline=p3.line(x =\'index\', y = \'percentage\',source = source1, color= \'black\', line_width = 3 )\n\np3.add_tools(HoverTool(renderers=[line], tooltips=[(\'SUV % of sales\',"@percentage{0}%")],mode=\'mouse\',toggleable=False))\np3.scatter(x = \'index\', y =\'percentage\', source = source1, color = \'black\', size = 5)\n\n\ntempx = [\'2019\', \'Pickup trucks and SUVs\']\ntempy = [50, 40]\n\np3.line(x = tempx, y = tempy, color = \'grey\', line_width = 2, line_dash = \'dashed\', level = \'underlay\')\np3.line(x = tempx, y = [50, 0], color = \'grey\', line_width = 2, line_dash = \'dashed\', level = \'underlay\')\n\n#add data sources below charts\nlabel_opts = dict(x = 0, y = 0, x_units = \'screen\', y_units =\'screen\')\nmsg = \'Data source: International Energy Agency, Marklines (2020)\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np3.add_layout(caption1, \'below\')\n\np3.toolbar.active_drag = None\n\n\nshow(p3)\nsave(p3)\n'

In [546]:
"""
#alternative line graph: US vs others
from bokeh.models import MultiLine

regions = ['US', 'World', 'China', 'Europe']
years = [i for i in range(2010, 2020)]
shares = [[27,17,14,10], [30,20,16,12], [29,21,19,14], [31,23,22,16], [34, 25,25,19], [38, 29,31,21],[42, 33, 37,24],
          [45,36,42,28],[48,39,42,33],[50,41,44,36]]

share = pd.DataFrame(shares, columns=regions)

hybrid = [2.4, 2.1, 3.1, 3.2, 2.8, 2.2, 2.0, 2.2, 2.0, 2.3]
plug_in_hybrid = [0.0, 0.1, 0.3, 0.3, 0.3, 0.3, 0.4, 0.5, 0.7, 0.5]
all_electric = [0.0, 0.1, 0.1, 0.3, 0.4, 0.4, 0.5, 0.6, 1.2, 1.4]


share['year'] = years
share['hybrid'] = hybrid
share['plug'] = plug_in_hybrid
share['all_elec'] = all_electric
share['electric_total'] = share['hybrid'] + share['plug'] + share['all_elec']

share
"""

"\n#alternative line graph: US vs others\nfrom bokeh.models import MultiLine\n\nregions = ['US', 'World', 'China', 'Europe']\nyears = [i for i in range(2010, 2020)]\nshares = [[27,17,14,10], [30,20,16,12], [29,21,19,14], [31,23,22,16], [34, 25,25,19], [38, 29,31,21],[42, 33, 37,24],\n          [45,36,42,28],[48,39,42,33],[50,41,44,36]]\n\nshare = pd.DataFrame(shares, columns=regions)\n\nhybrid = [2.4, 2.1, 3.1, 3.2, 2.8, 2.2, 2.0, 2.2, 2.0, 2.3]\nplug_in_hybrid = [0.0, 0.1, 0.3, 0.3, 0.3, 0.3, 0.4, 0.5, 0.7, 0.5]\nall_electric = [0.0, 0.1, 0.1, 0.3, 0.4, 0.4, 0.5, 0.6, 1.2, 1.4]\n\n\nshare['year'] = years\nshare['hybrid'] = hybrid\nshare['plug'] = plug_in_hybrid\nshare['all_elec'] = all_electric\nshare['electric_total'] = share['hybrid'] + share['plug'] + share['all_elec']\n\nshare\n"

In [547]:
"""
# visualisation of netherlands total ghg emission vs world
#data https://www.iea.org/data-and-statistics/charts/share-of-suvs-in-total-car-sales-in-key-markets-2010-2019
#https://tedb.ornl.gov/wp-content/uploads/2021/02/TEDB_Ed_39.pdf#page=182
from bokeh.models import LegendItem
output_file('suv_comparison.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Share SUV sales', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (2009.5, 2019.5),y_range = (0,60))


p.xaxis.ticker = list(range(2010, 2020))
p.yaxis[0].formatter = PrintfTickFormatter(format='%0.0f%%')

el = p.scatter(x = 'year', y = 'electric_total', source = share, color = colour[1], size = 10)
p.add_tools(HoverTool(renderers=[el], tooltips=[('Year',"@year"),('Share',"@electric_total{0.0}%")],mode='mouse', toggleable=False))


us = p.line(x='year',y= 'US',source=share, color = colour[0],line_width = 7, legend_label="US")
p.scatter(x = 'year', y ='US', source = share, color = colour[0], size = 10)
p.add_tools(HoverTool(renderers=[us], tooltips=[('Region', 'US'),('Year',"@year"),('Share',"@US{0}%")],mode='mouse', toggleable=False))

world = p.line(x='year',y= 'World',source=share, color = colour[7],line_width = 4, line_dash = 'dashed', alpha = 0.8,legend_label="World")
p.scatter(x='year',y= 'World',source=share, color = colour[7],size = 7)
p.add_tools(HoverTool(renderers=[world], tooltips=[('Region', 'World'),('Year',"@year"),('Share',"@World{0}%")],mode='mouse', toggleable=False))


china = p.line(x='year',y= 'China',source=share, color = colour[2],line_width = 4,alpha = 0.8, legend_label="China")
p.scatter(x='year',y= 'China',source=share, color = colour[2],size = 7)
p.add_tools(HoverTool(renderers=[china], tooltips=[('Region', 'China'),('Year',"@year"),('Share',"@China{0}%")],mode='mouse', toggleable=False))

eu = p.line(x='year',y= 'Europe',source=share, color = colour[3],line_width = 4, alpha = 0.8,legend_label="Europe")
p.scatter(x='year',y= 'Europe',source=share, color = colour[3],size = 7)
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'Europe'),('Year',"@year"),('Share',"@Europe{0}%")],mode='mouse', toggleable=False))

p.legend.location = 'top_left'

citation = Label(x=2010, y=5,
                 text='US share electric car sales (all types)', render_mode='css',
                 border_line_color=colour[1], border_line_alpha=1.0, border_line_width = 2,
                 background_fill_color='white', background_fill_alpha=1.0, text_font_size = '9pt' )
p.add_layout(citation)

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: International Energy Agency,'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'Transportation Energy Data Book, edition 39'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

p.toolbar.active_drag = None


save(p)

show(p)
"""

'\n# visualisation of netherlands total ghg emission vs world\n#data https://www.iea.org/data-and-statistics/charts/share-of-suvs-in-total-car-sales-in-key-markets-2010-2019\n#https://tedb.ornl.gov/wp-content/uploads/2021/02/TEDB_Ed_39.pdf#page=182\nfrom bokeh.models import LegendItem\noutput_file(\'suv_comparison.html\')\n\n#create figure\np = figure(x_axis_label=\'Year\', y_axis_label=\'Share SUV sales\', \n            sizing_mode=\'stretch_both\', toolbar_location=None,x_range = (2009.5, 2019.5),y_range = (0,60))\n\n\np.xaxis.ticker = list(range(2010, 2020))\np.yaxis[0].formatter = PrintfTickFormatter(format=\'%0.0f%%\')\n\nel = p.scatter(x = \'year\', y = \'electric_total\', source = share, color = colour[1], size = 10)\np.add_tools(HoverTool(renderers=[el], tooltips=[(\'Year\',"@year"),(\'Share\',"@electric_total{0.0}%")],mode=\'mouse\', toggleable=False))\n\n\nus = p.line(x=\'year\',y= \'US\',source=share, color = colour[0],line_width = 7, legend_label="US")\np.scatter(x = \'year\', y =\'US\', source = share, color = colour[0], size = 10)\np.add_tools(HoverTool(renderers=[us], tooltips=[(\'Region\', \'US\'),(\'Year\',"@year"),(\'Share\',"@US{0}%")],mode=\'mouse\', toggleable=False))\n\nworld = p.line(x=\'year\',y= \'World\',source=share, color = colour[7],line_width = 4, line_dash = \'dashed\', alpha = 0.8,legend_label="World")\np.scatter(x=\'year\',y= \'World\',source=share, color = colour[7],size = 7)\np.add_tools(HoverTool(renderers=[world], tooltips=[(\'Region\', \'World\'),(\'Year\',"@year"),(\'Share\',"@World{0}%")],mode=\'mouse\', toggleable=False))\n\n\nchina = p.line(x=\'year\',y= \'China\',source=share, color = colour[2],line_width = 4,alpha = 0.8, legend_label="China")\np.scatter(x=\'year\',y= \'China\',source=share, color = colour[2],size = 7)\np.add_tools(HoverTool(renderers=[china], tooltips=[(\'Region\', \'China\'),(\'Year\',"@year"),(\'Share\',"@China{0}%")],mode=\'mouse\', toggleable=False))\n\neu = p.line(x=\'year\',y= \'Europe\',source=share, color = colour[3],line_width = 4, alpha = 0.8,legend_label="Europe")\np.scatter(x=\'year\',y= \'Europe\',source=share, color = colour[3],size = 7)\np.add_tools(HoverTool(renderers=[eu], tooltips=[(\'Region\', \'Europe\'),(\'Year\',"@year"),(\'Share\',"@Europe{0}%")],mode=\'mouse\', toggleable=False))\n\np.legend.location = \'top_left\'\n\ncitation = Label(x=2010, y=5,\n                 text=\'US share electric car sales (all types)\', render_mode=\'css\',\n                 border_line_color=colour[1], border_line_alpha=1.0, border_line_width = 2,\n                 background_fill_color=\'white\', background_fill_alpha=1.0, text_font_size = \'9pt\' )\np.add_layout(citation)\n\n#add data sources below charts\nlabel_opts = dict(x = 0, y = 0, x_units = \'screen\', y_units =\'screen\')\nmsg = \'Data source: International Energy Agency,\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np.add_layout(caption1, \'below\')\nmsg = \'Transportation Energy Data Book, edition 39\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np.add_layout(caption1, \'below\')\n\np.toolbar.active_drag = None\n\n\nsave(p)\n\nshow(p)\n'

# Gas the Netherlans

In [548]:
share_gas = pd.read_csv('share-energy-source-sub.csv', sep = ';')
share_gas = share_gas[share_gas.Entity == 'Netherlands']
share_gas = share_gas.iloc[:,2:]
share_gas = share_gas.set_index('Year')
share_gas['Renewables'] = share_gas['Solar'] +share_gas['Hydro'] + share_gas['Wind'] +share_gas['Other renewables']
share_gas.head()

,Oil,Coal,Solar,Nuclear,Hydro,Wind,Gas,Other renewables,Renewables
Year,,,,,,,,,
1965,71.481,24.895,0.0,0.000,0.0,0.0,3.624,0.0,0.0
1966,72.371,21.176,0.0,0.000,0.0,0.0,6.453,0.0,0.0
1967,69.959,19.257,0.0,0.000,0.0,0.0,10.784,0.0,0.0
1968,67.461,16.315,0.0,0.015,0.0,0.0,16.209,0.0,0.0
1969,65.981,12.446,0.0,0.150,0.0,0.0,21.424,0.0,0.0

In [549]:
gas_cons = pd.read_csv('energy-consumption-by-source-and-region.csv', sep = ';')
gas_cons = gas_cons[gas_cons.Entity == 'Netherlands']
gas_cons = gas_cons.iloc[:,2:]
gas_cons = gas_cons.set_index('Year')
gas_cons['Renewables'] = gas_cons['Solar']+gas_cons['Hydro']+ gas_cons['Wind']+ gas_cons['Geo Biomass']+ gas_cons['Biofuels']
gas = gas_cons.iloc[:,1]
del gas_cons['Gas']
gas_cons.insert(loc=0, column='Gas', value=gas)
gas_cons

,Gas,Oil,Coal,Solar,Hydro,Nuclear,Wind,Geo Biomass,Biofuels,Renewables
Year,,,,,,,,,,
1965,15.000012,295.904775,103.055638,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
1966,28.611134,320.877691,93.888964,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
1967,50.555596,327.966957,90.277850,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
1968,85.000068,353.758402,85.555624,0.000000,0.000000,0.077778,0.000000,0.000000,0.000,0.000000
1969,125.277878,385.837689,72.777836,0.000000,0.000000,0.875001,0.000000,0.000000,0.000,0.000000
1970,176.389030,429.031668,53.333376,0.000000,0.000000,1.022223,0.000000,0.000000,0.000,0.000000
1971,230.555740,423.789564,40.277810,0.000000,0.000000,1.125001,0.000000,0.000000,0.000,0.000000
1972,300.000240,472.769077,34.444472,0.000000,0.000000,0.905556,0.000000,0.000000,0.000,0.000000
1973,333.611378,487.927048,35.000028,0.000000,0.000000,3.077780,0.000000,0.000000,0.000,0.000000
1974,355.000284,418.325784,33.333360,0.000000,0.000000,9.102785,0.000000,0.000000,0.000,0.000000
1975,370.278074,412.486027,28.055578,0.000000,0.000000,9.263896,0.000000,2.230557,0.000,2.230557
1976,384.444752,464.208806,35.000028,0.000000,0.000000,10.755564,0.000000,2.422224,0.000,2.422224
1977,385.833642,445.519789,36.666696,0.000000,0.000000,10.305564,0.000000,2.408335,0.000,2.408335
1978,386.666976,455.183803,41.944478,0.000000,0.000000,11.277787,0.000000,3.363892,0.000,3.363892
1979,385.000308,490.442204,40.000032,0.000000,0.000000,9.691674,0.000000,3.072225,0.000,3.072225
1980,351.944726,458.675831,46.388926,0.000000,0.000000,11.666676,0.000000,2.844447,0.000,2.844447
1981,335.000268,426.868285,51.388930,0.000000,0.000000,10.161119,0.000000,3.013891,0.000,3.013891
1982,320.000256,373.068004,59.444492,0.000000,0.000000,10.825009,0.000000,0.736112,0.000,0.736112
1983,342.222496,353.534779,61.388938,0.000000,0.000000,9.969452,0.000000,0.641667,0.000,0.641667
1984,363.611402,349.007160,74.166726,0.000000,0.000000,10.308342,0.000000,0.047222,0.000,0.047222
1985,383.333640,353.146158,73.888948,0.000000,0.008333,10.830564,0.000000,1.225001,0.000,1.233334
1986,382.222528,391.567121,76.111172,0.000000,0.008333,11.711120,0.002778,1.536112,0.000,1.547223
1987,394.444760,394.372383,80.277842,0.000000,0.002778,9.877786,0.005556,1.950002,0.000,1.958335
1988,356.666952,418.446310,96.111188,0.000000,0.005556,10.208341,0.044444,2.319446,0.000,2.369446
1989,365.833626,412.892695,95.277854,0.000000,0.102778,11.163898,0.063889,2.500002,0.000,2.666669
1990,368.055850,428.520150,101.666748,0.000000,0.236111,9.727786,0.155556,1.861113,0.000,2.252780
1991,410.694773,411.350087,93.611186,0.000000,0.288889,9.247230,0.244445,2.083335,0.000,2.616669
1992,399.916987,431.892190,93.333408,0.002778,0.333334,10.555564,0.408334,2.088891,0.000,2.833336
1993,411.305885,426.747386,94.166742,0.002778,0.255556,10.966675,0.483334,2.397224,0.000,3.138891
1994,397.222540,424.055767,100.277858,0.000028,0.277778,11.019453,0.661112,2.608335,0.000,3.547253
1995,408.028104,447.475166,103.611194,0.002778,0.244445,11.161120,0.880556,2.825002,0.000,3.952781
1996,452.194806,447.376894,100.000080,0.005556,0.222222,11.555565,1.213890,3.655558,0.000,5.097226
1997,423.694783,464.748786,97.222300,0.005556,0.255556,6.688894,1.319446,4.063892,0.000,5.644449
1998,418.389224,470.267181,99.166746,0.009722,0.311972,10.580817,1.777779,4.417451,0.000,6.516925
1999,408.778105,479.293934,86.944514,0.014639,0.250692,10.633934,1.791668,4.967610,0.000,7.024608
2000,409.916995,486.182865,90.277850,0.021417,0.395536,10.886698,2.302780,5.592210,0.000,8.311943
2001,418.194779,509.719018,96.111188,0.036042,0.323784,10.963273,2.276788,6.507567,0.000,9.144180
2002,413.972553,512.051278,96.666744,0.046723,0.300615,10.730683,2.593873,7.970133,0.000,10.911344
2003,416.833667,512.808803,100.000080,0.083747,0.196217,10.946453,3.590708,6.940403,0.000,10.811074
2004,426.778119,536.421891,98.611190,0.089710,0.259147,10.346235,5.053985,9.000549,0.000,14.403391
2005,414.555887,569.423363,94.166742,0.091991,0.236709,10.752659,5.559973,14.193718,0.000,20.082390
2006,398.083652,567.073030,89.722294,0.094150,0.281193,9.273665,7.307867,13.883344,0.477,22.043554
2007,388.055866,583.520613,97.777856,0.094860,0.284219,11.157090,9.129539,10.694820,3.854,24.057438
2008,403.889212,554.876944,92.500074,0.102657,0.263975,11.004840,11.240950,13.417585,3.368,28.393168
2009,413.583664,530.078245,87.222292,0.116597,0.255058,11.145327,12.024186,16.031957,4.408,32.835798
2010,467.583707,539.929899,87.777848,0.154992,0.271601,10.349063,10.411351,18.402921,2.735,31.975866
2011,409.278105,546.457395,86.583403,0.260038,0.147714,10.730676,13.216917,18.356799,3.820,35.801467
2012,392.833648,518.872030,95.138965,0.653607,0.268878,10.083352,12.831994,18.554755,3.963,36.272234
2013,391.111424,493.015402,95.194521,1.320829,0.292666,7.401302,14.406866,15.243687,3.786,35.050049
2014,344.722498,470.392431,105.305640,1.997150,0.284839,10.412015,14.753706,12.758108,4.432,34.225804
2015,340.805828,459.196389,128.083436,2.837153,0.235268,10.316481,19.099396,12.471736,3.806,38.449554
2016,351.528059,473.862474,118.694539,3.921632,0.251678,9.959287,20.547026,12.334013,3.053,40.107349
2017,361.666956,455.894406,106.388974,5.510869,0.151893,8.506202,26.422024,11.498382,4.749,48.332167
2018,353.639172,467.385170,95.500076,9.178747,0.179812,8.735546,26.254694,11.321487,7.279,54.213741
2019,368.428318,459.402885,74.027837,12.849784,0.183691,9.681390,28.371753,13.949752,8.430,63.784980

In [550]:
#prepare df with independent lines, + cumulative
temp = gas_cons.drop(['Solar', 'Hydro', 'Wind', 'Geo Biomass', 'Biofuels'], axis = 1)

cum_df = temp.cumsum(axis = 1)

cum_df.columns = ['Gas_sum', 'Oil_sum', 'Coal_sum', 'Nuclear_sum', 'R_sum']

sum_df = temp + cum_df

result= pd.concat([temp, cum_df], axis=1)
result = result*1000000000

In [551]:
result

,Gas,Oil,Coal,Nuclear,Renewables,Gas_sum,Oil_sum,Coal_sum,Nuclear_sum,R_sum
Year,,,,,,,,,,
1965,1.500001e+10,2.959048e+11,1.030556e+11,0.000000e+00,0.000000e+00,1.500001e+10,3.109048e+11,4.139604e+11,4.139604e+11,4.139604e+11
1966,2.861113e+10,3.208777e+11,9.388896e+10,0.000000e+00,0.000000e+00,2.861113e+10,3.494888e+11,4.433778e+11,4.433778e+11,4.433778e+11
1967,5.055560e+10,3.279670e+11,9.027785e+10,0.000000e+00,0.000000e+00,5.055560e+10,3.785226e+11,4.688004e+11,4.688004e+11,4.688004e+11
1968,8.500007e+10,3.537584e+11,8.555562e+10,7.777784e+07,0.000000e+00,8.500007e+10,4.387585e+11,5.243141e+11,5.243919e+11,5.243919e+11
1969,1.252779e+11,3.858377e+11,7.277784e+10,8.750007e+08,0.000000e+00,1.252779e+11,5.111156e+11,5.838934e+11,5.847684e+11,5.847684e+11
1970,1.763890e+11,4.290317e+11,5.333338e+10,1.022223e+09,0.000000e+00,1.763890e+11,6.054207e+11,6.587541e+11,6.597763e+11,6.597763e+11
1971,2.305557e+11,4.237896e+11,4.027781e+10,1.125001e+09,0.000000e+00,2.305557e+11,6.543453e+11,6.946231e+11,6.957481e+11,6.957481e+11
1972,3.000002e+11,4.727691e+11,3.444447e+10,9.055563e+08,0.000000e+00,3.000002e+11,7.727693e+11,8.072138e+11,8.081193e+11,8.081193e+11
1973,3.336114e+11,4.879270e+11,3.500003e+10,3.077780e+09,0.000000e+00,3.336114e+11,8.215384e+11,8.565385e+11,8.596162e+11,8.596162e+11
1974,3.550003e+11,4.183258e+11,3.333336e+10,9.102785e+09,0.000000e+00,3.550003e+11,7.733261e+11,8.066594e+11,8.157622e+11,8.157622e+11
1975,3.702781e+11,4.124860e+11,2.805558e+10,9.263896e+09,2.230557e+09,3.702781e+11,7.827641e+11,8.108197e+11,8.200836e+11,8.223141e+11
1976,3.844448e+11,4.642088e+11,3.500003e+10,1.075556e+10,2.422224e+09,3.844448e+11,8.486536e+11,8.836536e+11,8.944091e+11,8.968314e+11
1977,3.858336e+11,4.455198e+11,3.666670e+10,1.030556e+10,2.408335e+09,3.858336e+11,8.313534e+11,8.680201e+11,8.783257e+11,8.807340e+11
1978,3.866670e+11,4.551838e+11,4.194448e+10,1.127779e+10,3.363892e+09,3.866670e+11,8.418508e+11,8.837953e+11,8.950730e+11,8.984369e+11
1979,3.850003e+11,4.904422e+11,4.000003e+10,9.691674e+09,3.072225e+09,3.850003e+11,8.754425e+11,9.154425e+11,9.251342e+11,9.282064e+11
1980,3.519447e+11,4.586758e+11,4.638893e+10,1.166668e+10,2.844447e+09,3.519447e+11,8.106206e+11,8.570095e+11,8.686762e+11,8.715206e+11
1981,3.350003e+11,4.268683e+11,5.138893e+10,1.016112e+10,3.013891e+09,3.350003e+11,7.618686e+11,8.132575e+11,8.234186e+11,8.264325e+11
1982,3.200003e+11,3.730680e+11,5.944449e+10,1.082501e+10,7.361117e+08,3.200003e+11,6.930683e+11,7.525128e+11,7.633378e+11,7.640739e+11
1983,3.422225e+11,3.535348e+11,6.138894e+10,9.969452e+09,6.416672e+08,3.422225e+11,6.957573e+11,7.571462e+11,7.671157e+11,7.677573e+11
1984,3.636114e+11,3.490072e+11,7.416673e+10,1.030834e+10,4.722226e+07,3.636114e+11,7.126186e+11,7.867853e+11,7.970936e+11,7.971409e+11
1985,3.833336e+11,3.531462e+11,7.388895e+10,1.083056e+10,1.233334e+09,3.833336e+11,7.364798e+11,8.103687e+11,8.211993e+11,8.224326e+11
1986,3.822225e+11,3.915671e+11,7.611117e+10,1.171112e+10,1.547223e+09,3.822225e+11,7.737896e+11,8.499008e+11,8.616119e+11,8.631592e+11
1987,3.944448e+11,3.943724e+11,8.027784e+10,9.877786e+09,1.958335e+09,3.944448e+11,7.888171e+11,8.690950e+11,8.789728e+11,8.809311e+11
1988,3.566670e+11,4.184463e+11,9.611119e+10,1.020834e+10,2.369446e+09,3.566670e+11,7.751133e+11,8.712245e+11,8.814328e+11,8.838022e+11
1989,3.658336e+11,4.128927e+11,9.527785e+10,1.116390e+10,2.666669e+09,3.658336e+11,7.787263e+11,8.740042e+11,8.851681e+11,8.878347e+11
1990,3.680558e+11,4.285202e+11,1.016667e+11,9.727786e+09,2.252780e+09,3.680558e+11,7.965760e+11,8.982427e+11,9.079705e+11,9.102233e+11
1991,4.106948e+11,4.113501e+11,9.361119e+10,9.247230e+09,2.616669e+09,4.106948e+11,8.220449e+11,9.156560e+11,9.249033e+11,9.275199e+11
1992,3.999170e+11,4.318922e+11,9.333341e+10,1.055556e+10,2.833336e+09,3.999170e+11,8.318092e+11,9.251426e+11,9.356981e+11,9.385315e+11
1993,4.113059e+11,4.267474e+11,9.416674e+10,1.096668e+10,3.138891e+09,4.113059e+11,8.380533e+11,9.322200e+11,9.431867e+11,9.463256e+11
1994,3.972225e+11,4.240558e+11,1.002779e+11,1.101945e+10,3.547253e+09,3.972225e+11,8.212783e+11,9.215562e+11,9.325756e+11,9.361229e+11
1995,4.080281e+11,4.474752e+11,1.036112e+11,1.116112e+10,3.952781e+09,4.080281e+11,8.555033e+11,9.591145e+11,9.702756e+11,9.742284e+11
1996,4.521948e+11,4.473769e+11,1.000001e+11,1.155556e+10,5.097226e+09,4.521948e+11,8.995717e+11,9.995718e+11,1.011127e+12,1.016225e+12
1997,4.236948e+11,4.647488e+11,9.722230e+10,6.688894e+09,5.644449e+09,4.236948e+11,8.884436e+11,9.856659e+11,9.923548e+11,9.979992e+11
1998,4.183892e+11,4.702672e+11,9.916675e+10,1.058082e+10,6.516925e+09,4.183892e+11,8.886564e+11,9.878232e+11,9.984040e+11,1.004921e+12
1999,4.087781e+11,4.792939e+11,8.694451e+10,1.063393e+10,7.024608e+09,4.087781e+11,8.880720e+11,9.750166e+11,9.856505e+11,9.926751e+11
2000,4.099170e+11,4.861829e+11,9.027785e+10,1.088670e+10,8.311943e+09,4.099170e+11,8.960999e+11,9.863777e+11,9.972644e+11,1.005576e+12
2001,4.181948e+11,5.097190e+11,9.611119e+10,1.096327e+10,9.144180e+09,4.181948e+11,9.279138e+11,1.024025e+12,1.034988e+12,1.044132e+12
2002,4.139726e+11,5.120513e+11,9.666674e+10,1.073068e+10,1.091134e+10,4.139726e+11,9.260238e+11,1.022691e+12,1.033421e+12,1.044333e+12
2003,4.168337e+11,5.128088e+11,1.000001e+11,1.094645e+10,1.081107e+10,4.168337e+11,9.296425e+11,1.029643e+12,1.040589e+12,1.051400e+12
2004,4.267781e+11,5.364219e+11,9.861119e+10,1.034624e+10,1.440339e+10,4.267781e+11,9.632000e+11,1.061811e+12,1.072157e+12,1.086561e+12
2005,4.145559e+11,5.694234e+11,9.416674e+10,1.075266e+10,2.008239e+10,4.145559e+11,9.839792e+11,1.078146e+12,1.088899e+12,1.108981e+12
2006,3.980837e+11,5.670730e+11,8.972229e+10,9.273665e+09,2.204355e+10,3.980837e+11,9.651567e+11,1.054879e+12,1.064153e+12,1.086196e+12
2007,3.880559e+11,5.835206e+11,9.777786e+10,1.115709e+10,2.405744e+10,3.880559e+11,9.715765e+11,1.069354e+12,1.080511e+12,1.104569e+12
2008,4.038892e+11,5.548769e+11,9.250007e+10,1.100484e+10,2.839317e+10,4.038892e+11,9.587662e+11,1.051266e+12,1.062271e+12,1.090664e+12
2009,4.135837e+11,5.300782e+11,8.722229e+10,1.114533e+10,3.283580e+10,4.135837e+11,9.436619e+11,1.030884e+12,1.042030e+12,1.074865e+12
2010,4.675837e+11,5.399299e+11,8.777785e+10,1.034906e+10,3.197587e+10,4.675837e+11,1.007514e+12,1.095291e+12,1.105641e+12,1.137616e+12
2011,4.092781e+11,5.464574e+11,8.658340e+10,1.073068e+10,3.580147e+10,4.092781e+11,9.557355e+11,1.042319e+12,1.053050e+12,1.088851e+12
2012,3.928336e+11,5.188720e+11,9.513896e+10,1.008335e+10,3.627223e+10,3.928336e+11,9.117057e+11,1.006845e+12,1.016928e+12,1.053200e+12
2013,3.911114e+11,4.930154e+11,9.519452e+10,7.401302e+09,3.505005e+10,3.911114e+11,8.841268e+11,9.793213e+11,9.867226e+11,1.021773e+12
2014,3.447225e+11,4.703924e+11,1.053056e+11,1.041201e+10,3.422580e+10,3.447225e+11,8.151149e+11,9.204206e+11,9.308326e+11,9.650584e+11
2015,3.408058e+11,4.591964e+11,1.280834e+11,1.031648e+10,3.844955e+10,3.408058e+11,8.000022e+11,9.280857e+11,9.384021e+11,9.768517e+11
2016,3.515281e+11,4.738625e+11,1.186945e+11,9.959287e+09,4.010735e+10,3.515281e+11,8.253905e+11,9.440851e+11,9.540444e+11,9.941517e+11
2017,3.616670e+11,4.558944e+11,1.063890e+11,8.506202e+09,4.833217e+10,3.616670e+11,8.175614e+11,9.239503e+11,9.324565e+11,9.807887e+11
2018,3.536392e+11,4.673852e+11,9.550008e+10,8.735546e+09,5.421374e+10,3.536392e+11,8.210243e+11,9.165244e+11,9.252600e+11,9.794737e+11
2019,3.684283e+11,4.594029e+11,7.402784e+10,9.681390e+09,6.378498e+10,3.684283e+11,8.278312e+11,9.018590e+11,9.115404e+11,9.753254e+11

In [552]:
#data https://ourworldindata.org/co2/country/netherlands
output_file('gas_share.html')

#first lines

p1 = figure(x_range = (1965,2020), y_range = (0,100), sizing_mode='stretch_both', toolbar_location=None, x_axis_label ='Year', y_axis_label ='Energy share')

line2=p1.line(x =share_gas.index, y = share_gas.Gas, color= colour[1], line_width = 7, legend_label = 'Gas' )
p1.add_tools(HoverTool(renderers=[line2], tooltips=[('Type', 'Gas'),('Year', '@x'),('Percentage',"@y{0.0}%")],mode='mouse',toggleable=False))

line1=p1.line(x =share_gas.index, y = share_gas.Oil, color= colour[0], line_width = 4, alpha = 0.7, legend_label = 'Oil' )
p1.add_tools(HoverTool(renderers=[line1], tooltips=[('Type', 'Oil'),('Year', '@x'),('Percentage',"@y{0.0}%")],mode='mouse',toggleable=False))


line3=p1.line(x =share_gas.index, y = share_gas.Coal, color= colour[2], line_width = 4,alpha = 0.7, legend_label = 'Coal' )
p1.add_tools(HoverTool(renderers=[line3], tooltips=[('Type', 'Coal'),('Year', '@x'),('Percentage',"@y{0.0}%")],mode='mouse',toggleable=False))

nuc = p1.line(x = share_gas.index, y = share_gas.Nuclear, color= colour[3], line_width = 4, alpha = 0.7,legend_label = 'Nuclear' )
p1.add_tools(HoverTool(renderers=[nuc], tooltips=[('Type', 'Nuclear'),('Year', '@x'),('Percentage',"@y{0.0}%")],mode='mouse',toggleable=False))


line8=p1.line(x =share_gas.index, y = share_gas['Renewables'], color= colour[4], line_width = 4,alpha = 0.7, legend_label = 'Renewables' )
p1.add_tools(HoverTool(renderers=[line8], tooltips=[('Type', 'Renewables'),('Year', '@x'),('Percentage',"@y{0.0}%")],mode='mouse',toggleable=False))

p1.yaxis[0].formatter = PrintfTickFormatter(format='%0.0f%%')
p1.xaxis.major_label_orientation = 120

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Our World in Data'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p1.add_layout(caption1, 'below')
p1.toolbar.active_drag = None

show(p1)
save(p1)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/gas_share.html'

In [553]:
#second visualisation: stacked consumption
#data https://ourworldindata.org/co2/country/netherlands

output_file('gas_total.html')
source = ColumnDataSource(result)

p2 = figure(x_range = (1965,2020), y_range=(0,2000000000000),sizing_mode='stretch_both', toolbar_location=None, x_axis_label ='Year', y_axis_label ='Annual energy consumption (billions of kilowatt hours)',
           title = 'Gas provides over a third of energy used in the Netherlands')

p2.add_layout(Title(text="Energy consumption by source in the Netherlands", text_font_style="italic", text_font_size = '10px',), 'above')


p2.varea(x='Year', y1=0, y2='Gas_sum', source = source, color = colour[1], alpha = 0.7, legend_label = 'Gas')
gas = p2.line(x = 'Year', y = 'Gas_sum', source = source, color = colour[1])
p2.add_tools(HoverTool(renderers=[gas], tooltips=[('Type', 'Gas'),('Year', '@Year'),('kWh',"@Gas{0.0 a}")],mode='mouse',toggleable=False))


p2.varea(x='Year', y1='Gas_sum', y2='Oil_sum', source = source, color = colour[0], alpha = 0.7, legend_label = 'Oil')
oil = p2.line(x = 'Year', y = 'Oil_sum', source = source, color = colour[0])
p2.add_tools(HoverTool(renderers=[oil], tooltips=[('Type', 'Oil'),('Year', '@Year'),('kWh',"@Oil{0.0 a}")],mode='mouse',toggleable=False))


p2.varea(x='Year', y1='Oil_sum', y2='Coal_sum', source = source, color = colour[2], alpha = 0.7, legend_label = 'Coal')
coal = p2.line(x = 'Year', y = 'Coal_sum', source = source, color = colour[2])
p2.add_tools(HoverTool(renderers=[coal], tooltips=[('Type', 'Coal'),('Year', '@Year'),('kWh',"@Coal{0.0 a}")],mode='mouse',toggleable=False))

p2.varea(x='Year', y1='Coal_sum', y2='Nuclear_sum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Nuclear')
nuclear = p2.line(x = 'Year', y = 'Nuclear_sum', source = source, color = colour[3])
p2.add_tools(HoverTool(renderers=[nuclear], tooltips=[('Type', 'Nuclear'),('Year', '@Year'),('kWh',"@Nuclear{0.0 a}")],mode='mouse',toggleable=False))

p2.varea(x='Year', y1='Nuclear_sum', y2='R_sum', source = source, color = colour[4], alpha = 0.7, legend_label = 'Renewables')
renewable = p2.line(x = 'Year', y = 'R_sum', source = source, color = colour[4])
p2.add_tools(HoverTool(renderers=[renewable], tooltips=[('Type', 'Renewables'),('Year', '@Year'),('kWh',"@Renewables{0.0 a}")],mode='mouse',toggleable=False))

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data Source: Our World in Data -'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p2.add_layout(caption1, 'below')

msg = 'BP Statistical Review of World Energy'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p2.add_layout(caption1, 'below')


p2.xaxis.major_label_orientation = 120
p2.toolbar.active_drag = None

p2.yaxis[0].formatter = NumeralTickFormatter(format="0,0 a")


show(p2)
save (p2)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/gas_total.html'

In [554]:
#load data on imports and exports
im_ex = pd.read_csv('import_export.csv', sep = ';', names = ['year', 'imports', 'exports', 'units'])

im_ex = im_ex.iloc[1:]

In [555]:
for col in im_ex.columns[:-1]:
    #im_ex[col] = im_ex[col].str.replace('.0','')
    im_ex[col] = pd.to_numeric(im_ex[col])

In [556]:
im_ex = im_ex.sort_values(by = 'year', axis = 0, ascending = False)

In [557]:
im_ex['diff'] = im_ex['imports'] +im_ex['exports']

In [558]:
im_ex['diff'] = im_ex['diff'] *277778
im_ex['imports'] = im_ex['imports'] *277778
im_ex['exports'] = im_ex['exports'] *277778

In [559]:
im_ex

     year       imports       exports     units          diff
7  2020.0  553802943042 -370199185048  TJ-gross  183603757994
6  2015.0  377796413348 -513406799614  TJ-gross -135610386266
5  2010.0  238426024074 -551265996568  TJ-gross -312839972494
4  2005.0  212407669926 -482994275284  TJ-gross -270586605358
3  2000.0  161203740074 -383302806642  TJ-gross -222099066568
2  1995.0   35678917432 -376420023358  TJ-gross -340741105926
1  1990.0   26265576568 -333765822568  TJ-gross -307500246000

In [560]:

output_file('import_export.html')
source = ColumnDataSource(im_ex)

p = figure(x_range=(1986, 2024,), y_range=(-700000000000, 700000000000), y_axis_label = 'Gas import/export balance (billions of kilowatt hours)', x_axis_label = 'Year', 
           title ='The Netherlands now imports more gas than it exports',
           toolbar_location=None, sizing_mode = 'stretch_both')

p.add_layout(Title(text="Gas import/export balance in the Netherlands since 1990", text_font_style="italic", text_font_size = '10px',), 'above')

imp = p.vbar(x='year',bottom = 0, top = 'imports', width =1.5, source = source, fill_color = colour[0], legend_label = 'Gas imports')
#imp = p.scatter(y='year',x = 'imports', source = source, size = 5, fill_color = colour[0], line_color = colour[0])
p.add_tools(HoverTool(renderers=[imp], tooltips=[('Import', '@imports{0,0 a}n kWh')],mode='mouse',toggleable=False))

exp = p.vbar(x='year', bottom = 0, top = 'exports', width = 1.5, source = source, fill_color = colour[8], line_color = colour[8], legend_label = 'Gas exports')
#p.scatter(y='year',x = 'exports', source = source, size = 5, fill_color = colour[8], line_color = colour[8])
p.add_tools(HoverTool(renderers=[exp], tooltips=[('Export', '@exports{0,0 a}n kWh')],mode='mouse',toggleable=False))

#diff = p.scatter(y='year',x = 'diff', source = source, size = 20, fill_color = colour[3], line_color = colour[3], legend_label = 'Difference')
#p.add_tools(HoverTool(renderers=[diff], tooltips=[('Difference', '@diff{0,0} TJ gross')],mode='mouse',toggleable=False))


#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False

#p.left[0].formatter = NumeralTickFormatter(format="0,0 a")
p.yaxis.major_label_overrides = {0: '0', 200000000000: '200', 400000000000: '400', 600000000000: '600',
                                -200000000000: '-200', -400000000000: '-400', -600000000000: '-600'}


p.xaxis.minor_tick_line_color = None
p.toolbar.active_drag = None
p.legend.location = 'top_left'

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data Source: International Energy Agency'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/import_export.html'

# indonesia

In [561]:
#data load
indo_kyoto.head()

,year,IPC1,IPC2,IPC4,IPC5,IPCMAG,total,pop,pc,total_,mega
210,1960,36.9,0.95,5.11,0.721,59.5,103181000.0,87751066.0,1.175838,0.103181,103.181
211,1961,43.8,1.22,4.90,0.724,59.5,110144000.0,90098396.0,1.222486,0.110144,110.144
212,1962,39.0,1.17,4.67,0.728,61.5,107068000.0,92518373.0,1.157262,0.107068,107.068
213,1963,38.5,1.10,4.42,0.731,59.2,103951000.0,95015295.0,1.094045,0.103951,103.951
214,1964,37.8,1.21,4.15,0.735,60.2,104095000.0,97596728.0,1.066583,0.104095,104.095

In [562]:
indo_proj.head()

  index   paris  minimum  maximum     avg
0  2020  0.8817    0.892    0.942  0.9170
1  2021  0.8437    0.882    0.970  0.9260
2  2022  0.8057    0.906    1.001  0.9535
3  2023  0.7676    0.931    1.032  0.9815
4  2024  0.7296    0.955    1.063  1.0090

In [563]:
ghg = pd.read_csv('ghg-emissions.csv')



ghg = pd.pivot_table(ghg, columns = 'Country/Region')
#to gtonnes
ghg = ghg/1000

In [564]:
ghg

Country/Region     China    India  Indonesia  United States
1993             3.37779  1.12844    1.31127        5.69126
1994             3.52881  1.17478    1.32787        5.78220
1995             3.91830  1.24044    1.36088        5.84390
1996             3.95475  1.28963    1.17900        6.01062
1997             3.96361  1.34809    2.14282        6.25847
1998             4.10323  1.38226    1.37356        6.29380
1999             4.05337  1.46024    1.26156        6.29125
2000             4.24970  1.49820    1.19182        6.44620
2001             4.45991  1.74749    1.01935        6.40604
2002             4.76903  1.76979    1.50098        6.24695
2003             5.38689  1.81742    1.16769        6.30612
2004             6.13595  1.90513    1.51702        6.38722
2005             6.86281  1.97776    1.24270        6.40112
2006             7.54754  2.07367    1.65523        6.30681
2007             8.16543  2.21962    1.10024        6.39767
2008             8.45565  2.31748    1.08794        6.22021
2009             9.04619  2.46778    1.48361        5.79366
2010             9.87237  2.57693    1.12525        6.04159
2011            10.36483  2.61032    1.67572        5.79678
2012            10.69004  2.75853    1.69527        5.55087
2013            11.14476  2.81649    1.63617        5.69079
2014            11.15576  2.98834    2.01628        5.71115
2015            11.14968  3.00217    2.07024        5.58669
2016            11.20766  3.07324    1.45323        5.67692
2017            11.40826  3.20282    1.46605        5.61364
2018            11.70581  3.34663    1.70386        5.79435

In [565]:
# visualisation of indonesia total ghg emission vs world
#data source pik potsdam
output_file('indo_total.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Total greenhouse gas emissions (billions of tonnes CO2e)', title = 'Indonesia\'s emissions are around a seventh of the US\'s', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019), y_range = (0,50))

p.add_layout(Title(text="Total greenhouse gas emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')

#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


indo = p.line(x='year',y= 'total_', source = indo_kyoto, color = colour[4],line_width = 7, legend_label="Indonesia")
p.add_tools(HoverTool(renderers=[indo], tooltips=[('Country', 'Indonesia'),('Year',"@year"),('Emissions',"@mega{0.00} Mt")],mode='mouse', toggleable=False))

indo = p.line(x=ghg.index,y= ghg.Indonesia, color = 'black', line_width = 4, legend_label="Indonesia with land-use")
p.scatter(x=ghg.index,y= ghg.Indonesia, color = 'black',  size = 7)


fourth = p.line(x='year',y= 'total_',source=china_kyoto, color = colour[2],line_width = 4, alpha = 0.7, legend_label="China")
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse', toggleable=False))

first = p.line(x='year',y= 'total_',source=us_kyoto, color = colour[0],line_width = 4, alpha = 0.7, legend_label="US")
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse', toggleable=False))

third = p.line(x='year',y= 'total_',source=india_kyoto, color = colour[1],line_width = 4, alpha = 0.7, legend_label="India")
p.add_tools(HoverTool(renderers=[third], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse', toggleable=False))

eu = p.line(x='year', y= 'total_',source=eu_kyoto, color = colour[3], line_width = 4, alpha = 0.7, legend_label="EU")
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse',toggleable=False))

second = p.varea(x='year',y1 = 0, y2= 'total_',source=world_kyoto, color = colour[7], legend_label="World", alpha = 0.2, level ='underlay')
line = p.line(x ='year', y = 'total_', source = world_kyoto, color = colour[7], alpha = 0.1)
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse',toggleable=False))

p.yaxis[0].formatter = NumeralTickFormatter(format="0,000 a")

p.xaxis.major_label_orientation = 120

p.legend.location = 'top_left'

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'The PRIMAP-hist national historical emissions time series,'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'Climate Watch'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/indo_total.html'

In [566]:
# visualisation of indonesia metric tonnes co2 emission vs world average
#data source https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=usa&entity=kyotoghgar4


output_file('indo_per_capita.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Annual greenhouse gas emissions per capita (tonnes CO2e)', title = 'Per capita emissions in Indonesia are around half the global average',
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019),y_range = (0,45))

p.add_layout(Title(text="Per capita greenhouse gas emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')


#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


indo = p.line(x='year',y= 'pc',source=indo_kyoto, color = colour[4],line_width = 7, legend_label="Indonesia")
p.add_tools(HoverTool(renderers=[indo], tooltips=[('Country', 'Indonesia'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


second = p.line(x='year',y= 'pc',source=world_kyoto, color = colour[7],line_width = 3, line_dash = 'dashed', legend_label="World", alpha = 0.5)
p.add_tools(HoverTool(renderers=[second], tooltips=[('Region', 'World'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

first = p.line(x='year',y= 'pc',source=us_kyoto, color = colour[0],line_width = 3, legend_label="US", alpha = 0.5)
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


third = p.line(x='year',y= 'pc',source=eu_kyoto, color = colour[3],line_width = 3, legend_label="EU", alpha = 0.5)
p.add_tools(HoverTool(renderers=[third], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

fourth = p.line(x='year',y= 'pc',source=china_kyoto, color = colour[2],line_width = 3,legend_label="China", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


fifth = p.line(x='year',y= 'pc',source=india_kyoto, color = colour[1],line_width = 3, legend_label="India", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fifth], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


p.xaxis.major_label_orientation = 120
#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:The PRIMAP-hist national historical'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'emissions time series and the World Bank'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/indo_per_capita.html'

In [567]:
# visualisation of projected  tonnes co2 emission Indonesia
#https://climateactiontracker.org/countries/indonesia/
output_file('indo_projection.html')
source = ColumnDataSource(indo_proj)

p = figure(x_axis_label='Year', y_axis_label='Indonesia projected emissions (billions of tonnes CO2)', 
           title = 'Indonesia\'s emissions are projected to rise over the coming years', x_range = (2019.9,2030.1), y_range = (0,2),
            sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Projected CO2 emissions in Indonesia based on current policies", text_font_style="italic", text_font_size = '10px',), 'above')


proj = p.varea(x='index',
        y1='minimum',
        y2='maximum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Projected CO2 emissions')

p.legend.location = 'bottom_left'


#add average line
line = p.line(x ='index', y = 'avg', source = source, color= 'black', line_width = 1)
p.scatter(x='index', y ='avg', source = source, size = 3, fill_color = 'black', line_color = 'black')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Average projection',"@avg{0.00} Gt")],mode='mouse'))

#add paris scatter
paris = p.scatter(x = 'index', y = 'paris', source = source, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = '1.5C Paris compatible pathway*')
p.add_tools(HoverTool(renderers=[paris], tooltips=[('1.5C Compatible',"@paris{0.00} Gt")],mode='mouse'))

p.segment('index', 'paris', 'index', 'avg', source = source, line_width=2, line_color='black', alpha = 0.3, line_dash = [1,5] )

un = p.scatter(x = 2030, y=[1.661,1.671], size = 10, legend_label ='UN climate pledge')

# add a patch renderer with an alpha and line width
p.patch([2030, 2030], [1.661,1.671], line_width=5, alpha = 0.5)
p.add_tools(HoverTool(renderers = [un], tooltips =[('Upper', '1.66 Gt'), ('Lower', '1.67 Gt')]))

#p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Climate Action Tracker, September 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '* Using a global least-cost-solution model'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/indo_projection.html'

# fires

In [568]:
#load co2 emissions
#https://www.globalforestwatch.org/dashboards/country/IDN/?burnedAreaCumulative=eyJjb21wYXJlWWVhciI6ImFsbCJ9&category=climate&dashboardPrompts=eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6WyJkb3dubG9hZERhc2hib2FyZFN0YXRzIiwid2lkZ2V0U2V0dGluZ3MiLCJzaGFyZVdpZGdldCJdLCJzZXR0aW5ncyI6eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6WyJkb3dubG9hZERhc2hib2FyZFN0YXRzIiwid2lkZ2V0U2V0dGluZ3MiXSwic2V0dGluZ3MiOnsic2hvd1Byb21wdHMiOnRydWUsInByb21wdHNWaWV3ZWQiOlsiZG93bmxvYWREYXNoYm9hcmRTdGF0cyIsIndpZGdldFNldHRpbmdzIl0sInNldHRpbmdzIjp7InNob3dQcm9tcHRzIjp0cnVlLCJwcm9tcHRzVmlld2VkIjpbImRvd25sb2FkRGFzaGJvYXJkU3RhdHMiXSwic2V0dGluZ3MiOnsic2hvd1Byb21wdHMiOnRydWUsInByb21wdHNWaWV3ZWQiOltdLCJzZXR0aW5ncyI6eyJvcGVuIjpmYWxzZSwic3RlcEluZGV4IjowLCJzdGVwc0tleSI6IiJ9LCJvcGVuIjp0cnVlLCJzdGVwSW5kZXgiOjAsInN0ZXBzS2V5IjoiZG93bmxvYWREYXNoYm9hcmRTdGF0cyJ9LCJvcGVuIjp0cnVlLCJzdGVwSW5kZXgiOjAsInN0ZXBzS2V5Ijoid2lkZ2V0U2V0dGluZ3MifSwic3RlcHNLZXkiOiJ3aWRnZXRTZXR0aW5ncyIsInN0ZXBJbmRleCI6MCwib3BlbiI6ZmFsc2UsImZvcmNlIjp0cnVlfSwib3BlbiI6dHJ1ZSwic3RlcEluZGV4IjowLCJzdGVwc0tleSI6InNoYXJlV2lkZ2V0In0sInN0ZXBzS2V5Ijoic2hhcmVXaWRnZXQiLCJmb3JjZSI6dHJ1ZX0%3D&fireAlertStats=eyJmb3Jlc3RUeXBlIjoiaWZsIn0%3D&location=WyJjb3VudHJ5IiwiSUROIl0%3D&map=eyJjZW50ZXIiOnsibGF0IjoxMi43OTQzODcxNDU5NDgwMDgsImxuZyI6MTE0LjA2NDkzMzA4MDc4NDA3fSwiem9vbSI6My41OTczODE5NDQ0NDQ4NjE0LCJjYW5Cb3VuZCI6ZmFsc2UsImRhdGFzZXRzIjpbeyJkYXRhc2V0IjoicG9saXRpY2FsLWJvdW5kYXJpZXMiLCJsYXllcnMiOlsiZGlzcHV0ZWQtcG9saXRpY2FsLWJvdW5kYXJpZXMiLCJwb2xpdGljYWwtYm91bmRhcmllcyJdLCJib3VuZGFyeSI6dHJ1ZSwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZX0seyJkYXRhc2V0IjoibmV0LWNhcmJvbi1mbHV4IiwibGF5ZXJzIjpbIm5ldC1jYXJib24tZmx1eC0yMDAxLTIwMjAiXSwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZSwidGltZWxpbmVQYXJhbXMiOnsic3RhcnREYXRlIjoiMjAwMS0wMS0wMSIsImVuZERhdGUiOiIyMDIwLTEyLTMxIiwidHJpbUVuZERhdGUiOiIyMDIwLTEyLTMxIn0sInBhcmFtcyI6eyJ0aHJlc2hvbGQiOjMwLCJ2aXNpYmlsaXR5Ijp0cnVlfX0seyJkYXRhc2V0IjoiY2FyYm9uLXJlbW92YWxzIiwibGF5ZXJzIjpbImNhcmJvbi1yZW1vdmFscy0yMDAxLTIwMjAiXSwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZSwidGltZWxpbmVQYXJhbXMiOnsic3RhcnREYXRlIjoiMjAwMS0wMS0wMSIsImVuZERhdGUiOiIyMDIwLTEyLTMxIiwidHJpbUVuZERhdGUiOiIyMDIwLTEyLTMxIn0sInBhcmFtcyI6eyJ0aHJlc2hvbGQiOjMwLCJ2aXNpYmlsaXR5Ijp0cnVlfX0seyJkYXRhc2V0IjoiY2FyYm9uLWVtaXNzaW9ucyIsImxheWVycyI6WyJjYXJib24tZW1pc3Npb25zLTIwMDEtMjAyMCJdLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlLCJ0aW1lbGluZVBhcmFtcyI6eyJzdGFydERhdGUiOiIyMDAxLTAxLTAxIiwiZW5kRGF0ZSI6IjIwMjAtMTItMzEiLCJ0cmltRW5kRGF0ZSI6IjIwMjAtMTItMzEifSwicGFyYW1zIjp7InRocmVzaG9sZCI6MzAsInZpc2liaWxpdHkiOnRydWV9fV19&treeLossPct=eyJoaWdobGlnaHRlZCI6ZmFsc2V9
co2_forest = pd.read_csv('Forest_related_GHG_emissions.csv', names = ['year', 'all_gasses', 'non_co2', 'co2_only'], skiprows = 1)

co2_forest.head()

     year    all_gasses       non_co2      co2_only
IDN  2001  4.592794e+08  3.188493e+06  4.560909e+08
IDN  2002  5.810998e+08  7.937290e+06  5.731625e+08
IDN  2003  3.562404e+08  4.646855e+06  3.515935e+08
IDN  2004  9.266852e+08  1.557395e+07  9.111113e+08
IDN  2005  8.880859e+08  1.870182e+07  8.693841e+08

In [569]:
#load tree cover loss
#https://www.globalforestwatch.org/dashboards/country/IDN/?burnedAreaCumulative=eyJjb21wYXJlWWVhciI6ImFsbCJ9&category=forest-change&dashboardPrompts=eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6WyJkb3dubG9hZERhc2hib2FyZFN0YXRzIiwid2lkZ2V0U2V0dGluZ3MiLCJzaGFyZVdpZGdldCJdLCJzZXR0aW5ncyI6eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6WyJkb3dubG9hZERhc2hib2FyZFN0YXRzIiwid2lkZ2V0U2V0dGluZ3MiXSwic2V0dGluZ3MiOnsic2hvd1Byb21wdHMiOnRydWUsInByb21wdHNWaWV3ZWQiOlsiZG93bmxvYWREYXNoYm9hcmRTdGF0cyIsIndpZGdldFNldHRpbmdzIl0sInNldHRpbmdzIjp7InNob3dQcm9tcHRzIjp0cnVlLCJwcm9tcHRzVmlld2VkIjpbImRvd25sb2FkRGFzaGJvYXJkU3RhdHMiXSwic2V0dGluZ3MiOnsic2hvd1Byb21wdHMiOnRydWUsInByb21wdHNWaWV3ZWQiOltdLCJzZXR0aW5ncyI6eyJvcGVuIjpmYWxzZSwic3RlcEluZGV4IjowLCJzdGVwc0tleSI6IiJ9LCJvcGVuIjp0cnVlLCJzdGVwSW5kZXgiOjAsInN0ZXBzS2V5IjoiZG93bmxvYWREYXNoYm9hcmRTdGF0cyJ9LCJvcGVuIjp0cnVlLCJzdGVwSW5kZXgiOjAsInN0ZXBzS2V5Ijoid2lkZ2V0U2V0dGluZ3MifSwic3RlcHNLZXkiOiJ3aWRnZXRTZXR0aW5ncyIsInN0ZXBJbmRleCI6MCwib3BlbiI6ZmFsc2UsImZvcmNlIjp0cnVlfSwib3BlbiI6dHJ1ZSwic3RlcEluZGV4IjowLCJzdGVwc0tleSI6InNoYXJlV2lkZ2V0In0sInN0ZXBzS2V5Ijoic2hhcmVXaWRnZXQiLCJmb3JjZSI6dHJ1ZX0%3D&fireAlertStats=eyJmb3Jlc3RUeXBlIjoiaWZsIn0%3D&location=WyJjb3VudHJ5IiwiSUROIl0%3D&map=eyJjZW50ZXIiOnsibGF0IjoxMi43OTQzODcxNDU5NDgwMDgsImxuZyI6MTE0LjA2NDkzMzA4MDc4NDA3fSwiem9vbSI6My41OTczODE5NDQ0NDQ4NjE0LCJjYW5Cb3VuZCI6ZmFsc2UsImRhdGFzZXRzIjpbeyJvcGFjaXR5IjowLjcsInZpc2liaWxpdHkiOnRydWUsImRhdGFzZXQiOiJwcmltYXJ5LWZvcmVzdHMiLCJsYXllcnMiOlsicHJpbWFyeS1mb3Jlc3RzLTIwMDEiXX0seyJkYXRhc2V0IjoicG9saXRpY2FsLWJvdW5kYXJpZXMiLCJsYXllcnMiOlsiZGlzcHV0ZWQtcG9saXRpY2FsLWJvdW5kYXJpZXMiLCJwb2xpdGljYWwtYm91bmRhcmllcyJdLCJib3VuZGFyeSI6dHJ1ZSwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZX0seyJkYXRhc2V0IjoidHJlZS1jb3Zlci1sb3NzIiwibGF5ZXJzIjpbInRyZWUtY292ZXItbG9zcyJdLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlLCJ0aW1lbGluZVBhcmFtcyI6eyJzdGFydERhdGUiOiIyMDAyLTAxLTAxIiwiZW5kRGF0ZSI6IjIwMjAtMTItMzEiLCJ0cmltRW5kRGF0ZSI6IjIwMjAtMTItMzEifSwicGFyYW1zIjp7InRocmVzaG9sZCI6MzAsInZpc2liaWxpdHkiOnRydWV9fV19&treeLossPct=eyJoaWdobGlnaHRlZCI6ZmFsc2V9
forest_loss = pd.read_csv('treecover_loss__ha.csv', names = ['year', 'tree_cover_loss', 'co2_all_gasses'], skiprows = 1)
forest_loss = forest_loss.iloc[:, :-1]
forest_loss.head()

     year  tree_cover_loss
IDN  2001     7.440880e+05
IDN  2002     8.552759e+05
IDN  2003     5.448103e+05
IDN  2004     1.289043e+06
IDN  2005     1.182442e+06

In [570]:
#load primary forest loss
#same as above
primary_forests = pd.read_csv('treecover_loss_in_primary_forests_2001_tropics_only__ha.csv', names = ['year', 'primary_forest_loss', 'co2'], skiprows = 1)
primary_forests = primary_forests.iloc[:, :-1]
primary_forests.head()

     year  primary_forest_loss
IDN  2001        114393.788628
IDN  2002        271745.451978
IDN  2003        248435.592906
IDN  2004        479153.276835
IDN  2005        478405.812613

In [571]:
#merge data frames
indo_forests = pd.merge(co2_forest, forest_loss, on ='year')
indo_forests = pd.merge(indo_forests, primary_forests, on = 'year')
indo_forests['stand_forest'] = indo_forests['primary_forest_loss']/10000

indo_forests['all_gasses_mt']= indo_forests['all_gasses']/1000000

indo_forests.head()

,year,all_gasses,non_co2,co2_only,tree_cover_loss,primary_forest_loss,stand_forest,all_gasses_mt
0,2001,4.592794e+08,3.188493e+06,4.560909e+08,7.440880e+05,114393.788628,11.439379,459.279421
1,2002,5.810998e+08,7.937290e+06,5.731625e+08,8.552759e+05,271745.451978,27.174545,581.099772
2,2003,3.562404e+08,4.646855e+06,3.515935e+08,5.448103e+05,248435.592906,24.843559,356.240372
3,2004,9.266852e+08,1.557395e+07,9.111113e+08,1.289043e+06,479153.276835,47.915328,926.685214
4,2005,8.880859e+08,1.870182e+07,8.693841e+08,1.182442e+06,478405.812613,47.840581,888.085878

In [572]:
output_file('forests.html')
#data https://www.globalforestwatch.org/
from bokeh.models import TickFormatter, FixedTicker, Range1d, LinearAxis

#create figurebrazil_forests['all_gasses_mt']
p = figure(x_axis_label='Year', y_axis_label='Forest-related greenhouse gas emissions (millions of tonnes CO2e)',
           title = 'Forest loss in Indonesia leads to large CO2 emissions',x_range= (2000,2021), y_range = (0,4100),
            sizing_mode='stretch_both', toolbar_location=None, min_border=0, outline_line_color = None)

p.add_layout(Title(text="Greenhouse gas emissions by sector in Indonesia", text_font_style="italic", text_font_size = '10px',), 'above')


#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
#p.yaxis[0].formatter = NumeralTickFormatter(format="0")
p.xaxis.ticker = list(range(2000, 2021,5))

start = indo_forests.primary_forest_loss.min()
end= indo_forests.primary_forest_loss.max()

p.extra_y_ranges = {"Forest Loss": Range1d(0, 1100000)}
p.add_layout(LinearAxis(y_range_name="Forest Loss", axis_label = 'Forest loss (ha)'), 'right')
p.yaxis[1].formatter.use_scientific = False
p.yaxis[1].formatter = NumeralTickFormatter(format="0,0")
#p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

#set source to dataframe
s = ColumnDataSource(indo_forests)


#bar + linedata
bars = p.vbar(x = 'year', top = 'all_gasses_mt', width= 0.7, source = s,
          color=colour[6], line_color = colour[6], legend_label = 'Forest-related emissions')
#add tools
p.add_tools(HoverTool(renderers = [bars], tooltips = [('Year', '@year'), ('Emissions', '@all_gasses_mt{0,0} Mt')]))

line = p.line(x = 'year', y = 'primary_forest_loss', y_range_name = 'Forest Loss', source = s,
      color = colour[2], line_width = 5, legend_label = 'Primary forest loss')

p.add_tools(HoverTool(renderers =[line], tooltips = [('Year', '@year'),  ('Primary forest loss', '@primary_forest_loss{0,0} ha')]))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data sources: Global Forest Watch'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

p.legend.location = 'top_left'
#add bar

p.xaxis.major_label_orientation = 120

p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/forests.html'

In [573]:
#load data on lulucf
lulucf = pd.read_csv('ghg-emissions-by-sector.csv')

lulucf = lulucf[lulucf['Entity'] == 'Indonesia']

lulucf = lulucf.iloc[:, 2:]

#[2017,196080000,  
 
#[2018, 200240000,] 


lulucf

,Year,"Agriculture (GHG Emissions, CAIT)","Land-Use Change and Forestry (GHG Emissions, CAIT)","Waste (GHG Emissions, CAIT)","Industry (GHG Emissions, CAIT)","Manufacturing/Construction energy (GHG Emissions, CAIT)","Transport (GHG Emissions, CAIT)","Electricity & Heat (GHG Emissions, CAIT)","Buildings (GHG Emissions, CAIT)","Fugitive from energy production (GHG Emissions, CAIT)","Other Fuel Combustion (GHG Emissions, CAIT)","Bunker Fuels (GHG Emissions, CAIT)"
2133,1990,133060000.0,1.002220e+09,158200000.0,8600000.0,30900000.0,32200000.0,47800000.0,19500000.0,55790000.0,23880000.0,2700000.0
2134,1991,132400000.0,1.002220e+09,161520000.0,9950000.0,30900000.0,35900000.0,54100000.0,20200000.0,58850000.0,23690000.0,1700000.0
2135,1992,139740000.0,1.002220e+09,164850000.0,10630000.0,32600000.0,37900000.0,56200000.0,21400000.0,60650000.0,24330000.0,1700000.0
2136,1993,137230000.0,1.002220e+09,168180000.0,11610000.0,35800000.0,40500000.0,62700000.0,21600000.0,62340000.0,24880000.0,1800000.0
2137,1994,138250000.0,1.002220e+09,171520000.0,13370000.0,41700000.0,45400000.0,63900000.0,22300000.0,60420000.0,24880000.0,1700000.0
2138,1995,144200000.0,1.002220e+09,174660000.0,14130000.0,50900000.0,49300000.0,74300000.0,23900000.0,56020000.0,25390000.0,2500000.0
2139,1996,147500000.0,7.768100e+08,178290000.0,15120000.0,50700000.0,54600000.0,77500000.0,25400000.0,51610000.0,26360000.0,1600000.0
2140,1997,142800000.0,1.744800e+09,181920000.0,16890000.0,54900000.0,60700000.0,88800000.0,25800000.0,47040000.0,26730000.0,2200000.0
2141,1998,145580000.0,9.467500e+08,185550000.0,13940000.0,52100000.0,59200000.0,98500000.0,26700000.0,42810000.0,27500000.0,2000000.0
2142,1999,143730000.0,8.148300e+08,189170000.0,14970000.0,67900000.0,58800000.0,95600000.0,31300000.0,38070000.0,30270000.0,1700000.0
2143,2000,143060000.0,7.382400e+08,192800000.0,20000000.0,58300000.0,62700000.0,89400000.0,33700000.0,35240000.0,33340000.0,1600000.0
2144,2001,141690000.0,9.822400e+08,186350000.0,22240000.0,62400000.0,66800000.0,100000000.0,33400000.0,35070000.0,33690000.0,1600000.0
2145,2002,144700000.0,1.517050e+09,179900000.0,22070000.0,59100000.0,68000000.0,109200000.0,32200000.0,33430000.0,33430000.0,1600000.0
2146,2003,143960000.0,1.118990e+09,173440000.0,21900000.0,74800000.0,69300000.0,121500000.0,32300000.0,33810000.0,32680000.0,2300000.0
2147,2004,147880000.0,1.496820e+09,166990000.0,23350000.0,80500000.0,70800000.0,119600000.0,32900000.0,32660000.0,33930000.0,1800000.0
2148,2005,148380000.0,1.208600e+09,160530000.0,23010000.0,81600000.0,70600000.0,124200000.0,31400000.0,32120000.0,32580000.0,1900000.0
2149,2006,150030000.0,1.962830e+09,154080000.0,23770000.0,105000000.0,67200000.0,130200000.0,28200000.0,29330000.0,31350000.0,2100000.0
2150,2007,154710000.0,1.324550e+09,147630000.0,24510000.0,111500000.0,68700000.0,138600000.0,28200000.0,27960000.0,30730000.0,2200000.0
2151,2008,158760000.0,1.317590e+09,141170000.0,25680000.0,101500000.0,73000000.0,141100000.0,25300000.0,28230000.0,31000000.0,2300000.0
2152,2009,165980000.0,1.734700e+09,134720000.0,24790000.0,100500000.0,82700000.0,147900000.0,21600000.0,30860000.0,31370000.0,2400000.0
2153,2010,169190000.0,1.317020e+09,128270000.0,24410000.0,89200000.0,90800000.0,152000000.0,19700000.0,26920000.0,31850000.0,2600000.0
2154,2011,172420000.0,1.513100e+09,121810000.0,26130000.0,84300000.0,110000000.0,168800000.0,20100000.0,30090000.0,30050000.0,2700000.0
2155,2012,177800000.0,1.530230e+09,115360000.0,28180000.0,84100000.0,131200000.0,168800000.0,21600000.0,32340000.0,30360000.0,2900000.0
2156,2013,173690000.0,1.497640e+09,120060000.0,30100000.0,80800000.0,137800000.0,168200000.0,22800000.0,33390000.0,30070000.0,3100000.0
2157,2014,179350000.0,1.884820e+09,124760000.0,30710000.0,94200000.0,138200000.0,193800000.0,23200000.0,33740000.0,29390000.0,3200000.0
2158,2015,182500000.0,1.925390e+09,127280000.0,32140000.0,105900000.0,124100000.0,195500000.0,24200000.0,33350000.0,28940000.0,3300000.0
2159,2016,190220000.0,1.363070e+09,129470000.0,33750000.0,84200000.0,134500000.0,206600000.0,23100000.0,33250000.0,30950000.0,3600000.0

In [574]:
hist = pd.read_csv('historical_emissions.csv')
hist = pd.pivot_table(hist, columns = 'Sector')
hist.index.name = 'year'
hist = hist.reset_index()

hist['year'] = pd.to_numeric(hist['year'])

In [575]:
new_c = []

for col in lulucf.columns:
    col = col.replace(' (GHG Emissions, CAIT)', '')
    new_c.append(col)

lulucf.columns = new_c


lulucf = lulucf.rename(columns={'Manufacturing/Construction energy':'Manufacturing', 'Electricity & Heat': 'Electricty',
                               'Fugitive from energy production': 'Fugitive', 'Other Fuel Combustion':'other_fuel',
                               'Bunker Fuels': 'bunker'})
#IMPORTANT: DATASET CHANGE
lulucf = hist

lulucf = lulucf.rename(columns ={'Electricity/Heat':'Electricity'})

lulucf['other'] = lulucf['Fugitive Emissions'] + lulucf['Other Fuel Combustion'] + lulucf['Bunker Fuels']

lulucf = lulucf.drop(['Fugitive Emissions', 'Other Fuel Combustion', 'Bunker Fuels'], axis = 1)
lulucf['ind_manu'] = lulucf['Industrial Processes'] + lulucf['Manufacturing/Construction']
lulucf = lulucf.drop(['Industrial Processes', 'Manufacturing/Construction'], axis = 1)

lulu = lulucf.iloc[:,5]


lulucf = lulucf.drop(['Land-Use Change and Forestry'], axis = 1)

lulucf['LULUCF'] = lulu

lulucf = lulucf.set_index('year')

In [576]:
cum_df_ind = lulucf.cumsum(axis = 1)
cum_df_ind
cum_df_ind.columns = ['Agri_sum', 'Buil_sum','Elect_sum', 'Energy_sum','trans_sum','Waste_sum', 'other_sum', 'ind_sum', 'Lulucf_sum']


lulucf_sum= pd.concat([lulucf, cum_df_ind], axis=1)
lulucf_sum

,Agriculture,Building,Electricity,Energy,Transportation,Waste,other,ind_manu,LULUCF,Agri_sum,Buil_sum,Elect_sum,Energy_sum,trans_sum,Waste_sum,other_sum,ind_sum,Lulucf_sum
year,,,,,,,,,,,,,,,,,,
1990,132.57,19.52,47.75,207.16,32.20,158.20,82.37,36.54,750.63,132.57,152.09,199.84,407.00,439.20,597.40,679.77,716.31,1466.94
1991,131.91,20.24,54.09,220.49,35.85,161.52,84.21,37.63,750.63,131.91,152.15,206.24,426.73,462.58,624.10,708.31,745.94,1496.57
1992,139.25,21.41,56.17,229.75,37.91,164.85,86.74,39.79,750.63,139.25,160.66,216.83,446.58,484.49,649.34,736.08,775.87,1526.50
1993,136.74,21.61,62.70,244.20,40.49,168.18,88.98,43.71,750.63,136.74,158.35,221.05,465.25,505.74,673.92,762.90,806.61,1557.24
1994,137.76,22.27,63.90,254.72,45.35,171.52,87.07,51.10,750.61,137.76,160.03,223.93,478.65,524.00,695.52,782.59,833.69,1584.30
1995,143.95,23.98,74.27,275.67,49.26,174.66,83.88,60.75,752.60,143.95,167.93,242.20,517.87,567.13,741.79,825.67,886.42,1639.02
1996,146.98,25.45,77.52,282.41,54.60,178.29,79.48,61.86,556.34,146.98,172.43,249.95,532.36,586.96,765.25,844.73,906.59,1462.93
1997,142.44,25.87,88.77,299.93,60.65,181.92,75.91,67.63,1501.80,142.44,168.31,257.08,557.01,617.66,799.58,875.49,943.12,2444.92
1998,145.45,26.63,98.59,302.40,59.20,185.55,72.41,61.44,726.35,145.45,172.08,270.67,573.07,632.27,817.82,890.23,951.67,1678.02
1999,143.74,31.31,95.59,315.31,58.78,189.17,70.00,76.06,598.51,143.74,175.05,270.64,585.95,644.73,833.90,903.90,979.96,1578.47
2000,143.06,33.69,89.36,312.20,62.70,192.80,70.09,77.76,523.94,143.06,176.75,266.11,578.31,641.01,833.81,903.90,981.66,1505.60
2001,141.71,33.46,100.01,331.25,66.76,186.35,70.34,84.21,338.04,141.71,175.17,275.18,606.43,673.19,859.54,929.88,1014.09,1352.13
2002,145.20,32.13,109.24,335.19,68.00,179.90,68.48,80.85,818.83,145.20,177.33,286.57,621.76,689.76,869.66,938.14,1018.99,1837.82
2003,144.10,32.33,121.47,364.24,69.28,173.44,68.73,96.37,464.21,144.10,176.43,297.90,662.14,731.42,904.86,973.59,1069.96,1534.17
2004,148.61,32.92,119.66,370.20,70.84,166.99,68.39,103.38,808.11,148.61,181.53,301.19,671.39,742.23,909.22,977.61,1080.99,1889.10
2005,148.58,31.37,124.11,371.36,69.84,160.53,67.51,104.07,539.45,148.58,179.95,304.06,675.42,745.26,905.79,973.30,1077.37,1616.82
2006,151.04,28.19,130.17,389.96,66.30,154.08,63.58,128.16,936.64,151.04,179.23,309.40,699.36,765.66,919.74,983.32,1111.48,2048.12
2007,154.78,28.19,138.66,404.74,67.81,147.63,61.95,135.46,368.84,154.78,182.97,321.63,726.37,794.18,941.81,1003.76,1139.22,1508.06
2008,158.80,25.35,152.51,400.40,72.07,141.17,62.16,117.02,362.12,158.80,184.15,336.66,737.06,809.13,950.30,1012.46,1129.48,1491.60
2009,166.49,21.60,153.25,418.24,81.68,134.72,64.89,124.83,739.58,166.49,188.09,341.34,759.58,841.26,975.98,1040.87,1165.70,1905.28
2010,169.21,19.70,149.00,440.12,89.11,128.27,60.44,150.97,362.85,169.21,188.91,337.91,778.03,867.14,995.41,1055.85,1206.82,1569.67
2011,172.70,20.02,176.03,501.48,108.50,121.81,65.41,162.25,853.24,172.70,192.72,368.75,870.23,978.73,1100.54,1165.95,1328.20,2181.44
2012,178.07,21.54,168.79,505.02,129.63,115.36,70.40,147.93,868.05,178.07,199.61,368.40,873.42,1003.05,1118.41,1188.81,1336.74,2204.79
2013,173.88,22.76,168.20,472.62,136.12,120.06,71.35,109.26,839.29,173.88,196.64,364.84,837.46,973.58,1093.64,1164.99,1274.25,2113.54
2014,180.06,23.21,193.76,509.19,136.59,124.76,71.54,119.94,1171.21,180.06,203.27,397.03,906.22,1042.81,1167.57,1239.11,1359.05,2530.26
2015,183.36,24.14,195.51,511.21,122.57,127.28,73.89,130.14,1218.24,183.36,207.50,403.01,914.22,1036.79,1164.07,1237.96,1368.10,2586.34
2016,190.77,23.10,206.45,511.55,133.64,129.47,69.45,118.80,586.87,190.77,213.87,420.32,931.87,1065.51,1194.98,1264.43,1383.23,1970.10
2017,196.08,24.97,218.73,548.51,141.68,131.65,69.25,135.74,553.63,196.08,221.05,439.78,988.29,1129.97,1261.62,1330.87,1466.61,2020.24
2018,200.24,25.12,243.36,598.17,154.01,133.84,67.01,151.78,734.28,200.24,225.36,468.72,1066.89,1220.90,1354.74,1421.75,1573.53,2307.81

In [577]:
#to gigatonnes
lulucf_sum = lulucf_sum/1000

In [578]:
lulucf_sum.head()

,Agriculture,Building,Electricity,Energy,Transportation,Waste,other,ind_manu,LULUCF,Agri_sum,Buil_sum,Elect_sum,Energy_sum,trans_sum,Waste_sum,other_sum,ind_sum,Lulucf_sum
year,,,,,,,,,,,,,,,,,,
1990,0.13257,0.01952,0.04775,0.20716,0.03220,0.15820,0.08237,0.03654,0.75063,0.13257,0.15209,0.19984,0.40700,0.43920,0.59740,0.67977,0.71631,1.46694
1991,0.13191,0.02024,0.05409,0.22049,0.03585,0.16152,0.08421,0.03763,0.75063,0.13191,0.15215,0.20624,0.42673,0.46258,0.62410,0.70831,0.74594,1.49657
1992,0.13925,0.02141,0.05617,0.22975,0.03791,0.16485,0.08674,0.03979,0.75063,0.13925,0.16066,0.21683,0.44658,0.48449,0.64934,0.73608,0.77587,1.52650
1993,0.13674,0.02161,0.06270,0.24420,0.04049,0.16818,0.08898,0.04371,0.75063,0.13674,0.15835,0.22105,0.46525,0.50574,0.67392,0.76290,0.80661,1.55724
1994,0.13776,0.02227,0.06390,0.25472,0.04535,0.17152,0.08707,0.05110,0.75061,0.13776,0.16003,0.22393,0.47865,0.52400,0.69552,0.78259,0.83369,1.58430

In [579]:
# visualisation: GHG emissions per sector
#data https://www.climatewatchdata.org/data-explorer/historical-emissions?historical-emissions-data-sources=cait&historical-emissions-gases=All%20Selected%2Call-ghg&historical-emissions-regions=All%20Selected%2CIDN&historical-emissions-sectors=agriculture%2Cbuilding%2Cbunker-fuels%2Celectricity-heat%2Cenergy%2Cfugitive-emissions%2Cindustrial-processes%2Cland-use-change-and-forestry%2Cmanufacturing-construction%2Cother-fuel-combustion%2Ctransportation%2Cwaste&page=1&sort_col=unit&sort_dir=ASC
output_file('sector.html')

source = ColumnDataSource(lulucf_sum)

p2 = figure(x_range = (1990,2018),y_range = (0,5),sizing_mode='stretch_both', 
            title = 'Land use change and forestry emissions dominate Indonesia\'s climate impact',toolbar_location=None, x_axis_label = 'Year', y_axis_label = 'Greenhouse gas emissions (billions of tonnes CO2e)')

p2.add_layout(Title(text="Greenhouse gas emissions by sector in Indonesia", text_font_style="italic", text_font_size = '10px',), 'above')

p2.varea(x='year', y1=0, y2='Agriculture', source = source, color = colour[0], alpha = 0.7, legend_label = 'Agriculture')
agri = p2.line(x = 'year', y = 'Agriculture', source = source, color = colour[0])
p2.add_tools(HoverTool(renderers=[agri], tooltips=[('Type', 'Agriculture'),('Year', '@year'),('Emissions in billions of tonnes',"@Agriculture{0.00}")],mode='mouse',toggleable=False))


p2.varea(x='year', y1='Agriculture', y2='Buil_sum', source = source, color = colour[1], alpha = 0.7, legend_label = 'Buildings')
buil = p2.line(x = 'year', y = 'Buil_sum', source = source, color = colour[1])
p2.add_tools(HoverTool(renderers=[buil], tooltips=[('Type', 'Buildings'),('Year', '@year'),('Emissions in billions of tonnes',"@Building{0.00}")],mode='mouse',toggleable=False))


p2.varea(x='year', y1='Buil_sum', y2='Elect_sum', source = source, color = colour[2], alpha = 0.7, legend_label = 'Electricty and heat')
el = p2.line(x = 'year', y = 'Elect_sum', source = source, color = colour[2])
p2.add_tools(HoverTool(renderers=[el], tooltips=[('Type', 'Electricty and heating'),('Year', '@year'),('Emissions in billions of tonnes',"@Electricity{0.00}")],mode='mouse',toggleable=False))


p2.varea(x='year', y1='Elect_sum', y2='Energy_sum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Energy')
en = p2.line(x = 'year', y = 'Energy_sum', source = source, color = colour[3])
p2.add_tools(HoverTool(renderers=[en], tooltips=[('Type', 'Energy'),('Year', '@year'),('Emissions in billions of tonnes',"@Energy{0.00}")],mode='mouse',toggleable=False))


p2.varea(x='year', y1='Energy_sum', y2='trans_sum', source = source, color = colour[4], alpha = 0.7, legend_label = 'Transport')
trans = p2.line(x = 'year', y = 'trans_sum', source = source, color = colour[4])
p2.add_tools(HoverTool(renderers=[trans], tooltips=[('Type', 'Transport'),('Year', '@year'),('Emissions in billions of tonnes',"@Transportation{0.00}")],mode='mouse',toggleable=False))


p2.varea(x='year', y1='trans_sum', y2='Waste_sum', source = source, color = colour[5], alpha = 0.7, legend_label = 'Waste')
waste = p2.line(x = 'year', y = 'Waste_sum', source = source, color = colour[5])
p2.add_tools(HoverTool(renderers=[waste], tooltips=[('Type', 'Waste'),('Year', '@year'),('Emissions in billions of tonnes',"@Waste{0.0}")],mode='mouse',toggleable=False))


p2.varea(x='year', y1='Waste_sum', y2='other_sum', source = source, color = colour[6], alpha = 0.7, legend_label = 'Other emissions')
other = p2.line(x = 'year', y = 'other_sum', source = source, color = colour[6])
p2.add_tools(HoverTool(renderers=[other], tooltips=[('Type', 'Other emissions'),('Year', '@year'),('Emissions in billions of tonnes',"@other{0.00}")],mode='mouse',toggleable=False))


p2.varea(x='year', y1='other_sum', y2='ind_sum', source = source, color = colour[7], alpha = 0.7, legend_label = 'Industry and manufacturing')
ind = p2.line(x = 'year', y = 'ind_sum', source = source, color = colour[7])
p2.add_tools(HoverTool(renderers=[ind], tooltips=[('Type', 'Industry and manufacturing'),('Year', '@year'),('Emissions in billions of tonnes',"@ind_manu{0.00}")],mode='mouse',toggleable=False))


p2.varea(x='year', y1='ind_sum', y2='Lulucf_sum', source = source, color = '#fcba03', alpha = 0.7, legend_label = 'Land use change and forestry')
ind = p2.line(x = 'year', y = 'Lulucf_sum', source = source, color = '#fcba03')
p2.add_tools(HoverTool(renderers=[ind], tooltips=[('Type', 'Land use change and forestry'),('Year', '@year'),('Emissions in billions of tonnes',"@LULUCF{0.00}")],mode='mouse',toggleable=False))



p2.legend.location = "top_left"


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data sources:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p2.add_layout(caption1, 'below')
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'CAIT Climate Data Explorer via. Climate Watch'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p2.add_layout(caption1, 'below')
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')

msg = '*Land use, land change & forestry'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic', text_color = 'white')
#p2.add_layout(caption1, 'center')
p2.xaxis.major_label_orientation = 120



#Disable scientific notation on axes
p2.left[0].formatter.use_scientific = False
#p2.yaxis[0].formatter = NumeralTickFormatter(format="0 a")
p2.toolbar.active_drag = None

show(p2)
save(p2)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/sector.html'

# China coal data

In [580]:
#china coal data from boston uni https://www.bu.edu/cgp/
china_coal = pd.read_csv('China_coal.csv')

capacity = china_coal[china_coal['Project Status'] != 'Under Planning']

up = china_coal[china_coal['Project Status'] == 'Under Planning']


china_coal = china_coal.iloc[:, :-6]
capacity = capacity.iloc[:, :-6]

#preparing smaller df with useful data
coal_co2 = china_coal[['Capacity (MW)','Year of Commission', 'Technology','Region','Estimated Annual CO2 Emission from Power Generation (1000 ton)']] 
capacity = capacity[['Capacity (MW)','Year of Commission', 'Technology','Project Status','Region','Estimated Annual CO2 Emission from Power Generation (1000 ton)']] 


xrange = coal_co2['Year of Commission'].unique()
xrange.sort()
xrange = xrange[10:]

In [581]:
bar_co2 = coal_co2[coal_co2['Technology'] == 'Coal']

In [582]:
capacity

,Capacity (MW),Year of Commission,Technology,Project Status,Region,Estimated Annual CO2 Emission from Power Generation (1000 ton)
0,38.0,2007,Wind,In Operation,Europe/Central Asia,0
1,20.0,2013,Wind,In Operation,Europe/Central Asia,0
2,51.0,2012,Wind,In Operation,Africa,0
3,153.0,2016,Wind,In Operation,Africa,0
4,700.0,2015,Coal,In Operation,Southeast Asia,3579
...,...,...,...,...,...,...
772,28.0,2018,Wind,In Operation,LAC,0
773,28.0,2018,Wind,In Operation,LAC,0
774,28.0,2018,Wind,In Operation,LAC,0
775,28.0,2018,Wind,In Operation,LAC,0
776,30.0,2019,Wind,In Operation,LAC,0

In [583]:
def pivot(df):

    df = pd.pivot_table(df, values = 'Estimated Annual CO2 Emission from Power Generation (1000 ton)',
                        index = 'Year of Commission')
    return df

In [584]:
SEA = pivot(SEA)
SA = pivot(SA)
EU = pivot(EU)
ME = pivot(ME)
LAC = pivot(LAC)
oceania = pivot(oceania)
africa = pivot(africa)

In [585]:
grouped = bar_co2.groupby(['Year of Commission', 'Region']).sum()


#from 2015
grouped = grouped.iloc[14:].reset_index(1)

grouped = pd.pivot_table(grouped, index = 'Year of Commission',values = 'Estimated Annual CO2 Emission from Power Generation (1000 ton)', columns = 'Region')

grouped = grouped.fillna(0)
grouped

#cum sum
cum_ = grouped.cumsum(axis = 1)
cum_.columns =['afr_sum', 'eu_sum', 'me_sum', 'sa_sum', 'sea_sum'] 

coal_result = pd.concat([grouped, cum_], axis=1)

#coal_result = coal_result.iloc[:-1]
#convert 1000tonnes to mega ton
coal_result = coal_result/1000
coal_result

,Africa,Europe/Central Asia,Middle East,South Asia,Southeast Asia,afr_sum,eu_sum,me_sum,sa_sum,sea_sum
Year of Commission,,,,,,,,,,
2015,5.353,0.000,0.000,5.786,18.262,5.353,5.353,5.353,11.139,29.401
2016,0.000,4.218,0.000,0.000,9.097,0.000,4.218,4.218,4.218,13.315
2017,18.401,1.512,0.000,13.308,6.955,18.401,19.913,19.913,33.221,40.176
2018,0.000,0.000,0.000,0.000,14.037,0.000,0.000,0.000,0.000,14.037
2019,16.059,0.000,0.000,16.634,6.351,16.059,16.059,16.059,32.693,39.044
2020,10.706,0.000,4.015,0.000,6.049,10.706,10.706,14.721,14.721,20.770
2021,10.706,0.000,4.015,1.664,20.161,10.706,10.706,14.721,16.385,36.546
2022,5.353,0.000,4.015,0.000,6.251,5.353,5.353,9.368,9.368,15.619
2023,4.015,2.276,4.015,0.000,0.000,4.015,6.291,10.306,10.306,10.306
Pending,6.691,10.003,8.833,37.052,11.089,6.691,16.694,25.527,62.579,73.668

In [586]:
group = capacity.groupby(['Year of Commission', 'Technology','Project Status']).sum()


#from 2015


group = pd.pivot_table(group, index = 'Year of Commission',values = 'Capacity (MW)', columns = 'Technology')

group = group.fillna(0)

group = group.iloc[10:-8]

#last = group.iloc[-1:]
#group.iloc[-1:] = last

group['renewable'] = group['Biomass'] + group['Solar'] + group['Wind']# + group['Geothermal']
group = group.drop(['Biomass', 'Solar', 'Wind'], axis = 1)

#'Geothermal'

cum_ = group.cumsum(axis = 1)


cum_.columns = ['coal_sum', 'gas_sum', 'hydro_sum','nuclear_sum', 'oil_sum', 'R_sum']




result= pd.concat([group, cum_], axis=1)
#billions of watt
result = result*0.001

In [587]:
result

,Coal,Gas,Hydropower,Nuclear,Oil,renewable,coal_sum,gas_sum,hydro_sum,nuclear_sum,oil_sum,R_sum
Year of Commission,,,,,,,,,,,,
2010,0.300,1.848,1.3150,0.000,0.416,0.0570,0.300,2.148,3.4630,3.4630,3.8790,3.9360
2011,5.717,4.948,1.3290,0.000,0.060,0.1900,5.717,10.665,11.9940,11.9940,12.0540,12.2440
2012,2.110,0.970,0.5560,0.325,0.101,0.4020,2.110,3.080,3.6360,3.9610,4.0620,4.4640
2013,3.775,0.420,1.1600,0.000,0.000,1.0210,3.775,4.195,5.3550,5.3550,5.3550,6.3760
2014,7.938,0.371,0.9580,0.000,0.100,0.3980,7.938,8.309,9.2670,9.2670,9.3670,9.7650
2015,5.073,0.537,5.6900,0.000,0.485,1.2300,5.073,5.610,11.3000,11.3000,11.7850,13.0150
2016,2.555,4.149,4.4840,0.340,0.060,2.0010,2.555,6.704,11.1880,11.5280,11.5880,13.5890
2017,7.070,0.480,3.9405,0.340,0.492,2.5060,7.070,7.550,11.4905,11.8305,12.3225,14.8285
2018,2.785,2.112,4.4070,0.000,0.371,0.5770,2.785,4.897,9.3040,9.3040,9.6750,10.2520
2019,3.480,0.000,1.5695,0.000,0.286,2.0653,3.480,3.480,5.0495,5.0495,5.3355,7.4008
2020,3.400,0.000,2.5400,0.000,0.470,0.8510,3.400,3.400,5.9400,5.9400,6.4100,7.2610
2021,6.530,0.000,0.3180,0.000,0.000,0.0000,6.530,6.530,6.8480,6.8480,6.8480,6.8480
2022,2.640,0.000,1.1780,2.200,0.000,0.3700,2.640,2.640,3.8180,6.0180,6.0180,6.3880
2023,1.550,0.000,3.0480,0.000,0.000,0.4990,1.550,1.550,4.5980,4.5980,4.5980,5.0970
2024,0.000,0.000,0.0280,0.000,0.000,0.9550,0.000,0.000,0.0280,0.0280,0.0280,0.9830
2025,0.000,0.000,0.0000,3.540,0.000,0.2670,0.000,0.000,0.0000,3.5400,3.5400,3.8070

In [588]:
#bar chart
#set up figure

from bokeh.models import Span
output_file('coal_co2.html')

colour = d3['Category10'][10]

source = ColumnDataSource(coal_result[:-3])

p1 = figure(x_axis_label='Year', y_axis_label='Estimated annual CO2 emissions (millions of tonnes)',
            title = '...', x_range = list(coal_result.index), y_range = (0, 80), toolbar_location=None, sizing_mode='stretch_both')

p1.add_layout(Title(text="Estimated annual emissions from newly-added overseas coal power generation each year*", text_font_style="italic", text_font_size = '10px',), 'above')


afr = p1.vbar(x = 'Year of Commission', bottom = 0, top = 'Africa', source = source, width = 0.9, color = colour[0], legend_label = 'Africa')
p1.add_tools(HoverTool(renderers=[afr], tooltips=[('Region', 'Africa'),('CO2 Emissions in millions of tonnes', '@Africa{0.0}')],mode='mouse',toggleable=False))

eu = p1.vbar(x = 'Year of Commission', bottom = 'Africa', top = 'eu_sum', source = source, width = 0.9, color = colour[1], legend_label = 'EU')
p1.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('CO2 Emissions in millions of tonnes', '@{Europe/Central Asia}{0.0}')],mode='mouse',toggleable=False))

me = p1.vbar(x = 'Year of Commission', bottom = 'eu_sum', top = 'me_sum', source = source, width = 0.9, color = colour[2], legend_label = 'Middle East')
p1.add_tools(HoverTool(renderers=[me], tooltips=[('Region', 'Middle East'),('CO2 Emissions in millions of tonnes', '@{Middle East}{0.0}')],mode='mouse',toggleable=False))

sa = p1.vbar(x = 'Year of Commission', bottom = 'me_sum', top = 'sa_sum', source = source, width = 0.9, color = colour[3], legend_label = 'South Asia')
p1.add_tools(HoverTool(renderers=[sa], tooltips=[('Region', 'South Asia'),('CO2 Emissions in millions of tonnes', '@{South Asia}{0.0}')],mode='mouse',toggleable=False))

sea = p1.vbar(x = 'Year of Commission', bottom = 'sa_sum', top = 'sea_sum', source = source, width = 0.9, color = colour[4], legend_label = 'Southeast Asia')
p1.add_tools(HoverTool(renderers=[sea], tooltips=[('Region', 'Southeast Asia'),('CO2 Emissions in millions of tonnes', '@{Southeast Asia}{0.0}')],mode='mouse',toggleable=False))

source2 = ColumnDataSource(coal_result[-3:])
afr = p1.vbar(x = 'Year of Commission', bottom = 0, top = 'Africa', source = source2, width = 0.9, color = colour[0], legend_label = 'Africa', alpha = 0.5)
p1.add_tools(HoverTool(renderers=[afr], tooltips=[('Region', 'Africa'),('CO2 Emissions in millions of tonnes', '@Africa{0.0} Mt')],mode='mouse',toggleable=False))

eu = p1.vbar(x = 'Year of Commission', bottom = 'Africa', top = 'eu_sum', source = source2, width = 0.9, color = colour[1], legend_label = 'EU', alpha = 0.5)
p1.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('CO2 Emissions in millions of tonnes', '@{Europe/Central Asia}{0.0}')],mode='mouse',toggleable=False))

me = p1.vbar(x = 'Year of Commission', bottom = 'eu_sum', top = 'me_sum', source = source2, width = 0.9, color = colour[2], legend_label = 'Middle East', alpha = 0.5)
p1.add_tools(HoverTool(renderers=[me], tooltips=[('Region', 'Middle East'),('CO2 Emissions in millions of tonnes', '@{Middle East}{0.0}')],mode='mouse',toggleable=False))

sa = p1.vbar(x = 'Year of Commission', bottom = 'me_sum', top = 'sa_sum', source = source2, width = 0.9, color = colour[3], legend_label = 'South Asia', alpha = 0.5)
p1.add_tools(HoverTool(renderers=[sa], tooltips=[('Region', 'South Asia'),('CO2 Emissions in millions of tonnes', '@{South Asia}{0.0}')],mode='mouse',toggleable=False))

sea = p1.vbar(x = 'Year of Commission', bottom = 'sa_sum', top = 'sea_sum', source = source2, width = 0.9, color = colour[4], legend_label = 'Southeast Asia', alpha = 0.5)
p1.add_tools(HoverTool(renderers=[sea], tooltips=[('Region', 'Southeast Asia'),('CO2 Emissions in millions of tonnes', '@{Southeast Asia}{0.0}')],mode='mouse',toggleable=False))


p1.legend.location = "top_left"
p1.add_layout(Span(location= 6,
                            dimension='height', line_color='grey',
                            line_dash='dashed', line_width=2))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p1.add_layout(caption1, 'below')
msg = 'Boston University Global Development Policy Center'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p1.add_layout(caption1, 'below')
msg = '*Pending/future estimates include plants under planning and construction'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p1.add_layout(caption1, 'below')
p1.xaxis.major_label_orientation = 120

p1.toolbar.active_drag = None
#Disable scientific notation on axes
p1.left[0].formatter.use_scientific = False
p1.yaxis[0].formatter = NumeralTickFormatter(format="0,0")


show(p1)
save(p1)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/coal_co2.html'

In [589]:
result

,Coal,Gas,Hydropower,Nuclear,Oil,renewable,coal_sum,gas_sum,hydro_sum,nuclear_sum,oil_sum,R_sum
Year of Commission,,,,,,,,,,,,
2010,0.300,1.848,1.3150,0.000,0.416,0.0570,0.300,2.148,3.4630,3.4630,3.8790,3.9360
2011,5.717,4.948,1.3290,0.000,0.060,0.1900,5.717,10.665,11.9940,11.9940,12.0540,12.2440
2012,2.110,0.970,0.5560,0.325,0.101,0.4020,2.110,3.080,3.6360,3.9610,4.0620,4.4640
2013,3.775,0.420,1.1600,0.000,0.000,1.0210,3.775,4.195,5.3550,5.3550,5.3550,6.3760
2014,7.938,0.371,0.9580,0.000,0.100,0.3980,7.938,8.309,9.2670,9.2670,9.3670,9.7650
2015,5.073,0.537,5.6900,0.000,0.485,1.2300,5.073,5.610,11.3000,11.3000,11.7850,13.0150
2016,2.555,4.149,4.4840,0.340,0.060,2.0010,2.555,6.704,11.1880,11.5280,11.5880,13.5890
2017,7.070,0.480,3.9405,0.340,0.492,2.5060,7.070,7.550,11.4905,11.8305,12.3225,14.8285
2018,2.785,2.112,4.4070,0.000,0.371,0.5770,2.785,4.897,9.3040,9.3040,9.6750,10.2520
2019,3.480,0.000,1.5695,0.000,0.286,2.0653,3.480,3.480,5.0495,5.0495,5.3355,7.4008
2020,3.400,0.000,2.5400,0.000,0.470,0.8510,3.400,3.400,5.9400,5.9400,6.4100,7.2610
2021,6.530,0.000,0.3180,0.000,0.000,0.0000,6.530,6.530,6.8480,6.8480,6.8480,6.8480
2022,2.640,0.000,1.1780,2.200,0.000,0.3700,2.640,2.640,3.8180,6.0180,6.0180,6.3880
2023,1.550,0.000,3.0480,0.000,0.000,0.4990,1.550,1.550,4.5980,4.5980,4.5980,5.0970
2024,0.000,0.000,0.0280,0.000,0.000,0.9550,0.000,0.000,0.0280,0.0280,0.0280,0.9830
2025,0.000,0.000,0.0000,3.540,0.000,0.2670,0.000,0.000,0.0000,3.5400,3.5400,3.8070

In [590]:
#line chart, capacity
output_file('capacity.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Capacity (billions of watts)', title = 'China has pledged to end funding for coal-fired power stations abroad',
            sizing_mode='stretch_both', toolbar_location=None,x_range = (2010,2025),y_range = (0,30))
p.xaxis.ticker = list(range(2010, 2026, 3))

p.add_layout(Title(text="Power generation capacity commitments outside China with Chinese development finance and foreign direct investments*", text_font_style="italic", text_font_size = '9px',), 'above')



source = ColumnDataSource(result[:-5])

p.varea(x = 'Year of Commission', y1 = 0, y2 = 'Coal', source = source, color = colour[5], alpha = 0.8,  legend_label = 'Coal')
coal = p.line(x = 'Year of Commission', y = 'Coal', source = source, line_color = colour[5], line_width = 2)
p.add_tools(HoverTool(renderers=[coal], tooltips=[('Technology', 'Coal'),('Year', '@{Year of Commission}'), ('Capacity', '@Coal{0.0} billions of watts')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'Coal', y2 = 'gas_sum', source = source, color = colour[1], alpha = 0.8,  legend_label = 'Gas')
gas = p.line(x = 'Year of Commission', y = 'gas_sum', source = source, line_color = colour[1], line_width = 3)
p.add_tools(HoverTool(renderers=[gas], tooltips=[('Technology', 'Gas'),('Year', '@{Year of Commission}'),('Capacity', '@Gas{0.0} billions of watts')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'gas_sum', y2 = 'hydro_sum', source = source, color = colour[0], alpha = 0.8,  legend_label = 'Hydropower')
hydro = p.line(x = 'Year of Commission', y = 'hydro_sum', source = source, line_color = colour[0], line_width = 3)
p.add_tools(HoverTool(renderers=[hydro], tooltips=[('Technology', 'Hydropower'),('Year', '@{Year of Commission}'),('Capacity', '@Hydropower{0.0} billions of watts')],mode='mouse',toggleable=False))


p.varea(x = 'Year of Commission', y1 = 'hydro_sum', y2 = 'nuclear_sum', source = source, color = colour[2], alpha = 0.8,  legend_label = 'Nuclear')
nuclear = p.line(x = 'Year of Commission', y = 'nuclear_sum', source = source, line_color = colour[2], line_width = 3)
p.add_tools(HoverTool(renderers=[nuclear], tooltips=[('Technology', 'Nuclear'),('Year', '@{Year of Commission}'),('Capacity', '@Nuclear{0.0} billions of watts')],mode='mouse',toggleable=False))


p.varea(x = 'Year of Commission', y1 = 'nuclear_sum', y2 = 'oil_sum', source = source, color = colour[3], alpha = 0.8,  legend_label = 'Oil')
oil = p.line(x = 'Year of Commission', y = 'oil_sum', source = source, line_color = colour[3], line_width = 3)
p.add_tools(HoverTool(renderers=[oil], tooltips=[('Technology', 'Oil'),('Year', '@{Year of Commission}'),('Capacity', '@Oil{0.0} billions of watts')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'oil_sum', y2 = 'R_sum', source = source, color = colour[4], alpha = 0.8,  legend_label = 'Renewable')
r = p.line(x = 'Year of Commission', y = 'R_sum', source = source, line_color = colour[4], line_width = 3)
p.add_tools(HoverTool(renderers=[r], tooltips=[('Technology', 'Renewable'),('Year', '@{Year of Commission}'),('Capacity', '@renewable{0.0} billions of watts')],mode='mouse',toggleable=False))


source = ColumnDataSource(result[-6:])

p.varea(x = 'Year of Commission', y1 = 0, y2 = 'Coal', source = source, color = colour[5], alpha = 0.4,  legend_label = 'Coal')
coal = p.line(x = 'Year of Commission', y = 'Coal', source = source, line_color = colour[5], line_width = 2, alpha = 0.3)
p.add_tools(HoverTool(renderers=[coal], tooltips=[('Technology', 'Coal'),('Year', '@{Year of Commission}'), ('Capacity', '@Coal{0.0} billions of watts')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'Coal', y2 = 'gas_sum', source = source, color = colour[1], alpha = 0.4,  legend_label = 'Gas')
gas = p.line(x = 'Year of Commission', y = 'gas_sum', source = source, line_color = colour[1], line_width = 3, alpha = 0.3)
p.add_tools(HoverTool(renderers=[gas], tooltips=[('Technology', 'Gas'),('Year', '@{Year of Commission}'),('Capacity', '@Gas{0.0} billions of watts')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'gas_sum', y2 = 'hydro_sum', source = source, color = colour[0], alpha = 0.4,  legend_label = 'Hydropower')
hydro = p.line(x = 'Year of Commission', y = 'hydro_sum', source = source, line_color = colour[0], line_width = 3, alpha = 0.3)
p.add_tools(HoverTool(renderers=[hydro], tooltips=[('Technology', 'Hydropower'),('Year', '@{Year of Commission}'),('Capacity', '@Hydropower{0.0} billions of watts')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'hydro_sum', y2 = 'nuclear_sum', source = source, color = colour[2], alpha = 0.4,  legend_label = 'Nuclear')
nuclear = p.line(x = 'Year of Commission', y = 'nuclear_sum', source = source, line_color = colour[2], line_width = 3, alpha = 0.3)
p.add_tools(HoverTool(renderers=[nuclear], tooltips=[('Technology', 'Nuclear'),('Year', '@{Year of Commission}'),('Capacity', '@Nuclear{0.0} billions of watts')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'nuclear_sum', y2 = 'oil_sum', source = source, color = colour[3], alpha = 0.4,  legend_label = 'Oil')
oil = p.line(x = 'Year of Commission', y = 'oil_sum', source = source, line_color = colour[3], line_width = 3, alpha = 0.3)
p.add_tools(HoverTool(renderers=[oil], tooltips=[('Technology', 'Oil'),('Year', '@{Year of Commission}'),('Capacity', '@Oil Mw')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'oil_sum', y2 = 'R_sum', source = source, color = colour[4], alpha = 0.4,  legend_label = 'Renewable')
r = p.line(x = 'Year of Commission', y = 'R_sum', source = source, line_color = colour[4], line_width = 3, alpha = 0.3)
p.add_tools(HoverTool(renderers=[r], tooltips=[('Technology', 'Renewable'),('Year', '@{Year of Commission}'),('Capacity', '@renewable{0}{0.0} billions of watts')],mode='mouse',toggleable=False))


p.add_layout(Span(location= 2020,
                            dimension='height', line_color='grey',
                            line_dash='dashed', line_width=2))

p.legend.location = 'top_left'

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'Boston University Global Development Policy Centre'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '*Future capacity only includes plants under construction'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

p.xaxis.major_label_orientation = 120

p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/capacity.html'

In [591]:
coal_result.head()

,Africa,Europe/Central Asia,Middle East,South Asia,Southeast Asia,afr_sum,eu_sum,me_sum,sa_sum,sea_sum
Year of Commission,,,,,,,,,,
2015,5.353,0.000,0.0,5.786,18.262,5.353,5.353,5.353,11.139,29.401
2016,0.000,4.218,0.0,0.000,9.097,0.000,4.218,4.218,4.218,13.315
2017,18.401,1.512,0.0,13.308,6.955,18.401,19.913,19.913,33.221,40.176
2018,0.000,0.000,0.0,0.000,14.037,0.000,0.000,0.000,0.000,14.037
2019,16.059,0.000,0.0,16.634,6.351,16.059,16.059,16.059,32.693,39.044

In [592]:
"""
#line chart, capacity
output_file('coal_co2_2.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Estimated annual CO2 emission from power generation (1000 tonnes)', 
            sizing_mode='stretch_both', toolbar_location=None,x_range = (2015,2023),y_range = (0,80000))
p.xaxis.ticker = list(range(2010, 2026))

source = ColumnDataSource(coal_result[:-3])

p.varea(x = 'Year of Commission', y1 = 0, y2 = 'afr_sum', source = source, color = colour[5], alpha = 0.8,  legend_label = 'Africa')
afr = p.line(x = 'Year of Commission', y = 'afr_sum', source = source, line_color = colour[5], line_width = 2)
p.add_tools(HoverTool(renderers=[afr], tooltips=[('Region', 'Africa'),('Year', '@{Year of Commission}'), ('CO2 emissions', '@afr_sum{0,0} Kt')],mode='mouse',toggleable=False))


p.varea(x = 'Year of Commission', y1 = 'afr_sum', y2 = 'eu_sum', source = source, color = colour[1], alpha = 0.8,  legend_label = 'Europe and Central Asia')
eu = p.line(x = 'Year of Commission', y = 'eu_sum', source = source, line_color = colour[1], line_width = 3)
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'Europe'),('Year', '@{Year of Commission}'),('CO2 emissions', '{@Europe/Central Asia}{0,0} Kt')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'eu_sum', y2 = 'me_sum', source = source, color = colour[0], alpha = 0.8,  legend_label = 'Middle East')
me = p.line(x = 'Year of Commission', y = 'me_sum', source = source, line_color = colour[0], line_width = 3)
p.add_tools(HoverTool(renderers=[me], tooltips=[('Region', 'Middle East'),('Year', '@{Year of Commission}'),('CO2 emissions', '@{Middle East}{0,0} Kt')],mode='mouse',toggleable=False))


p.varea(x = 'Year of Commission', y1 = 'me_sum', y2 = 'sa_sum', source = source, color = colour[2], alpha = 0.8,  legend_label = 'South Asia')
sa = p.line(x = 'Year of Commission', y = 'sa_sum', source = source, line_color = colour[2], line_width = 3)
p.add_tools(HoverTool(renderers=[sa], tooltips=[('Region', 'South Asia'),('Year', '@{Year of Commission}'),('CO2 emissions', '@{South Asia}{0,0} Kt')],mode='mouse',toggleable=False))


p.varea(x = 'Year of Commission', y1 = 'sa_sum', y2 = 'sea_sum', source = source, color = colour[3], alpha = 0.8,  legend_label = 'Southeast Asia')
sea = p.line(x = 'Year of Commission', y = 'sea_sum', source = source, line_color = colour[3], line_width = 3)
p.add_tools(HoverTool(renderers=[sea], tooltips=[('Region', 'Southeast Asia'),('Year', '@{Year of Commission}'),('CO2 emissions', '{Southeast Asia}{0,0} Kt')],mode='mouse',toggleable=False))


source = ColumnDataSource(result[-6:])

p.varea(x = 'Year of Commission', y1 = 0, y2 = 'Coal', source = source, color = colour[5], alpha = 0.4,  legend_label = 'Coal')
coal = p.line(x = 'Year of Commission', y = 'Coal', source = source, line_color = colour[5], line_width = 2, alpha = 0.3)
p.add_tools(HoverTool(renderers=[coal], tooltips=[('Technology', 'Coal'),('Year', '@{Year of Commission}'), ('Capacity', '@Coal Mw')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'Coal', y2 = 'gas_sum', source = source, color = colour[1], alpha = 0.4,  legend_label = 'Gas')
gas = p.line(x = 'Year of Commission', y = 'gas_sum', source = source, line_color = colour[1], line_width = 3, alpha = 0.3)
p.add_tools(HoverTool(renderers=[gas], tooltips=[('Technology', 'Gas'),('Year', '@{Year of Commission}'),('Capacity', '@Gas Mw')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'gas_sum', y2 = 'hydro_sum', source = source, color = colour[0], alpha = 0.4,  legend_label = 'Hydropower')
hydro = p.line(x = 'Year of Commission', y = 'hydro_sum', source = source, line_color = colour[0], line_width = 3, alpha = 0.3)
p.add_tools(HoverTool(renderers=[hydro], tooltips=[('Technology', 'Hydropower'),('Year', '@{Year of Commission}'),('Capacity', '@Hydropower Mw')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'hydro_sum', y2 = 'nuclear_sum', source = source, color = colour[2], alpha = 0.4,  legend_label = 'Nuclear')
nuclear = p.line(x = 'Year of Commission', y = 'nuclear_sum', source = source, line_color = colour[2], line_width = 3, alpha = 0.3)
p.add_tools(HoverTool(renderers=[nuclear], tooltips=[('Technology', 'Nuclear'),('Year', '@{Year of Commission}'),('Capacity', '@Nuclear Mw')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'nuclear_sum', y2 = 'oil_sum', source = source, color = colour[3], alpha = 0.4,  legend_label = 'Oil')
oil = p.line(x = 'Year of Commission', y = 'oil_sum', source = source, line_color = colour[3], line_width = 3, alpha = 0.3)
p.add_tools(HoverTool(renderers=[oil], tooltips=[('Technology', 'Oil'),('Year', '@{Year of Commission}'),('Capacity', '@Oil Mw')],mode='mouse',toggleable=False))

p.varea(x = 'Year of Commission', y1 = 'oil_sum', y2 = 'R_sum', source = source, color = colour[4], alpha = 0.4,  legend_label = 'Renewable')
r = p.line(x = 'Year of Commission', y = 'R_sum', source = source, line_color = colour[4], line_width = 3, alpha = 0.3)
p.add_tools(HoverTool(renderers=[r], tooltips=[('Technology', 'Renewable'),('Year', '@{Year of Commission}'),('Capacity', '@renewable{0} Mw')],mode='mouse',toggleable=False))


p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")
p.add_layout(Span(location= 2020,
                            dimension='height', line_color='grey',
                            line_dash='dashed', line_width=2))

p.legend.location = 'top_left'

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'Boston University Global Development Policy Centre'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.xaxis.major_label_orientation = 120

p.toolbar.active_drag = None

show(p)
save(p)
"""

'\n#line chart, capacity\noutput_file(\'coal_co2_2.html\')\n\n#create figure\np = figure(x_axis_label=\'Year\', y_axis_label=\'Estimated annual CO2 emission from power generation (1000 tonnes)\', \n            sizing_mode=\'stretch_both\', toolbar_location=None,x_range = (2015,2023),y_range = (0,80000))\np.xaxis.ticker = list(range(2010, 2026))\n\nsource = ColumnDataSource(coal_result[:-3])\n\np.varea(x = \'Year of Commission\', y1 = 0, y2 = \'afr_sum\', source = source, color = colour[5], alpha = 0.8,  legend_label = \'Africa\')\nafr = p.line(x = \'Year of Commission\', y = \'afr_sum\', source = source, line_color = colour[5], line_width = 2)\np.add_tools(HoverTool(renderers=[afr], tooltips=[(\'Region\', \'Africa\'),(\'Year\', \'@{Year of Commission}\'), (\'CO2 emissions\', \'@afr_sum{0,0} Kt\')],mode=\'mouse\',toggleable=False))\n\n\np.varea(x = \'Year of Commission\', y1 = \'afr_sum\', y2 = \'eu_sum\', source = source, color = colour[1], alpha = 0.8,  legend_label = \'Europe and Central Asia\')\neu = p.line(x = \'Year of Commission\', y = \'eu_sum\', source = source, line_color = colour[1], line_width = 3)\np.add_tools(HoverTool(renderers=[eu], tooltips=[(\'Region\', \'Europe\'),(\'Year\', \'@{Year of Commission}\'),(\'CO2 emissions\', \'{@Europe/Central Asia}{0,0} Kt\')],mode=\'mouse\',toggleable=False))\n\np.varea(x = \'Year of Commission\', y1 = \'eu_sum\', y2 = \'me_sum\', source = source, color = colour[0], alpha = 0.8,  legend_label = \'Middle East\')\nme = p.line(x = \'Year of Commission\', y = \'me_sum\', source = source, line_color = colour[0], line_width = 3)\np.add_tools(HoverTool(renderers=[me], tooltips=[(\'Region\', \'Middle East\'),(\'Year\', \'@{Year of Commission}\'),(\'CO2 emissions\', \'@{Middle East}{0,0} Kt\')],mode=\'mouse\',toggleable=False))\n\n\np.varea(x = \'Year of Commission\', y1 = \'me_sum\', y2 = \'sa_sum\', source = source, color = colour[2], alpha = 0.8,  legend_label = \'South Asia\')\nsa = p.line(x = \'Year of Commission\', y = \'sa_sum\', source = source, line_color = colour[2], line_width = 3)\np.add_tools(HoverTool(renderers=[sa], tooltips=[(\'Region\', \'South Asia\'),(\'Year\', \'@{Year of Commission}\'),(\'CO2 emissions\', \'@{South Asia}{0,0} Kt\')],mode=\'mouse\',toggleable=False))\n\n\np.varea(x = \'Year of Commission\', y1 = \'sa_sum\', y2 = \'sea_sum\', source = source, color = colour[3], alpha = 0.8,  legend_label = \'Southeast Asia\')\nsea = p.line(x = \'Year of Commission\', y = \'sea_sum\', source = source, line_color = colour[3], line_width = 3)\np.add_tools(HoverTool(renderers=[sea], tooltips=[(\'Region\', \'Southeast Asia\'),(\'Year\', \'@{Year of Commission}\'),(\'CO2 emissions\', \'{Southeast Asia}{0,0} Kt\')],mode=\'mouse\',toggleable=False))\n\n\nsource = ColumnDataSource(result[-6:])\n\np.varea(x = \'Year of Commission\', y1 = 0, y2 = \'Coal\', source = source, color = colour[5], alpha = 0.4,  legend_label = \'Coal\')\ncoal = p.line(x = \'Year of Commission\', y = \'Coal\', source = source, line_color = colour[5], line_width = 2, alpha = 0.3)\np.add_tools(HoverTool(renderers=[coal], tooltips=[(\'Technology\', \'Coal\'),(\'Year\', \'@{Year of Commission}\'), (\'Capacity\', \'@Coal Mw\')],mode=\'mouse\',toggleable=False))\n\np.varea(x = \'Year of Commission\', y1 = \'Coal\', y2 = \'gas_sum\', source = source, color = colour[1], alpha = 0.4,  legend_label = \'Gas\')\ngas = p.line(x = \'Year of Commission\', y = \'gas_sum\', source = source, line_color = colour[1], line_width = 3, alpha = 0.3)\np.add_tools(HoverTool(renderers=[gas], tooltips=[(\'Technology\', \'Gas\'),(\'Year\', \'@{Year of Commission}\'),(\'Capacity\', \'@Gas Mw\')],mode=\'mouse\',toggleable=False))\n\np.varea(x = \'Year of Commission\', y1 = \'gas_sum\', y2 = \'hydro_sum\', source = source, color = colour[0], alpha = 0.4,  legend_label = \'Hydropower\')\nhydro = p.line(x = \'Year of Commission\', y = \'hydro_sum\', source = source, line_color = colour[0], line_width = 3, alpha = 0.3)\np.add_tools(HoverTool(renderers=[hydro], tooltips=[(\'Technology\', \'Hydropower\'),(\'Year\', \'@{Year of Commission}\'),(\'Capacity\', \'@Hydropower Mw\')],mode=\'mouse\',toggleable=False))\n\np.varea(x = \'Year of Commission\', y1 = \'hydro_sum\', y2 = \'nuclear_sum\', source = source, color = colour[2], alpha = 0.4,  legend_label = \'Nuclear\')\nnuclear = p.line(x = \'Year of Commission\', y = \'nuclear_sum\', source = source, line_color = colour[2], line_width = 3, alpha = 0.3)\np.add_tools(HoverTool(renderers=[nuclear], tooltips=[(\'Technology\', \'Nuclear\'),(\'Year\', \'@{Year of Commission}\'),(\'Capacity\', \'@Nuclear Mw\')],mode=\'mouse\',toggleable=False))\n\np.varea(x = \'Year of Commission\', y1 = \'nuclear_sum\', y2 = \'oil_sum\', source = source, color = colour[3], alpha = 0.4,  legend_label = \'Oil\')\noil = p.line(x = \'Year of Commission\', y = \'oil_sum\', source = source, line_color = colour[3], line_width = 3, alpha = 0.3)\np.add_tools(HoverTool(renderers=[oil], tooltips=[(\'Technology\', \'Oil\'),(\'Year\', \'@{Year of Commission}\'),(\'Capacity\', \'@Oil Mw\')],mode=\'mouse\',toggleable=False))\n\np.varea(x = \'Year of Commission\', y1 = \'oil_sum\', y2 = \'R_sum\', source = source, color = colour[4], alpha = 0.4,  legend_label = \'Renewable\')\nr = p.line(x = \'Year of Commission\', y = \'R_sum\', source = source, line_color = colour[4], line_width = 3, alpha = 0.3)\np.add_tools(HoverTool(renderers=[r], tooltips=[(\'Technology\', \'Renewable\'),(\'Year\', \'@{Year of Commission}\'),(\'Capacity\', \'@renewable{0} Mw\')],mode=\'mouse\',toggleable=False))\n\n\np.yaxis[0].formatter = NumeralTickFormatter(format="0,0")\np.add_layout(Span(location= 2020,\n                            dimension=\'height\', line_color=\'grey\',\n                            line_dash=\'dashed\', line_width=2))\n\np.legend.location = \'top_left\'\n\n#add data sources below charts\nlabel_opts = dict(x = 0, y = 0, x_units = \'screen\', y_units =\'screen\')\nmsg = \'Data source:\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np.add_layout(caption1, \'below\')\nmsg = \'Boston University Global Development Policy Centre\'\ncaption1 = Label(text=msg, **label_opts, text_font_size = \'8pt\', text_font_style = \'italic\')\np.add_layout(caption1, \'below\')\np.xaxis.major_label_orientation = 120\n\np.toolbar.active_drag = None\n\nshow(p)\nsave(p)\n'

# India

In [593]:
india_kyoto.head()

,year,IPC1,IPC2,IPC4,IPC5,IPCMAG,total,pop,pc,total_
210,1960,148.0,38.4,23.7,3.90,281.0,495000000.0,450547675.0,1.098663,0.49500
211,1961,158.0,42.9,22.9,3.92,283.0,510720000.0,459642166.0,1.111125,0.51072
212,1962,171.0,48.2,22.1,3.94,283.0,528240000.0,469077191.0,1.126126,0.52824
213,1963,181.0,53.7,21.3,3.96,283.0,542960000.0,478825602.0,1.133941,0.54296
214,1964,176.0,54.7,20.4,3.98,286.0,541080000.0,488848139.0,1.106847,0.54108

In [594]:
india_proj.head()

  index   paris  minimum  maximum     avg
0  2020  3.0105    2.923    2.923  2.9230
1  2021  2.8796    3.054    3.054  3.0540
2  2022  2.7487    3.135    3.170  3.1525
3  2023  2.6179    3.216    3.287  3.2515
4  2024  2.4870    3.297    3.403  3.3500

In [595]:
#load data
coal = pd.read_csv('electricity_coal.csv', sep = ';')
coal = coal[(coal['Country Name'].isin(['China', 'India']))]

urban = pd.read_csv('urban_electricity.csv', sep = ';')
urban = urban[(urban['Country Name'].isin(['China', 'India']))]

rural = pd.read_csv('rural_electricity.csv', sep = ';')
rural = rural[(rural['Country Name'].isin(['China', 'India']))]

electricity = pd.read_csv('el.csv', sep = ';')
#electricity = electricity[(electricity['Country Name'].isin(['China', 'India']))]
electricity = electricity[(electricity['Country Name'].isin(['China', 'India']))]

In [596]:
electricity

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
40,China,CHN,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.964874,99.997009,100.000000,100.0,100.000000,100.000000,100.000000,100.000000,NaN,NaN
109,India,IND,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,79.900000,80.738045,83.585213,88.0,89.534882,92.456833,95.193298,97.815285,NaN,NaN

In [597]:
#alternative coal data
alt_coal = pd.read_csv('share-electricity-coal.csv')
china_coal = alt_coal[(alt_coal['Entity'].isin(['China']))]
india_coal = alt_coal[(alt_coal['Entity'].isin(['India']))]

## India total

In [598]:
# visualisation of india total ghg emission vs world
#data source pik potsdam
output_file('india_total.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Total greenhouse gas emissions (billions of tonnes CO2e)', title = 'India is now the world\'s third largest greenhouse gas emitter',
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019), y_range = (0,50))

p.add_layout(Title(text="Total greenhouse gas emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')



#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


third = p.line(x='year',y= 'total_',source=india_kyoto, color = colour[1],line_width = 7, legend_label="India")
p.add_tools(HoverTool(renderers=[third], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse', toggleable=False))

fourth = p.line(x='year',y= 'total_',source=china_kyoto, color = colour[2],line_width = 4, alpha = 0.7, legend_label="China")
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse', toggleable=False))

first = p.line(x='year',y= 'total_',source=us_kyoto, color = colour[0],line_width = 4, alpha = 0.7, legend_label="US")
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse', toggleable=False))

eu = p.line(x='year', y= 'total_',source=eu_kyoto, color = colour[3], line_width = 4, alpha = 0.7, legend_label="EU")
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse',toggleable=False))

second = p.varea(x='year',y1 = 0, y2= 'total_',source=world_kyoto, color = colour[7], legend_label="World", alpha = 0.2, level ='underlay')
line = p.line(x ='year', y = 'total_', source = world_kyoto, color = colour[7], alpha = 0.1)
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year',"@year"),('Emissions',"@total_{0.00} Gt")],mode='mouse',toggleable=False))

p.yaxis[0].formatter = NumeralTickFormatter(format="0,000 a")

p.xaxis.major_label_orientation = 120

p.legend.location = 'top_left'

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'The PRIMAP-hist national historical emissions time series'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/india_total.html'

In [599]:
# visualisation of india metric tonnes co2 emission vs world average
#data source https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=usa&entity=kyotoghgar4


output_file('india_per_capita.html')

#create figure
p = figure(x_axis_label='Year', y_axis_label='Annual greenhouse gas emissions per capita (tonnes CO2e)', title = 'India\'s per capita emissions are less than half the world average',
            sizing_mode='stretch_both', toolbar_location=None,x_range = (1960, 2019),y_range = (0,45))


p.add_layout(Title(text="Per capita emissions in different countries/regions (excluding land-use)", text_font_style="italic", text_font_size = '10px',), 'above')

#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
p.below[0].formatter.use_scientific = False


fifth = p.line(x='year',y= 'pc',source=india_kyoto, color = colour[1],line_width = 7, legend_label="India")
p.add_tools(HoverTool(renderers=[fifth], tooltips=[('Country', 'India'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


second = p.line(x='year',y= 'pc',source=world_kyoto, color = colour[7],line_width = 4, line_dash = 'dashed', legend_label="World", alpha = 0.5)
p.add_tools(HoverTool(renderers=[second], tooltips=[('Region', 'World'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

first = p.line(x='year',y= 'pc',source=us_kyoto, color = colour[0],line_width = 4, legend_label="US", alpha = 0.5)
p.add_tools(HoverTool(renderers=[first], tooltips=[('Country', 'US'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))


third = p.line(x='year',y= 'pc',source=eu_kyoto, color = colour[3],line_width = 4, legend_label="EU", alpha = 0.5)
p.add_tools(HoverTool(renderers=[third], tooltips=[('Region', 'EU'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse',toggleable=False))

fourth = p.line(x='year',y= 'pc',source=china_kyoto, color = colour[2],line_width = 4,legend_label="China", alpha = 0.5)
p.add_tools(HoverTool(renderers=[fourth], tooltips=[('Country', 'China'),('Year',"@year"),('Emissions',"@pc{0.0} t")],mode='mouse', toggleable=False))



p.xaxis.major_label_orientation = 120

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source:The PRIMAP-hist national historical'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'emissions time series and the World Bank'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/india_per_capita.html'

In [600]:
# visualisation of projected  tonnes co2 emission Indonesia
#https://climateactiontracker.org/countries/indonesia/
output_file('india_projection.html')
source = ColumnDataSource(india_proj)

p = figure(x_axis_label='Year', y_axis_label='India projected emissions (billions of tonnes CO2)', x_range = (2019.9,2030.1), y_range = (0,6),
            title = '...', sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Projected CO2 emissions in India based on current policies", text_font_style="italic", text_font_size = '10px',), 'above')



proj = p.varea(x='index',
        y1='minimum',
        y2='maximum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Projected CO2 emissions')

p.legend.location = 'bottom_left'


#add average line
line = p.line(x ='index', y = 'avg', source = source, color= 'black', line_width = 1)
p.scatter(x='index', y ='avg', source = source, size = 3, fill_color = 'black', line_color = 'black')
p.add_tools(HoverTool(renderers=[line], tooltips=[('Year', '@index'),('Average projection',"@avg{0} Mt")],mode='mouse'))

#add paris scatter
paris = p.scatter(x = 'index', y = 'paris', source = source, size = 12, fill_color= colour[2], line_color = colour[2],legend_label = '1.5C Paris compatible pathway')
p.add_tools(HoverTool(renderers=[paris], tooltips=[('1.5C Compatible',"@paris{0} mt")],mode='mouse'))

p.segment('index', 'paris', 'index', 'avg', source = source, line_width=2, line_color='black', alpha = 0.3, line_dash = [1,5] )

un = p.scatter(x = 2030, y=[5.265,5.427], size = 10, legend_label ='UN unconditional climate pledge')

#add a patch renderer with an alpha and line width
p.patch([2030, 2030], [5.265,5.427], line_width=5, alpha = 0.5)
p.add_tools(HoverTool(renderers = [un], tooltips =[('Upper', '5.3 Gt'), ('Lower', '5.4 Gt')]))

un1 = p.scatter(x = 2030, y=[4.686,4.802], size = 10, color = colour[9], legend_label ='UN conditional climate pledge')

#add a patch renderer with an alpha and line width
p.patch([2030, 2030], [4.686,4.802], color = colour[9], line_width=5, alpha = 0.5)
p.add_tools(HoverTool(renderers = [un1], tooltips =[('Upper', '4.7 Gt'), ('Lower', '4.8 Gt')]))

p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Climate action tracker, September 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = '* Using a global least-cost-solution model'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/india_projection.html'

In [601]:
#prep dataset
rural = pd.pivot_table(rural, columns = ['Country Name']).reset_index()
urban = pd.pivot_table(urban, columns = ['Country Name']).reset_index()
coal = pd.pivot_table(coal, columns = ['Country Name']).reset_index()
el = pd.pivot_table(electricity, columns = ['Country Name']).reset_index()

In [602]:
urban = urban.iloc[:-1]
rural = rural.iloc[:-1]
el = el.iloc[:-1]

urban['index'] = pd.to_numeric(urban['index'])
rural['index'] = pd.to_numeric(rural['index'])
el['index'] = pd.to_numeric(el['index'])

In [603]:
india_coal = india_coal[india_coal['Year'] >= 2000]
china_coal = china_coal[china_coal['Year'] >= 2000]

india_coal = india_coal[india_coal['Year'] < 2019]
china_coal = china_coal[china_coal['Year'] < 2019]


urban= urban[urban['index'] >= 2000]
rural = rural[rural['index'] >=2000]
el = el[el['index'] >=2000]

In [608]:
el

Country Name  index       China      India
40             2000   96.930870  59.341045
41             2001   97.213219  55.800000
42             2002   97.487282  62.300000
43             2003   97.751877  64.023132
44             2004   98.005836  64.400000
45             2005   98.248131  67.093437
46             2006   98.481293  67.900000
47             2007   98.711403  70.130760
48             2008   98.944702  71.651085
49             2009   99.187416  75.000000
50             2010   99.700000  76.300000
51             2011   99.857224  67.600000
52             2012   99.964874  79.900000
53             2013   99.997009  80.738045
54             2014  100.000000  83.585213
55             2015  100.000000  88.000000
56             2016  100.000000  89.534882
57             2017  100.000000  92.456833
58             2018  100.000000  95.193298
59             2019  100.000000  97.815285
60             2020         NaN        NaN

In [612]:
output_file('india_coal_comparison.html')
from bokeh.transform import dodge

p = figure(x_axis_label='Year', y_axis_label='Percentage', x_range = (1999, 2019), y_range = (40,105),
            title = 'Almost all of India\'s population now has access to electricity' ,sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Access to electricity and coal as percentage of electricity production", text_font_style="italic", text_font_size = '10px',), 'above')


p.xaxis.ticker = list(range(2000, 2019,2))

#coal bars
i_coal = p.vbar(x =dodge('Year', -0.25, range=p.x_range), top = 'Coal (% electricity)', alpha = 0.7, source = india_coal, color= colour[1], width = 0.4, legend_label = 'India electricity from coal % of total')
p.add_tools(HoverTool(renderers=[i_coal], tooltips=[('Country', 'India'),('Year', '@Year'),('Percentage',"@{Coal (% electricity)}{0.0}%")],mode='mouse'))


c_coal = p.vbar(x = dodge('Year', 0.25, range = p.x_range), top = 'Coal (% electricity)', alpha = 0.7, source = china_coal, color= colour[2], width = 0.4, legend_label = 'China electricity from coal % of total')
p.add_tools(HoverTool(renderers=[c_coal], tooltips=[('Country', 'China'),('Year', '@Year'),('Percentage',"@{Coal (% electricity)}{0.0}%")],mode='mouse'))

#electricity line
i_urb = p.line(x ='index', y = 'India', source = el, color= 'black', line_width = 2, line_dash ='dotted',  legend_label = 'India access to electricity % of population')
p.add_tools(HoverTool(renderers=[i_urb], tooltips=[('Electricity', '% of population'),('Year', '@index'),('Percentage',"@India{0.0}%")],mode='mouse'))

c_urb = p.line(x ='index', y = 'China', source = el, color= 'blue', line_width = 2, line_dash = 'dotted',  legend_label = 'China access to electricity % of population')
p.add_tools(HoverTool(renderers=[c_urb], tooltips=[('Electricity', '% of population'),('Year', '@index'),('Percentage',"@China{0.0}%")],mode='mouse'))


"""
#urban electricty line
i_urb = p.line(x ='index', y = 'India', source = urban, color= 'black', line_width = 2, line_dash ='dotted',  legend_label = 'India access to electricity % of urban population')
p.add_tools(HoverTool(renderers=[i_urb], tooltips=[('Area', 'Urban'),('Year', '@index'),('Percentage',"@India{0.0}%")],mode='mouse'))

c_urb = p.line(x ='index', y = 'China', source = urban, color= 'blue', line_width = 2, line_dash = 'dotted',  legend_label = 'China access to electricity % of urban population')
p.add_tools(HoverTool(renderers=[c_urb], tooltips=[('Area', 'Urban'),('Year', '@index'),('Percentage',"@China{0.0}%")],mode='mouse'))

#rural electricty line
i_rur = p.line(x ='index', y = 'India', source = rural, color= 'black', line_width = 2, line_dash ='dashed',  legend_label = 'India access to electricity % of rural population')
p.add_tools(HoverTool(renderers=[i_rur], tooltips=[('Area', 'Rural'),('Year', '@index'),('Percentage',"@India{0.0}%")],mode='mouse'))

c_rur = p.line(x ='index', y = 'China', source = rural, color= 'blue', line_width = 2, line_dash = 'dashed',  legend_label = 'China access to electricity % of rural population')
p.add_tools(HoverTool(renderers=[c_rur], tooltips=[('Area', 'Rural'),('Year', '@index'),('Percentage',"@China{0.0}%")],mode='mouse'))

"""

p.yaxis[0].formatter = PrintfTickFormatter(format='%0.0f%%')

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: World Bank, Our World in Data'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None

p.legend.location = 'bottom_right'
show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/india_coal_comparison.html'

In [460]:
#prepare data for coal/gas chart

gas_cons = pd.read_csv('energy-consumption-by-source-and-region.csv', sep = ';')
gas_cons = gas_cons[gas_cons.Entity == 'India']
gas_cons = gas_cons.iloc[:,2:]
gas_cons = gas_cons.set_index('Year')
gas_cons['Renewables'] = gas_cons['Solar']+gas_cons['Hydro']+ gas_cons['Wind']+ gas_cons['Geo Biomass']+ gas_cons['Biofuels']

coal = gas_cons.iloc[:,2]


del gas_cons['Coal']
gas_cons.insert(loc=0, column='Coal', value=coal)

#prepare df with independent lines, + cumulative
temp = gas_cons.drop(['Solar', 'Hydro', 'Wind', 'Geo Biomass', 'Biofuels'], axis = 1)

cum_df = temp.cumsum(axis = 1)

cum_df.columns = ['Coal_sum', 'Oil_sum', 'Gas_sum', 'Nuclear_sum', 'R_sum']

sum_df = temp + cum_df

result_i= pd.concat([temp, cum_df], axis=1)
#result_i = result_i*1000000000

In [461]:
result_i

,Coal,Oil,Gas,Nuclear,Renewables,Coal_sum,Oil_sum,Gas_sum,Nuclear_sum,R_sum
Year,,,,,,,,,,
1965,413.407682,146.995250,2.372522,0.000000,53.241536,413.407682,560.402932,562.775454,562.775454,616.016990
1966,412.415691,164.149813,2.663272,0.000000,55.598552,412.415691,576.565504,579.228776,579.228776,634.827328
1967,419.285587,169.360364,3.558783,0.000000,62.215381,419.285587,588.645950,592.204733,592.204733,654.420114
1968,433.825064,189.771047,3.954203,0.000000,71.803031,433.825064,623.596111,627.550315,627.550315,699.353346
1969,460.841576,227.929016,4.745044,2.013284,79.721129,460.841576,688.770592,693.515636,695.528920,775.250049
1970,436.809226,226.891629,6.328471,3.633732,84.545645,436.809226,663.700855,670.029326,673.663058,758.208703
1971,442.872556,243.332658,6.706224,2.700747,92.733818,442.872556,686.205214,692.911438,695.612185,788.346002
1972,467.683461,262.383467,7.355912,2.565709,90.008519,467.683461,730.066928,737.422840,739.988550,829.997068
1973,461.449776,276.959297,7.336662,5.426045,95.851952,461.449776,738.409073,745.745735,751.171781,847.023733
1974,520.856519,271.543178,8.303975,4.996381,92.230497,520.856519,792.399697,800.703673,805.700054,897.930550
1975,559.906650,278.093057,10.630821,5.953919,110.190461,559.906650,837.999707,848.630528,854.584447,964.774908
1976,583.035299,293.258928,12.914354,7.377949,115.272776,583.035299,876.294227,889.208581,896.586530,1011.859305
1977,610.346656,315.044288,13.792636,5.143695,125.768859,610.346656,925.390943,939.183579,944.327274,1070.096133
1978,590.664585,342.374790,15.404825,6.285374,156.041773,590.664585,933.039375,948.444200,954.729574,1110.771347
1979,627.493385,369.473051,19.158578,6.518620,150.468414,627.493385,996.966436,1016.125014,1022.643634,1173.112048
1980,659.565510,376.816478,11.331040,6.800971,154.003937,659.565510,1036.381988,1047.713029,1054.514000,1208.517937
1981,742.143011,405.655609,19.781797,6.850075,164.119461,742.143011,1147.798620,1167.580417,1174.430492,1338.549953
1982,733.904620,422.656676,25.934583,5.990747,138.499196,733.904620,1156.561296,1182.495879,1188.486626,1326.985822
1983,779.048674,444.353300,30.857775,8.544180,133.453711,779.048674,1223.401975,1254.259749,1262.803930,1396.257640
1984,818.311485,477.067413,35.340622,11.220375,149.118041,818.311485,1295.378898,1330.719520,1341.939894,1491.057935
1985,857.397765,517.636209,43.228316,12.521643,143.925242,857.397765,1375.033975,1418.262290,1430.783934,1574.709176
1986,921.240791,544.259897,60.400292,13.945673,146.024458,921.240791,1465.500687,1525.900979,1539.846653,1685.871111
1987,1011.630644,561.767229,69.577063,14.780450,136.007144,1011.630644,1573.397873,1642.974936,1657.755386,1793.762529
1988,1085.558218,616.501285,81.504950,16.879666,151.708302,1085.558218,1702.059504,1783.564454,1800.444120,1952.152423
1989,1179.942074,667.773179,96.904674,11.171270,176.027298,1179.942074,1847.715253,1944.619927,1955.791197,2131.818495
1990,1276.026165,693.537327,115.927443,17.763547,184.625023,1276.026165,1969.563493,2085.490935,2103.254482,2287.879505
1991,1357.878783,704.798044,129.108121,15.038248,205.908125,1357.878783,2062.676827,2191.784948,2206.823196,2412.731321
1992,1438.257713,741.826939,144.347010,17.788099,195.190740,1438.257713,2180.084652,2324.431663,2342.219762,2537.410502
1993,1489.626519,749.628296,146.670969,17.297054,197.442704,1489.626519,2239.254815,2385.925784,2403.222838,2600.665542
1994,1537.288311,805.070078,158.569307,13.736979,224.399278,1537.288311,2342.358390,2500.927696,2514.664676,2739.063953
1995,1631.614708,897.839536,180.778435,21.151756,213.839470,1631.614708,2529.454245,2710.232679,2731.384435,2945.223906
1996,1678.483870,969.208076,197.317374,23.336906,196.383862,1678.483870,2647.691946,2845.009320,2868.346226,3064.730088
1997,1755.924892,1036.261307,214.526503,27.977280,200.518869,1755.924892,2792.186199,3006.712702,3034.689981,3235.208850
1998,1814.341748,1109.913155,235.428940,31.586459,238.917730,1814.341748,2924.254904,3159.683843,3191.270302,3430.188032
1999,1797.316330,1211.432559,241.233878,35.355228,237.187948,1797.316330,3008.748889,3249.982767,3285.337995,3522.525943
2000,1911.792969,1273.522222,253.627134,43.801199,223.247948,1911.792969,3185.315190,3438.942324,3482.743524,3705.991472
2001,1927.726778,1280.543483,254.277688,52.127439,210.592874,1927.726778,3208.270261,3462.547949,3514.675388,3725.268262
2002,2013.457757,1364.884619,265.544337,53.063493,199.877247,2013.457757,3378.342376,3643.886714,3696.950207,3896.827454
2003,2108.819539,1400.510234,284.269212,49.424371,203.652365,2108.819539,3509.329772,3793.598985,3843.023356,4046.675721
2004,2243.530317,1437.841128,306.691630,57.540173,295.973022,2243.530317,3681.371445,3988.063075,4045.603249,4341.576271
2005,2456.115316,1464.246185,343.256650,47.683424,289.509644,2456.115316,3920.361501,4263.618151,4311.301575,4600.811219
2006,2550.428178,1538.393113,358.772162,47.128956,341.440686,2550.428178,4088.821291,4447.593453,4494.722409,4836.163095
2007,2791.572755,1653.978932,388.102919,47.365704,377.069716,2791.572755,4445.551687,4833.654606,4881.020309,5258.090026
2008,3015.320292,1734.109214,399.876980,40.205375,367.386042,3015.320292,4749.429506,5149.306485,5189.511861,5556.897903
2009,3266.075293,1825.098716,491.081241,44.116557,352.617811,3266.075293,5091.174009,5582.255250,5626.371807,5978.989618
2010,3377.142920,1866.313629,589.616693,60.183464,371.945269,3377.142920,5243.456549,5833.073241,5893.256705,6265.201974
2011,3542.843795,1953.502909,602.859253,83.506477,450.751564,3542.843795,5496.346705,6099.205958,6182.712435,6633.463998
2012,3837.760634,2069.575945,556.991364,85.359927,426.265761,3837.760634,5907.336579,6464.327943,6549.687871,6975.953632
2013,4102.856007,2083.451820,490.193410,85.277189,481.823298,4102.856007,6186.307827,6676.501238,6761.778426,7243.601724
2014,4507.140525,2144.122795,485.016056,88.272163,514.808374,4507.140525,6651.263320,7136.279376,7224.551539,7739.359914
2015,4597.026459,2316.802119,478.068758,96.908982,503.094152,4597.026459,6913.828578,7391.897336,7488.806318,7991.900470
2016,4682.362883,2540.975266,507.910225,95.304591,525.517582,4682.362883,7223.338149,7731.248374,7826.552965,8352.070547
2017,4849.172939,2635.233951,537.355878,93.536200,588.750401,4849.172939,7484.406890,8021.762768,8115.298968,8704.049369
2018,5154.910704,2763.984350,580.914048,97.055911,653.640178,5154.910704,7918.895055,8499.809103,8596.865014,9250.505191
2019,5172.222865,2843.930590,596.808969,111.833182,736.187827,5172.222865,8016.153456,8612.962424,8724.795606,9460.983433

In [468]:
#second visualisation: stacked consumption coal
#data https://ourworldindata.org/co2/country/netherlands

output_file('coal_total_india.html')
source = ColumnDataSource(result_i)

p2 = figure(x_range = (1965,2018), y_range=(0,10000),sizing_mode='stretch_both', 
            title = 'India\'s huge rise in energy use has rested strongly on coal', toolbar_location=None, x_axis_label ='Year', y_axis_label ='Energy consumption (in terrawatt-hours*)')

p2.add_layout(Title(text="Energy consumption by source in India", text_font_style="italic", text_font_size = '10px',), 'above')

p2.varea(x='Year', y1=0, y2='Coal_sum', source = source, color = colour[1], alpha = 0.7, legend_label = 'Coal')
coal = p2.line(x = 'Year', y = 'Coal_sum', source = source, color = colour[1])
p2.add_tools(HoverTool(renderers=[coal], tooltips=[('Type', 'Coal'),('Year', '@Year'),('kWh',"@Coal{0.0 a}")],mode='mouse',toggleable=False))


p2.varea(x='Year', y1='Coal_sum', y2='Oil_sum', source = source, color = colour[0], alpha = 0.7, legend_label = 'Oil')
oil = p2.line(x = 'Year', y = 'Oil_sum', source = source, color = colour[0])
p2.add_tools(HoverTool(renderers=[oil], tooltips=[('Type', 'Oil'),('Year', '@Year'),('kWh',"@Oil{0.0 a}")],mode='mouse',toggleable=False))


p2.varea(x='Year', y1='Oil_sum', y2='Gas_sum', source = source, color = colour[2], alpha = 0.7, legend_label = 'Gas')
gas = p2.line(x = 'Year', y = 'Gas_sum', source = source, color = colour[2])
p2.add_tools(HoverTool(renderers=[coal], tooltips=[('Type', 'Gas'),('Year', '@Year'),('kWh',"@Gas{0.0 a}")],mode='mouse',toggleable=False))

p2.varea(x='Year', y1='Gas_sum', y2='Nuclear_sum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Nuclear')
nuclear = p2.line(x = 'Year', y = 'Nuclear_sum', source = source, color = colour[3])
p2.add_tools(HoverTool(renderers=[nuclear], tooltips=[('Type', 'Nuclear'),('Year', '@Year'),('kWh',"@Nuclear{0.0 a}")],mode='mouse',toggleable=False))

p2.varea(x='Year', y1='Nuclear_sum', y2='R_sum', source = source, color = colour[4], alpha = 0.7, legend_label = 'Renewables')
renewable = p2.line(x = 'Year', y = 'R_sum', source = source, color = colour[4])
p2.add_tools(HoverTool(renderers=[renewable], tooltips=[('Type', 'Renewables'),('Year', '@Year'),('kWh',"@Renewables{0.0 a}")],mode='mouse',toggleable=False))

#add data sources below charts

label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data Source: Our World in Data'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p2.add_layout(caption1, 'below')
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = '*A terawatt-hour is a unit of energy equal to outputting one trillion watts for one hour'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p2.add_layout(caption1, 'below')
p2.xaxis.major_label_orientation = 120

p2.toolbar.active_drag = None

p2.yaxis[0].formatter = NumeralTickFormatter(format="0,0")
p2.legend.location = 'top_left'

show(p2)
save (p2)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/coal_total_india.html'

# Brazil forest loss

In [202]:
#load co2 emissions
#https://www.globalforestwatch.org/dashboards/country/IDN/?burnedAreaCumulative=eyJjb21wYXJlWWVhciI6ImFsbCJ9&category=climate&dashboardPrompts=eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6WyJkb3dubG9hZERhc2hib2FyZFN0YXRzIiwid2lkZ2V0U2V0dGluZ3MiLCJzaGFyZVdpZGdldCJdLCJzZXR0aW5ncyI6eyJzaG93UHJvbXB0cyI6dHJ1ZSwicHJvbXB0c1ZpZXdlZCI6WyJkb3dubG9hZERhc2hib2FyZFN0YXRzIiwid2lkZ2V0U2V0dGluZ3MiXSwic2V0dGluZ3MiOnsic2hvd1Byb21wdHMiOnRydWUsInByb21wdHNWaWV3ZWQiOlsiZG93bmxvYWREYXNoYm9hcmRTdGF0cyIsIndpZGdldFNldHRpbmdzIl0sInNldHRpbmdzIjp7InNob3dQcm9tcHRzIjp0cnVlLCJwcm9tcHRzVmlld2VkIjpbImRvd25sb2FkRGFzaGJvYXJkU3RhdHMiXSwic2V0dGluZ3MiOnsic2hvd1Byb21wdHMiOnRydWUsInByb21wdHNWaWV3ZWQiOltdLCJzZXR0aW5ncyI6eyJvcGVuIjpmYWxzZSwic3RlcEluZGV4IjowLCJzdGVwc0tleSI6IiJ9LCJvcGVuIjp0cnVlLCJzdGVwSW5kZXgiOjAsInN0ZXBzS2V5IjoiZG93bmxvYWREYXNoYm9hcmRTdGF0cyJ9LCJvcGVuIjp0cnVlLCJzdGVwSW5kZXgiOjAsInN0ZXBzS2V5Ijoid2lkZ2V0U2V0dGluZ3MifSwic3RlcHNLZXkiOiJ3aWRnZXRTZXR0aW5ncyIsInN0ZXBJbmRleCI6MCwib3BlbiI6ZmFsc2UsImZvcmNlIjp0cnVlfSwib3BlbiI6dHJ1ZSwic3RlcEluZGV4IjowLCJzdGVwc0tleSI6InNoYXJlV2lkZ2V0In0sInN0ZXBzS2V5Ijoic2hhcmVXaWRnZXQiLCJmb3JjZSI6dHJ1ZX0%3D&fireAlertStats=eyJmb3Jlc3RUeXBlIjoiaWZsIn0%3D&location=WyJjb3VudHJ5IiwiSUROIl0%3D&map=eyJjZW50ZXIiOnsibGF0IjoxMi43OTQzODcxNDU5NDgwMDgsImxuZyI6MTE0LjA2NDkzMzA4MDc4NDA3fSwiem9vbSI6My41OTczODE5NDQ0NDQ4NjE0LCJjYW5Cb3VuZCI6ZmFsc2UsImRhdGFzZXRzIjpbeyJkYXRhc2V0IjoicG9saXRpY2FsLWJvdW5kYXJpZXMiLCJsYXllcnMiOlsiZGlzcHV0ZWQtcG9saXRpY2FsLWJvdW5kYXJpZXMiLCJwb2xpdGljYWwtYm91bmRhcmllcyJdLCJib3VuZGFyeSI6dHJ1ZSwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZX0seyJkYXRhc2V0IjoibmV0LWNhcmJvbi1mbHV4IiwibGF5ZXJzIjpbIm5ldC1jYXJib24tZmx1eC0yMDAxLTIwMjAiXSwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZSwidGltZWxpbmVQYXJhbXMiOnsic3RhcnREYXRlIjoiMjAwMS0wMS0wMSIsImVuZERhdGUiOiIyMDIwLTEyLTMxIiwidHJpbUVuZERhdGUiOiIyMDIwLTEyLTMxIn0sInBhcmFtcyI6eyJ0aHJlc2hvbGQiOjMwLCJ2aXNpYmlsaXR5Ijp0cnVlfX0seyJkYXRhc2V0IjoiY2FyYm9uLXJlbW92YWxzIiwibGF5ZXJzIjpbImNhcmJvbi1yZW1vdmFscy0yMDAxLTIwMjAiXSwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZSwidGltZWxpbmVQYXJhbXMiOnsic3RhcnREYXRlIjoiMjAwMS0wMS0wMSIsImVuZERhdGUiOiIyMDIwLTEyLTMxIiwidHJpbUVuZERhdGUiOiIyMDIwLTEyLTMxIn0sInBhcmFtcyI6eyJ0aHJlc2hvbGQiOjMwLCJ2aXNpYmlsaXR5Ijp0cnVlfX0seyJkYXRhc2V0IjoiY2FyYm9uLWVtaXNzaW9ucyIsImxheWVycyI6WyJjYXJib24tZW1pc3Npb25zLTIwMDEtMjAyMCJdLCJvcGFjaXR5IjoxLCJ2aXNpYmlsaXR5Ijp0cnVlLCJ0aW1lbGluZVBhcmFtcyI6eyJzdGFydERhdGUiOiIyMDAxLTAxLTAxIiwiZW5kRGF0ZSI6IjIwMjAtMTItMzEiLCJ0cmltRW5kRGF0ZSI6IjIwMjAtMTItMzEifSwicGFyYW1zIjp7InRocmVzaG9sZCI6MzAsInZpc2liaWxpdHkiOnRydWV9fV19&treeLossPct=eyJoaWdobGlnaHRlZCI6ZmFsc2V9
co2_forest = pd.read_csv('Forest_related_GHG_emissions_brazil.csv', names = ['year', 'all_gasses', 'non_co2', 'co2_only'], skiprows = 1)

co2_forest.head()

     year    all_gasses       non_co2      co2_only
BRA  2001  1.177965e+09  1.179646e+07  1.166168e+09
BRA  2002  1.611052e+09  2.264450e+07  1.588407e+09
BRA  2003  1.478305e+09  2.130276e+07  1.457003e+09
BRA  2004  1.884753e+09  2.696412e+07  1.857789e+09
BRA  2005  1.816124e+09  2.567372e+07  1.790451e+09

In [203]:
#load primary forest loss
#same as above
primary_forests = pd.read_csv('treecover_loss_in_primary_forests_2001_tropics_only__ha_brazil.csv', names = ['year', 'primary_forest_loss', 'co2'], skiprows = 1)
primary_forests = primary_forests.iloc[:, :-1]
primary_forests.head()

     year  primary_forest_loss
BRA  2001         4.655430e+05
BRA  2002         1.621765e+06
BRA  2003         1.570576e+06
BRA  2004         2.016477e+06
BRA  2005         1.824425e+06

In [205]:
#merge data frames
brazil_forests = pd.merge(co2_forest, forest_loss, on ='year')
brazil_forests = pd.merge(brazil_forests, primary_forests, on = 'year')
brazil_forests['stand_forest'] = brazil_forests['primary_forest_loss']/10000

brazil_forests['all_gasses_mt']= brazil_forests['all_gasses']/1000000
brazil_forests['gt'] = brazil_forests['all_gasses_mt'] *0.001

brazil_forests.head()

,year,all_gasses,non_co2,co2_only,tree_cover_loss,primary_forest_loss,stand_forest,all_gasses_mt,gt
0,2001,1.177965e+09,1.179646e+07,1.166168e+09,7.440880e+05,4.655430e+05,46.554298,1177.964711,1.177965
1,2002,1.611052e+09,2.264450e+07,1.588407e+09,8.552759e+05,1.621765e+06,162.176513,1611.051645,1.611052
2,2003,1.478305e+09,2.130276e+07,1.457003e+09,5.448103e+05,1.570576e+06,157.057559,1478.305311,1.478305
3,2004,1.884753e+09,2.696412e+07,1.857789e+09,1.289043e+06,2.016477e+06,201.647716,1884.753108,1.884753
4,2005,1.816124e+09,2.567372e+07,1.790451e+09,1.182442e+06,1.824425e+06,182.442547,1816.124252,1.816124

In [452]:
output_file('forests_brazil.html')
#data https://www.globalforestwatch.org/
from bokeh.models import TickFormatter, FixedTicker, Range1d, LinearAxis

#create figure
p = figure(x_axis_label='Year', y_axis_label='Forest-related greenhouse gas emissions (billions of tonnes CO2e)',title = 'Forest emissions closely mirror primary forest loss in Brazil',x_range= (2000,2021), y_range = (0,4),
            sizing_mode='stretch_both', toolbar_location=None, min_border=0, outline_line_color = None)

p.add_layout(Title(text='Forest-related emissions and primary forest loss in Brazil', text_font_style="italic", text_font_size = '10px',), 'above')



#Disable scientific notation on axes
p.left[0].formatter.use_scientific = False
#p.yaxis[0].formatter = NumeralTickFormatter(format="0")
p.xaxis.ticker = list(range(2000, 2021, 5))

start = brazil_forests.primary_forest_loss.min()
end= brazil_forests.primary_forest_loss.max()

p.extra_y_ranges = {"Forest Loss": Range1d(start, end)}
p.add_layout(LinearAxis(y_range_name="Forest Loss", axis_label = 'Forest loss (hectar)'), 'right')
p.yaxis[1].formatter.use_scientific = False
p.yaxis[1].formatter = NumeralTickFormatter(format="0,0")
#p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

#set source to dataframe
s = ColumnDataSource(brazil_forests)


#bar + linedata
bars = p.vbar(x = 'year', top = 'gt', width= 0.7, source = s,
          color=colour[6], line_color = colour[6], legend_label = 'Forest-related emissions')
#add tools
p.add_tools(HoverTool(renderers = [bars], tooltips = [('Year', '@year'), ('Emissions', '@gt{0.00} Gt')]))

line = p.line(x = 'year', y = 'primary_forest_loss', y_range_name = 'Forest Loss', source = s,
      color = colour[2], line_width = 5, legend_label = 'Primary forest loss')

p.add_tools(HoverTool(renderers =[line], tooltips = [('Year', '@year'),  ('Primary forest loss', '@primary_forest_loss{0,0} ha')]))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data sources: Global Forest Watch'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

#add bar

p.xaxis.major_label_orientation = 120

p.toolbar.active_drag = None
p.legend.location = 'top_left'

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/forests_brazil.html'

# Nigeria electricity share

In [666]:
urban = pd.read_csv('urban_electricity.csv', sep = ';')
urban_n = urban[(urban['Country Name'].isin(['Nigeria','Morocco', 'World']))]

rural = pd.read_csv('rural_electricity.csv', sep = ';')
rural_n = rural[(rural['Country Name'].isin(['Nigeria','Morocco', 'World']))]

In [667]:
#prep dataset
rural_n = pd.pivot_table(rural_n, columns = ['Country Name']).reset_index()
urban_n = pd.pivot_table(urban_n, columns = ['Country Name']).reset_index()

urban_n = urban_n.iloc[:-1]
rural_n = rural_n.iloc[:-1]

urban_n['index'] = pd.to_numeric(urban_n['index'])
rural_n['index'] = pd.to_numeric(rural_n['index'])

In [668]:
urban_n

Country Name  index  Morocco  Nigeria      World
0              1960      NaN      NaN        NaN
1              1961      NaN      NaN        NaN
2              1962      NaN      NaN        NaN
3              1963      NaN      NaN        NaN
4              1964      NaN      NaN        NaN
..              ...      ...      ...        ...
56             2016     99.3     86.0  96.768832
57             2017    100.0     86.8  97.090994
58             2018     99.3     81.7  97.012843
59             2019    100.0     83.9  97.272664
60             2020      NaN      NaN        NaN

[61 rows x 4 columns]

In [671]:
output_file('nigeria_electricity.html')
from bokeh.transform import dodge

p = figure(x_axis_label='Year', y_axis_label='Percentage', title = 'Nigeria\'s rural population largely lacks access to electricity', x_range = (2000, 2020), y_range = (0,105),
            sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Access to electricity, % of population", text_font_style="italic", text_font_size = '10px',), 'above')


p.xaxis.ticker = list(range(2000, 2020,2))

#coal line
#i_coal = p.vbar(x =dodge('Year', -0.25, range=p.x_range), top = 'Coal (% electricity)', alpha = 0.7, source = india_coal, color= colour[1], width = 0.4, legend_label = 'India electricity from coal % of total')
#p.add_tools(HoverTool(renderers=[i_coal], tooltips=[('Country', 'India'),('Year', '@Year'),('Percentage',"@{Coal (% electricity)}{0.0}%")],mode='mouse'))


#c_coal = p.vbar(x = dodge('Year', 0.25, range = p.x_range), top = 'Coal (% electricity)', alpha = 0.7, source = china_coal, color= colour[2], width = 0.4, legend_label = 'China electricity from coal % of total')
#p.add_tools(HoverTool(renderers=[c_coal], tooltips=[('Country', 'China'),('Year', '@Year'),('Percentage',"@{Coal (% electricity)}{0.0}%")],mode='mouse'))

#urban electricty line Nigeria
urb = p.line(x ='index', y = 'Nigeria', source = urban_n, color= colour[0], line_width = 5, line_dash = 'dashed', legend_label = 'Nigeria access to electricity % of urban population')
p.add_tools(HoverTool(renderers=[urb], tooltips=[('Area', 'Urban'),('Year', '@index'),('Percentage',"@Nigeria{0.0}%")],mode='mouse'))

#rural electricty line Nigeria
rur = p.line(x ='index', y = 'Nigeria', source = rural_n, color= colour[0], line_width = 5,  legend_label = 'Nigeria access to electricity % of rural population')
p.add_tools(HoverTool(renderers=[rur], tooltips=[('Area', 'Rural'),('Year', '@index'),('Percentage',"@Nigeria{0.0}%")],mode='mouse'))

#urban electricty line world
urb = p.line(x ='index', y = 'World', source = urban_n, color= colour[1], line_width = 5, line_dash = 'dashed',  legend_label = 'World access to electricity % of urban population')
p.add_tools(HoverTool(renderers=[urb], tooltips=[('Area', 'Urban'),('Year', '@index'),('Percentage',"@World{0.0}%")],mode='mouse'))

#rural electricty line world
rur = p.line(x ='index', y = 'World', source = rural_n, color= colour[1], line_width = 5,  legend_label = 'World access to electricity % of rural population')
p.add_tools(HoverTool(renderers=[rur], tooltips=[('Area', 'Rural'),('Year', '@index'),('Percentage',"@World{0.0}%")],mode='mouse'))

p.yaxis[0].formatter = PrintfTickFormatter(format='%0.0f%%')

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: World Bank'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None

p.legend.location = 'bottom_left'
show(p)

In [673]:
clean = pd.read_csv('clean_cooking.csv', sep = ';')

clean = clean[(clean['Country Name'].isin(['Nigeria','Morocco', 'World', 'European Union']))]

#prep dataset
clean = pd.pivot_table(clean, columns = ['Country Name']).reset_index()

clean = clean.iloc[:-1]


clean['index'] = pd.to_numeric(clean['index'])
clean

Country Name  index  European Union  Morocco  Nigeria      World
0              1960             NaN      NaN      NaN        NaN
1              1961             NaN      NaN      NaN        NaN
2              1962             NaN      NaN      NaN        NaN
3              1963             NaN      NaN      NaN        NaN
4              1964             NaN      NaN      NaN        NaN
..              ...             ...      ...      ...        ...
56             2016       98.818121    96.75     4.91  59.340671
57             2017             NaN      NaN      NaN        NaN
58             2018             NaN      NaN      NaN        NaN
59             2019             NaN      NaN      NaN        NaN
60             2020             NaN      NaN      NaN        NaN

[61 rows x 5 columns]

In [681]:
output_file('nigeria_cooking.html')
from bokeh.transform import dodge

p = figure(x_axis_label='Year', y_axis_label='Percentage of population', title = 'Few people in Nigeria have access to clean cooking fuels', x_range = (2000, 2016), y_range = (0,105),
            sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Access to clean fuels and technology for cooking", text_font_style="italic", text_font_size = '10px',), 'above')


p.xaxis.ticker = list(range(2000, 2017,2))

#coal line
#i_coal = p.vbar(x =dodge('Year', -0.25, range=p.x_range), top = 'Coal (% electricity)', alpha = 0.7, source = india_coal, color= colour[1], width = 0.4, legend_label = 'India electricity from coal % of total')
#p.add_tools(HoverTool(renderers=[i_coal], tooltips=[('Country', 'India'),('Year', '@Year'),('Percentage',"@{Coal (% electricity)}{0.0}%")],mode='mouse'))


#c_coal = p.vbar(x = dodge('Year', 0.25, range = p.x_range), top = 'Coal (% electricity)', alpha = 0.7, source = china_coal, color= colour[2], width = 0.4, legend_label = 'China electricity from coal % of total')
#p.add_tools(HoverTool(renderers=[c_coal], tooltips=[('Country', 'China'),('Year', '@Year'),('Percentage',"@{Coal (% electricity)}{0.0}%")],mode='mouse'))

# line Nigeria
n = p.line(x ='index', y = 'Nigeria', source = clean, color= 'black', line_width = 5, legend_label = 'Nigeria access to clean cooking fuels')
p.add_tools(HoverTool(renderers=[n], tooltips=[('Country','Nigeria'),('Year', '@index'),('Percentage',"@Nigeria{0.0}%")],mode='mouse'))
p.scatter(x = 'index', y = 'Nigeria', source = clean, fill_color = 'black', line_color = 'black',size = 7 )


# area world
w = p.line(x ='index', y = 'World', source = clean, color= colour[1], line_width = 2,  legend_label = 'World access to clean cooking fuels')
#p.varea(x = 'index', y1 = 0, y2 = 'World', source = clean, color = colour[1], alpha = 0.5, level = 'underlay')
p.add_tools(HoverTool(renderers=[w], tooltips=[('Region','World'),('Year', '@index'),('Percentage',"@World{0.0}%")],mode='mouse'))
p.scatter(x = 'index', y = 'World', source = clean, fill_color = colour[1], line_color = colour[1],size = 4 )


#line EU
eu = p.line(x ='index', y = 'European Union', source = clean, color= colour[2], line_width = 2,  legend_label = 'EU access to clean cooking fuels')
p.add_tools(HoverTool(renderers=[eu], tooltips=[('Region','EU'),('Year', '@index'),('Percentage',"@{European Union}{0.0}%")],mode='mouse'))
#p.varea(x = 'index', y1 = 'World', y2 = 'European Union', source = clean, color = colour[2], alpha = 0.5, level = 'underlay')
p.scatter(x = 'index', y = 'European Union', source = clean, fill_color = colour[2], line_color = colour[2],size = 4 )

p.yaxis[0].formatter = PrintfTickFormatter(format='%0.0f%%')

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: World Bank'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

p.legend.location = 'top_left'
show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/nigeria_cooking.html'

# Russia oil share of energy consumption

In [684]:
gas_cons = pd.read_csv('energy-consumption-by-source-and-region.csv', sep = ';')
gas_cons = gas_cons[gas_cons.Entity == 'Russia']
gas_cons = gas_cons.iloc[:,2:]
gas_cons = gas_cons.set_index('Year')
gas_cons['Renewables'] = gas_cons['Solar']+gas_cons['Hydro']+ gas_cons['Wind']+ gas_cons['Geo Biomass']+ gas_cons['Biofuels']
gas_cons.head()

,Oil,Gas,Coal,Solar,Hydro,Nuclear,Wind,Geo Biomass,Biofuels,Renewables
Year,,,,,,,,,,
1985,2936.286307,3560.850740,2303.886852,0.0,443.683563,275.881266,0.0,0.0,0.0,443.683563
1986,2971.361410,3602.146062,2366.462867,0.0,456.475281,292.282163,0.0,0.0,0.0,456.475281
1987,2995.658429,3809.969976,2402.566108,0.0,451.466623,346.395304,0.0,0.0,0.0,451.466623
1988,2972.014191,4020.565166,2367.103793,0.0,447.010391,374.483069,0.0,0.0,0.0,447.010391
1989,3027.458136,4080.339324,2288.869102,0.0,443.683563,378.718331,0.0,0.0,0.0,443.683563

In [685]:
#prepare df with independent lines, + cumulative
temp = gas_cons.drop(['Solar', 'Hydro', 'Wind', 'Geo Biomass', 'Biofuels'], axis = 1)

cum_df = temp.cumsum(axis = 1)

cum_df.columns = ['Oil_sum', 'Gas_sum', 'Coal_sum', 'Nuclear_sum', 'R_sum']

sum_df = temp + cum_df

result_r= pd.concat([temp, cum_df], axis=1)
result_r = result_r.iloc[:-5]
#result_r = result_r*1000000000

In [742]:
#second visualisation: stacked consumption
#data https://ourworldindata.org/co2/country/netherlands

output_file('russia_energy.html')
source = ColumnDataSource(result_r)

p = figure(x_range = (1985,2019), y_range=(0,15000), sizing_mode='stretch_both', toolbar_location=None, x_axis_label ='Year', y_axis_label ='Annual energy consumption (in terrawatt-hours*)',
           title = 'Russia gets most of its energy from gas')

p.add_layout(Title(text="Energy consumption by source in Russia", text_font_style="italic", text_font_size = '10px',), 'above')


p.varea(x='Year', y1=0, y2='Oil_sum', source = source, color = colour[1], alpha = 0.7, legend_label = 'Oil')
oil = p.line(x = 'Year', y = 'Oil_sum', source = source, color = colour[1])
p.add_tools(HoverTool(renderers=[oil], tooltips=[('Type', 'Oil'),('Year', '@Year'),('kWh',"@Oil{0.0 a}")],mode='mouse',toggleable=False))


p.varea(x='Year', y1='Oil_sum', y2='Gas_sum', source = source, color = colour[0], alpha = 0.7, legend_label = 'Gas')
gas = p.line(x = 'Year', y = 'Gas_sum', source = source, color = colour[0])
p.add_tools(HoverTool(renderers=[gas], tooltips=[('Type', 'Gas'),('Year', '@Year'),('kWh',"@Gas{0.0 a}")],mode='mouse',toggleable=False))


p.varea(x='Year', y1='Gas_sum', y2='Coal_sum', source = source, color = colour[2], alpha = 0.7, legend_label = 'Coal')
coal = p.line(x = 'Year', y = 'Coal_sum', source = source, color = colour[2])
p.add_tools(HoverTool(renderers=[coal], tooltips=[('Type', 'Coal'),('Year', '@Year'),('kWh',"@Coal{0.0 a}")],mode='mouse',toggleable=False))

p.varea(x='Year', y1='Coal_sum', y2='Nuclear_sum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Nuclear')
nuclear = p.line(x = 'Year', y = 'Nuclear_sum', source = source, color = colour[3])
p.add_tools(HoverTool(renderers=[nuclear], tooltips=[('Type', 'Nuclear'),('Year', '@Year'),('kWh',"@Nuclear{0.0 a}")],mode='mouse',toggleable=False))

p.varea(x='Year', y1='Nuclear_sum', y2='R_sum', source = source, color = colour[4], alpha = 0.7, legend_label = 'Renewables')
renewable = p.line(x = 'Year', y = 'R_sum', source = source, color = colour[4])
p.add_tools(HoverTool(renderers=[renewable], tooltips=[('Type', 'Renewables'),('Year', '@Year'),('kWh',"@Renewables{0.0 a}")],mode='mouse',toggleable=False))

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data Source: Our World in Data'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

msg = 'BP Statistical Review of World Energy'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = '*A terawatt-hour is a unit of energy equal to outputting one trillion watts for one hour'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

p.legend.location = 'top_left'

p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

show(p)
save (p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/russia_energy.html'

# Morocco

In [800]:
#data load
gas_cons = pd.read_csv('energy-consumption-by-source-and-region.csv', sep = ';')
gas_cons = gas_cons[gas_cons.Entity == 'Morocco']
morocco = gas_cons.iloc[:,2:].set_index('Year')

el_m = pd.read_csv('electricity-prod-source-stacked.csv')
el_m = el_m[el_m.Entity == 'Morocco']
el_m = el_m.iloc[:-15,2:].set_index('Year')

el_m

,Electricity from coal (TWh),Electricity from gas (TWh),Electricity from hydro (TWh),Electricity from other renewables (TWh),Electricity from solar (TWh),Electricity from oil (TWh),Electricity from wind (TWh),Electricity from nuclear (TWh)
Year,,,,,,,,
2000,8.909789,0.000000,0.71100,0.000000,0.0000,2.446351,0.064,0.0
2001,10.302197,0.000000,0.86200,0.000000,0.0000,2.828663,0.206,0.0
2002,11.083214,0.000000,0.84200,0.000000,0.0001,3.043106,0.194,0.0
2003,12.038328,0.000000,1.44100,0.000000,0.0001,2.804272,0.203,0.0
2004,12.738213,0.000000,1.59200,0.000000,0.0001,2.967307,0.199,0.0
2005,14.276740,0.000000,0.96900,0.000000,0.0001,3.325700,0.206,0.0
2006,13.188836,1.832946,0.98800,0.000000,0.0001,3.072278,0.183,0.0
2007,13.232002,1.838945,0.90600,0.000000,0.0001,3.082333,0.279,0.0
2008,13.427275,1.866083,0.92000,0.000000,0.0001,3.127821,0.298,0.0
2009,12.460617,1.731740,2.54200,0.000000,0.0001,2.902643,0.391,0.0
2010,11.630635,3.552779,3.43300,0.000000,0.0001,3.188886,0.659,0.0
2011,11.262829,6.618650,1.98600,0.000000,0.0001,3.088041,0.690,0.0
2012,12.609845,7.410230,1.61500,0.005000,0.0000,3.457366,0.728,0.0
2013,11.407224,6.703504,2.75700,0.005000,0.0000,3.127631,1.356,0.0
2014,12.180193,7.157743,1.62100,0.005414,0.0000,3.339564,1.920,0.0
2015,12.676488,7.449393,1.86600,0.005414,0.0050,3.475638,2.520,0.0
2016,13.013747,7.647585,1.24200,0.011910,0.4010,3.568108,3.000,0.0
2017,13.568609,7.973652,1.17300,0.013263,0.4150,3.720240,3.035,0.0
2018,14.009368,8.232665,1.67706,0.013263,0.9500,3.841087,3.841,0.0
2019,16.365131,9.617040,1.63746,0.015879,1.5810,4.486990,4.699,0.0

In [794]:
el_m['Renewables'] = el_m['Electricity from hydro (TWh)'] + el_m['Electricity from other renewables (TWh)'] + el_m['Electricity from solar (TWh)']+el_m['Electricity from wind (TWh)']

el_m = el_m.drop(['Electricity from hydro (TWh)','Electricity from other renewables (TWh)', 'Electricity from solar (TWh)', 'Electricity from wind (TWh)', 'Electricity from nuclear (TWh)' ], axis = 1)
el_m
cum_el = el_m.cumsum(axis = 1)
cum_el

cum_el.columns = ['coal_sum', 'gas_sum', 'oil_sum', 'R_sum']


result_= pd.concat([el_m, cum_el], axis=1)
#result_m = result_r.iloc[:-5]
#result_m = result_m*1000000000
result_

,Electricity from coal (TWh),Electricity from gas (TWh),Electricity from oil (TWh),Renewables,coal_sum,gas_sum,oil_sum,R_sum
Year,,,,,,,,
2000,8.909789,0.000000,2.446351,0.775000,8.909789,8.909789,11.35614,12.131140
2001,10.302197,0.000000,2.828663,1.068000,10.302197,10.302197,13.13086,14.198860
2002,11.083214,0.000000,3.043106,1.036100,11.083214,11.083214,14.12632,15.162420
2003,12.038328,0.000000,2.804272,1.644100,12.038328,12.038328,14.84260,16.486700
2004,12.738213,0.000000,2.967307,1.791100,12.738213,12.738213,15.70552,17.496620
2005,14.276740,0.000000,3.325700,1.175100,14.276740,14.276740,17.60244,18.777540
2006,13.188836,1.832946,3.072278,1.171100,13.188836,15.021782,18.09406,19.265160
2007,13.232002,1.838945,3.082333,1.185100,13.232002,15.070947,18.15328,19.338380
2008,13.427275,1.866083,3.127821,1.218100,13.427275,15.293359,18.42118,19.639280
2009,12.460617,1.731740,2.902643,2.933100,12.460617,14.192357,17.09500,20.028100
2010,11.630635,3.552779,3.188886,4.092100,11.630635,15.183414,18.37230,22.464400
2011,11.262829,6.618650,3.088041,2.676100,11.262829,17.881479,20.96952,23.645620
2012,12.609845,7.410230,3.457366,2.348000,12.609845,20.020074,23.47744,25.825440
2013,11.407224,6.703504,3.127631,4.118000,11.407224,18.110729,21.23836,25.356360
2014,12.180193,7.157743,3.339564,3.546414,12.180193,19.337936,22.67750,26.223914
2015,12.676488,7.449393,3.475638,4.396414,12.676488,20.125882,23.60152,27.997934
2016,13.013747,7.647585,3.568108,4.654910,13.013747,20.661332,24.22944,28.884350
2017,13.568609,7.973652,3.720240,4.636263,13.568609,21.542260,25.26250,29.898763
2018,14.009368,8.232665,3.841087,6.481323,14.009368,22.242033,26.08312,32.564443
2019,16.365131,9.617040,4.486990,7.933339,16.365131,25.982170,30.46916,38.402499

In [801]:
morocco['Renewables'] = morocco['Hydro']+ morocco['Solar'] + morocco['Wind']+ morocco['Geo Biomass']+ morocco['Biofuels']
#prepare df with independent lines, + cumulative
temp = morocco.drop(['Hydro', 'Wind', 'Solar','Geo Biomass', 'Biofuels', 'Nuclear'], axis = 1)
temp
cum_df = temp.cumsum(axis = 1)

cum_df.columns = ['Oil_sum', 'Gas_sum', 'Coal_sum', 'R_sum']

sum_df = temp + cum_df

result_m= pd.concat([temp, cum_df], axis=1)
#result_m = result_r.iloc[:-5]
result_m = result_m*1000000000

In [802]:
#second visualisation: stacked consumption
#data https://ourworldindata.org/co2/country/netherlands

output_file('morocco_energy.html')
source = ColumnDataSource(result_m)

p = figure(x_range = (1965,2019), y_range=(0,300000000000), sizing_mode='stretch_both', toolbar_location=None, x_axis_label ='Year', y_axis_label ='Annual energy consumption (billions of kilowatt hours)',
           title = 'Morocco has expanded its consumption of both coal and renewables')

p.add_layout(Title(text="Energy consumption by source in Morocco", text_font_style="italic", text_font_size = '10px',), 'above')


p.varea(x='Year', y1=0, y2='Oil_sum', source = source, color = colour[1], alpha = 0.7, legend_label = 'Oil')
oil = p.line(x = 'Year', y = 'Oil_sum', source = source, color = colour[1])
p.add_tools(HoverTool(renderers=[oil], tooltips=[('Type', 'Oil'),('Year', '@Year'),('kWh',"@Oil{0.0 a}")],mode='mouse',toggleable=False))


p.varea(x='Year', y1='Oil_sum', y2='Gas_sum', source = source, color = colour[0], alpha = 0.7, legend_label = 'Gas')
gas = p.line(x = 'Year', y = 'Gas_sum', source = source, color = colour[0])
p.add_tools(HoverTool(renderers=[gas], tooltips=[('Type', 'Gas'),('Year', '@Year'),('kWh',"@Gas{0.0 a}")],mode='mouse',toggleable=False))


p.varea(x='Year', y1='Gas_sum', y2='Coal_sum', source = source, color = colour[2], alpha = 0.7, legend_label = 'Coal')
coal = p.line(x = 'Year', y = 'Coal_sum', source = source, color = colour[2])
p.add_tools(HoverTool(renderers=[coal], tooltips=[('Type', 'Coal'),('Year', '@Year'),('kWh',"@Coal{0.0 a}")],mode='mouse',toggleable=False))

p.varea(x='Year', y1='Coal_sum', y2='R_sum', source = source, color = colour[4], alpha = 0.7, legend_label = 'Renewables')
renewable = p.line(x = 'Year', y = 'R_sum', source = source, color = colour[4])
p.add_tools(HoverTool(renderers=[renewable], tooltips=[('Type', 'Renewables'),('Year', '@Year'),('kWh',"@Renewables{0.0 a}")],mode='mouse',toggleable=False))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data Source: Our World in Data -'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'BP Statistical Review of World Energy'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.legend.location = 'top_left'


p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

p.yaxis[0].formatter = NumeralTickFormatter(format="0,0 a")

show(p)
save (p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/morocco_energy.html'

In [795]:
result_

,Electricity from coal (TWh),Electricity from gas (TWh),Electricity from oil (TWh),Renewables,coal_sum,gas_sum,oil_sum,R_sum
Year,,,,,,,,
2000,8.909789,0.000000,2.446351,0.775000,8.909789,8.909789,11.35614,12.131140
2001,10.302197,0.000000,2.828663,1.068000,10.302197,10.302197,13.13086,14.198860
2002,11.083214,0.000000,3.043106,1.036100,11.083214,11.083214,14.12632,15.162420
2003,12.038328,0.000000,2.804272,1.644100,12.038328,12.038328,14.84260,16.486700
2004,12.738213,0.000000,2.967307,1.791100,12.738213,12.738213,15.70552,17.496620
2005,14.276740,0.000000,3.325700,1.175100,14.276740,14.276740,17.60244,18.777540
2006,13.188836,1.832946,3.072278,1.171100,13.188836,15.021782,18.09406,19.265160
2007,13.232002,1.838945,3.082333,1.185100,13.232002,15.070947,18.15328,19.338380
2008,13.427275,1.866083,3.127821,1.218100,13.427275,15.293359,18.42118,19.639280
2009,12.460617,1.731740,2.902643,2.933100,12.460617,14.192357,17.09500,20.028100
2010,11.630635,3.552779,3.188886,4.092100,11.630635,15.183414,18.37230,22.464400
2011,11.262829,6.618650,3.088041,2.676100,11.262829,17.881479,20.96952,23.645620
2012,12.609845,7.410230,3.457366,2.348000,12.609845,20.020074,23.47744,25.825440
2013,11.407224,6.703504,3.127631,4.118000,11.407224,18.110729,21.23836,25.356360
2014,12.180193,7.157743,3.339564,3.546414,12.180193,19.337936,22.67750,26.223914
2015,12.676488,7.449393,3.475638,4.396414,12.676488,20.125882,23.60152,27.997934
2016,13.013747,7.647585,3.568108,4.654910,13.013747,20.661332,24.22944,28.884350
2017,13.568609,7.973652,3.720240,4.636263,13.568609,21.542260,25.26250,29.898763
2018,14.009368,8.232665,3.841087,6.481323,14.009368,22.242033,26.08312,32.564443
2019,16.365131,9.617040,4.486990,7.933339,16.365131,25.982170,30.46916,38.402499

In [799]:
#second visualisation: stacked consumption
#data https://ourworldindata.org/co2/country/netherlands

output_file('morocco_source.html')
source = ColumnDataSource(result_)

p = figure(x_range = (2000,2019), y_range=(0,50), sizing_mode='stretch_both', toolbar_location=None, x_axis_label ='Year', y_axis_label ='Annual electricity production (terrawatt hours*)',
           title = 'Renewable electricity production in Morocco is rising')

p.add_layout(Title(text="Electricity production by source in Morocco", text_font_style="italic", text_font_size = '10px',), 'above')


p.varea(x='Year', y1=0, y2='coal_sum', source = source, color = colour[1], alpha = 0.7, legend_label = 'Coal')
coal = p.line(x = 'Year', y = 'coal_sum', source = source, color = colour[1])
p.add_tools(HoverTool(renderers=[coal], tooltips=[('Type', 'Coal'),('Year', '@Year'),('TWh',"@{Electricity from coal (TWh)}{0.0}")],mode='mouse',toggleable=False))


p.varea(x='Year', y1='coal_sum', y2='gas_sum', source = source, color = colour[0], alpha = 0.7, legend_label = 'Gas')
gas = p.line(x = 'Year', y = 'gas_sum', source = source, color = colour[0])
p.add_tools(HoverTool(renderers=[gas], tooltips=[('Type', 'Gas'),('Year', '@Year'),('TWh',"@{Electricity from gas (TWh)}{0.0}")],mode='mouse',toggleable=False))


p.varea(x='Year', y1='gas_sum', y2='oil_sum', source = source, color = colour[2], alpha = 0.7, legend_label = 'Oil')
oil = p.line(x = 'Year', y = 'oil_sum', source = source, color = colour[2])
p.add_tools(HoverTool(renderers=[coal], tooltips=[('Type', 'Oil'),('Year', '@Year'),('TWh',"@{Electricity from oil (TWh)}{0.0}")],mode='mouse',toggleable=False))

p.varea(x='Year', y1='oil_sum', y2='R_sum', source = source, color = colour[4], alpha = 0.7, legend_label = 'Renewables')
renewable = p.line(x = 'Year', y = 'R_sum', source = source, color = colour[4])
p.add_tools(HoverTool(renderers=[renewable], tooltips=[('Type', 'Renewables'),('Year', '@Year'),('TWh',"@Renewables{0.0 }")],mode='mouse',toggleable=False))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data Source: Our World in Data -'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
msg = 'BP Statistical Review of World Energy'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = '*A terawatt-hour is a unit of energy equal to outputting one trillion watts for one hour'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.legend.location = 'top_left'
p.legend.location = 'top_left'


p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

p.yaxis[0].formatter = NumeralTickFormatter(format="0,0 a")

show(p)
save (p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/morocco_source.html'

In [761]:
output_file('morocco_electricity.html')
from bokeh.transform import dodge

p = figure(x_axis_label='Year', y_axis_label='Percentage of population', title = 'Morocco is now close to achieving universal electricity access', x_range = (2000, 2019.5), y_range = (0,105),
            sizing_mode='stretch_both', toolbar_location=None)

p.add_layout(Title(text="Access to electricity, % of population", text_font_style="italic", text_font_size = '10px',), 'above')


p.xaxis.ticker = list(range(2000, 2020,4))

#coal line
#i_coal = p.vbar(x =dodge('Year', -0.25, range=p.x_range), top = 'Coal (% electricity)', alpha = 0.7, source = india_coal, color= colour[1], width = 0.4, legend_label = 'India electricity from coal % of total')
#p.add_tools(HoverTool(renderers=[i_coal], tooltips=[('Country', 'India'),('Year', '@Year'),('Percentage',"@{Coal (% electricity)}{0.0}%")],mode='mouse'))


#c_coal = p.vbar(x = dodge('Year', 0.25, range = p.x_range), top = 'Coal (% electricity)', alpha = 0.7, source = china_coal, color= colour[2], width = 0.4, legend_label = 'China electricity from coal % of total')
#p.add_tools(HoverTool(renderers=[c_coal], tooltips=[('Country', 'China'),('Year', '@Year'),('Percentage',"@{Coal (% electricity)}{0.0}%")],mode='mouse'))

#urban electricty line Morocco
urb = p.line(x ='index', y = 'Morocco', source = urban_n, color= colour[0], line_width = 5, line_dash = 'dashed', legend_label = 'Morocco access to electricity % of urban population')
p.add_tools(HoverTool(renderers=[urb], tooltips=[('Area', 'Urban'),('Year', '@index'),('Percentage',"@Morocco{0.0}%")],mode='mouse'))

#rural electricty line Morocco
rur = p.line(x ='index', y = 'Morocco', source = rural_n, color= colour[0], line_width = 5,  legend_label = 'Morocco access to electricity % of rural population')
p.add_tools(HoverTool(renderers=[rur], tooltips=[('Area', 'Rural'),('Year', '@index'),('Percentage',"@Morocco{0.0}%")],mode='mouse'))

#urban electricty line world
urb = p.line(x ='index', y = 'World', source = urban_n, color= colour[1], line_width = 5, line_dash = 'dashed',  legend_label = 'World access to electricity % of urban population')
p.add_tools(HoverTool(renderers=[urb], tooltips=[('Area', 'Urban'),('Year', '@index'),('Percentage',"@World{0.0}%")],mode='mouse'))

#rural electricty line world
rur = p.line(x ='index', y = 'World', source = rural_n, color= colour[1], line_width = 5,  legend_label = 'World access to electricity % of rural population')
p.add_tools(HoverTool(renderers=[rur], tooltips=[('Area', 'Rural'),('Year', '@index'),('Percentage',"@World{0.0}%")],mode='mouse'))

p.yaxis[0].formatter = PrintfTickFormatter(format='%0.0f%%')

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data source: Worldbank'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.toolbar.active_drag = None

p.legend.location = 'bottom_right'
show(p)

In [434]:
#brazil oil

countries = ['United States', 'Brazil', 'Iraq', 'Canada', 'Saudi Arabia']
mbd= [3.39, 1.48, 1.28, 0.6, 0.55]

oil = pd.DataFrame(mbd, countries, columns = ['mbd']).reset_index()

In [435]:
oil['color'] = colour[0:5]

In [436]:
output_file('oil_top5.html')
#data: https://www.iea.org/data-and-statistics/charts/top-5-contributors-to-global-oil-growth-2018-30
source = ColumnDataSource(oil)

p = figure(x_range = countries, y_range = (0,6),y_axis_label = 'Million barrels per day', x_axis_label = 'Country', 
           title ='...',
           toolbar_location=None, sizing_mode = 'stretch_both')

p.add_layout(Title(text="Projected top five contributors to global oil growth, 2018-2030", text_font_style="italic", text_font_size = '10px',), 'above')

imp = p.vbar(x='index',bottom = 0, top = 'mbd', width =0.75, source = source, fill_color = 'color', line_color = 'color', legend_group = 'index')
#imp = p.scatter(y='year',x = 'imports', source = source, size = 5, fill_color = colour[0], line_color = colour[0])
p.add_tools(HoverTool(renderers=[imp], tooltips=[('Production growth to 2030', '@mbd{0.00} million barrels per day')],mode='mouse',toggleable=False))


#Disable scientific notation on axes
#p.left[0].formatter.use_scientific = False
#p.below[0].formatter.use_scientific = False
#p.below[0].formatter = NumeralTickFormatter(format="0,0")
#p.left[0].formatter = NumeralTickFormatter(format="0,0 a")

#p.xaxis.minor_tick_line_color = None
p.toolbar.active_drag = None
p.legend.location = 'top_left'

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data Source: International Energy Agency'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/oil_top5.html'

In [651]:
nigeria = pd.read_csv('final_cons.csv', sep = ';')

nigeria = nigeria.drop('Units', axis = 1)
nigeria = nigeria.set_index('Unnamed: 0')

el = nigeria.iloc[:,-1]

nigeria = nigeria.drop('Electricity', axis = 1)
nigeria.insert(1, 'Electricity', el)


cum_n = nigeria.cumsum(axis = 1)


cum_n.columns = ['coal_sum','elec_sum', 'oil_sum', 'gas_sum', 'bio_sum']

cum_n


result_n= pd.concat([nigeria, cum_n], axis=1)
#convert to twh
result_n = (result_n*277777.77778) *0.000000001


result_n

,Coal,Electricity,Oil products,Natural gas,Biofuels and waste,coal_sum,elec_sum,oil_sum,gas_sum,bio_sum
Unnamed: 0,,,,,,,,,,
1990,0.449444,7.871111,73.826389,8.331389,599.361944,0.449444,8.320556,82.146944,90.478333,689.840278
1995,0.143333,9.436111,83.893889,8.608333,681.495556,0.143333,9.579444,93.473333,102.081667,783.577222
2000,0.021389,8.643056,112.102778,11.271111,779.068889,0.021389,8.664444,120.767222,132.038333,911.107222
2005,0.057222,17.175000,141.646389,32.724167,896.354444,0.057222,17.232222,158.878611,191.602778,1087.957222
2010,0.272222,20.660000,144.266944,14.087778,1058.093889,0.272222,20.932222,165.199167,179.286944,1237.380833
2015,0.365556,25.041944,211.615278,43.768889,1184.301667,0.365556,25.407500,237.022778,280.791667,1465.093333
2019,0.391389,27.273889,240.964167,43.676111,1263.875833,0.391389,27.665278,268.629444,312.305556,1576.181389

In [682]:
#second visualisation: stacked consumption
#data https://www.iea.org/data-and-statistics/data-browser/?country=NIGERIA&fuel=Energy%20consumption&indicator=TFCbySource

output_file('nigeria_tfc.html')
source = ColumnDataSource(result_n)

p = figure(x_range = (1990,2019), y_range=(0,2000), sizing_mode='stretch_both', toolbar_location=None, x_axis_label ='Year', y_axis_label ='Annual energy consumption (terrawatt hours*)',
           title = 'Biofuels and waste dominate Nigeria\'s energy sources')

p.add_layout(Title(text="Total final energy consumption by source", text_font_style="italic", text_font_size = '10px',), 'above')


p.varea(x='Unnamed: 0', y1=0, y2='coal_sum', source = source, color = colour[1], alpha = 0.7, legend_label = 'Coal')
coal = p.line(x = 'Unnamed: 0', y = 'coal_sum', source = source, color = colour[1])
p.add_tools(HoverTool(renderers=[coal], tooltips=[('Type', 'Coal'),('Year', '@{Unnamed: 0}'),('TWh',"@Coal{0.0 a}")],mode='mouse',toggleable=False))


p.varea(x='Unnamed: 0', y1='coal_sum', y2='elec_sum', source = source, color = colour[3], alpha = 0.7, legend_label = 'Electricity')
el = p.line(x = 'Unnamed: 0', y = 'elec_sum', source = source, color = colour[3])
p.add_tools(HoverTool(renderers=[el], tooltips=[('Type', 'Electricity'),('Year', '@{Unnamed: 0}'),('TWh',"@Electricity{0.0 a}")],mode='mouse',toggleable=False))


p.varea(x='Unnamed: 0', y1='elec_sum', y2='oil_sum', source = source, color = colour[2], alpha = 0.7, legend_label = 'Oil products')
oil = p.line(x = 'Unnamed: 0', y = 'oil_sum', source = source, color = colour[2])
p.add_tools(HoverTool(renderers=[oil], tooltips=[('Type', 'Oil products'),('Year', '@{Unnamed: 0}'),('TWh',"@{Oil products}{0.0 a}")],mode='mouse',toggleable=False))

p.varea(x='Unnamed: 0', y1='oil_sum', y2='gas_sum', source = source, color = colour[4], alpha = 0.7, legend_label = 'Natural gas')
gas = p.line(x = 'Unnamed: 0', y = 'gas_sum', source = source, color = colour[4])
p.add_tools(HoverTool(renderers=[gas], tooltips=[('Type', 'Natural gas'),('Year', '@{Unnamed: 0}'),('TWh',"@{Natural gas}{0.0 a}")],mode='mouse',toggleable=False))

p.varea(x='Unnamed: 0', y1='gas_sum', y2='bio_sum', source = source, color = colour[0], alpha = 0.7, legend_label = 'Biofuels and waste')
bio = p.line(x = 'Unnamed: 0', y = 'bio_sum', source = source, color = colour[0])
p.add_tools(HoverTool(renderers=[bio], tooltips=[('Type', 'Biofuels and waste'),('Year', '@{Unnamed: 0}'),('TWh',"@{Biofuels and waste}{0.0 a}")],mode='mouse',toggleable=False))


#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data Source: International Energy Agency -'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = '*A terawatt-hour is a unit of energy equal to outputting one trillion watts for one hour'
caption1 = Label(text=msg, **label_opts, text_font_size = '7pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')
p.legend.location = 'top_left'


p.xaxis.major_label_orientation = 120
p.toolbar.active_drag = None

p.yaxis[0].formatter = NumeralTickFormatter(format="0,0")

show(p)
save (p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/nigeria_tfc.html'

In [749]:
rus = pd.read_csv('oil_production.csv', sep = ';')
rus = rus.iloc[:,:-1]
rus.columns = ['country', 'production']
#Oil production (thousand barrels daily in 2020)
rus = rus[1:18]

for index, row in rus.iterrows():
    if 'Total' in row[0]:
        rus.drop(index, inplace = True)
        
#for index, row in df.iterrows():
  #  if row['a'] > 0:
        #df.drop(index, inplace=True)
rus['c'] = colour
#times thousand to get all barrels
rus['production'] = rus.production *1000
#divide by million
rus['mil'] = rus['production']/1000000

In [750]:
rus

                 country  production        c     mil
3                     US  16476000.0  #1f77b4  16.476
5           Saudi Arabia  11039000.0  #ff7f0e  11.039
6                 Russia  10667000.0  #2ca02c  10.667
10                Canada   5135000.0  #d62728   5.135
11                  Iraq   4114000.0  #9467bd   4.114
12                 China   3901000.0  #8c564b   3.901
13  United Arab Emirates   3657000.0  #e377c2   3.657
15                  Iran   3084000.0  #7f7f7f   3.084
16                Brazil   3026000.0  #bcbd22   3.026
17                Kuwait   2686000.0  #17becf   2.686

In [752]:
output_file('oil_top10.html')
#data:BP statistical review
source = ColumnDataSource(rus)

p = figure(x_range = rus.country, y_range = (0,20),y_axis_label = 'Million barrels per day', x_axis_label = 'Country', 
           title ='Russia was the third biggest oil producer in 2020',
           toolbar_location=None, sizing_mode = 'stretch_both')

p.add_layout(Title(text="Top ten global oil producers in 2020", text_font_style="italic", text_font_size = '10px',), 'above')

oil = p.vbar(x='country',bottom = 0, top = 'mil', width =0.75, source = source, fill_color = 'c', line_color = 'c')
#imp = p.scatter(y='year',x = 'imports', source = source, size = 5, fill_color = colour[0], line_color = colour[0])
p.add_tools(HoverTool(renderers=[oil], tooltips=[('Oil production', '@mil{0.0} million barrels per day')],mode='mouse',toggleable=False))


#Disable scientific notation on axes

p.left[0].formatter = NumeralTickFormatter(format="0,0")

#p.xaxis.minor_tick_line_color = None
p.toolbar.active_drag = None
#p.legend.location = 'top_right'
p.xaxis.major_label_orientation = 120

#add data sources below charts
label_opts = dict(x = 0, y = 0, x_units = 'screen', y_units ='screen')
msg = 'Data Source: BP Statistical Review of World Energy 2021'
caption1 = Label(text=msg, **label_opts, text_font_size = '8pt', text_font_style = 'italic')
p.add_layout(caption1, 'below')

show(p)
save(p)

'/Users/kajsarosenblad/Documents/private/Skrivet/BBC/Carbon net zero/oil_top10.html'